### ISSUE TITLE
Mutation in RORA and Autism spectrum disorder (ASD) 

### ISSUE THREAD

**Issue by MichaelaFux** [OD4RD/Main-Help-Desk#101]
We have a patient who shows a mutation in exon 5 of the RoRa gene (OMIM 600825). This mutation seems to be related with Autism spectrum.
I could not find any information on OMIM 600825 in Orphanet. Does this mean that it is not rare or is that disease not yet indexed in Orphanet? 

Thank you for your support.
Michaela

**Comment by OrphanetSwitzerland** [comment]
After discussion with Michaela, we invite you to consider the creation of the entity “Intellectual developmental disorder with or without epilepsy or cerebellar ataxia” (OMIM 618060) linked to RORA gene.

Please see: https://pubmed.ncbi.nlm.nih.gov/29656859/

**Comment by JTorphanet** [comment]
Dear @MichaelaFux, @OrphanetSwitzerland, 

Thank you for your message, I will review this request in October and I will let you know ASAP. 

Thank you for your patience, 
Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

We have reviewed this request and we do not validate this creation. There is only one publication and the clinical picture seems to be non-specific (ID, epilepsy, motor delay and no facial dysmorphism) and not well defined for the moment ("a clinical spectrum of neurodevelopmental delay with at least two different presentations" and "In addition to these two groups, three individuals exhibit only mild ID without behavioral problems). We prefer to wait further publications to be sure of the delimitation of the clinical picture. 

The RORA gene will be added to ORPHA 528084 "Non-specific syndromic ID" and the OMIM number 618060 as BTNT relationship. Unfortunately, due to a technical issue affecting the database we are not able to implement any changes for the time being. 

Moreover, we have detected a possible lack of entities related to epileptic syndrome and we will do a deeper work early in 2024 to evaluate this. 

I wish you a very happy festive season !
Best, 

Julie
