### ISSUE TITLE
Elejalde syndrome / disease

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#108]
Dear all,

There are two disorders with similar synonyms:

[ORPHA:221054](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=18934)   (Disorder)   Acrocephalopolydactyly
Synonym(s) : Elejalde **syndrome**

[ORPHA:33445](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=10323)   (Disorder)   Neuroectodermal melanolysosomal disease
Synonym(s) : Elejalde **disease**

According to OMIM, both disorders are known as "Elejalde syndrome".
On Orphanet the synonym for ORPHA:33445 is "Elejalde disease", but in the abstract it is always called "syndrome" (which is the synonym for ORPHA:221054).

"_Definition: Elejalde syndrome (ES) is characterized by silvery to leaden hair, bronze skin colour in sun-exposed areas and severe neurological impairment._"

Could you correct the summary to avoid this confusion?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Can you please take a look at this when you get the chance? Technically it might be ok to stay like this because it is 'Elejalde syndrome/disease' as synonym for each ORPHAcodes but then the abstract and short definition of ORPHA:33445 would need to be adjusted accordingly. 

Thank you, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear Marie Cécile and Orphanet-ES, 

I am currently working on these two entity in order to clarify the usage of same synonyme as well as the curation of the texts, I will update you once the proper actions we are taking are completed, 

Best wishes, 

Aysegul

**Comment by Orphanet-AysegulSenol** [comment]
Dear Orphanet-ES, 

I would like to update you on the confusion caused by the usage of the same synonyme "Elejalde syndrome/disease" for two different entities in Orphanet:

The problem was both entities were described by Elejalde et al. (PMIDs: 890100 and 474620 where they described  Acrocephalopolydactyly (Orpha 221054) and  Neuroectodermal melanolysosomal disease (Orpha 33445) respectively). Thus, in theory usage of "Elejalde syndrome" (and not disease actually, it is not commonly used) for both diseases in literature and in Orphanet is correct. However as you had mentioned also it is confusing. To clarify this issue it has been decided to remove the synonymes "Elejalde syndome" and "Elejalde disease", and instead to add "Elejalde neuroectodermal melanolysosomal disease" and  "Elejalde acrocephalopolydactyly" as new synonymes. These changes will appear in 24h.

Best wishes, 

Aysegul

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-AysegulSenol ,

Thanks for your answer.

It seems to me to be a very appropriate solution, because it maintains the name but clarifies the difference between both clinical entities.

I will be waiting for its publication to also correct the Spanish translation.

Best wishes,

María Elena

**Comment by Orphanet-AysegulSenol** [comment]
Dear Maria Elena, 

Thank you for your nice comment. I wanted to confirm that the modifications are now visible in Orphanet.

Best wishes,

Aysegul
