### ISSUE TITLE
Use of more than 1 ORPHAcode

### ISSUE THREAD

**Issue by MartinArles** [OD4RD/Main-Help-Desk#11]
This issue is raised quite frequently in the context of a working group gathering together coders from the main Swiss hospitals (in their job, they receive the patients’ files and have to suggest one or more ORPHAcodes): 

To complement the ORPHAcode to be more precise: As, for now, the information systems in the Swiss hospitals are not prepared to include other terminologies such as HPO, there is a tendency to add more than one OC to better characterize the patient (going against the Orphanet recommendation).
Examples:
-	Down syndrome: In addition to ORPHA:870, coding also ORPHA:99103 (Atrial septal defect, ostium secundum type)
-	Xp21 deletion syndrome: In addition to ORPHA:261476, coding also ORPHA:98896 (Duchenne muscular dystrophy)

This issue is actually going to be discussed soon with the Steering Board of the Swiss Rare Disease Registry

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland,

Regarding the case about coding Down Syndrome, ORPHA:870 associated with ORPHA:99103 describing an 'Atrial septal defect, ostium secundum type', we always recommend to not used ORPHAcode for malformation signs.
Since cardiac defects are often present and considered as one of the main features among clinical signs of Down syndrome (a multisystemic disease) the major recommendation is to code with ORPHAcode of the main disease only. Otherwise coders comprise statistical analysis counting this patient 2 times for instance. Please use https://github.com/OD4RD/Main-Help-Desk/wiki/Coding-Recommendations to support your answer to swiss coders.

Regarding the second example for a patient presenting Xp21 deletion syndrome ORPHA:261476 + Duchenne muscular Dystrophy ORPHA:98896, I will come back to you with a precise answer since in this case Duchenne is not a clinical sign of the Xp21 deletion.

**Comment by OrphanetSwitzerland** [comment]
Hello,

Do you have any news concerning the 2nd example (Xp21 deletion syndrome ORPHA:261476 + Duchenne muscular dystrophy ORPHA:98896)?

Thanks

**Comment by OrphanetSwitzerland** [comment]
Hello,
A new reminder.
Kind regards

**Comment by OrphanetSwitzerland** [comment]
Kind reminder
