### ISSUE TITLE
ORPHA:169618 - Secondary central precocious puberty: Non rare?

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#110]
Hello,

While discussing the issue #44, the entities ORPHA:759 (Central precocious puberty) and ORPHA:169618 (Secondary central precocious puberty) became inactive because considered as non-rare.

However we just realised that these two entities are active:
ORPHA:650082 Secondary central precocious puberty in female
ORPHA:650092 Secondary central precocious puberty in male

We are a bit confused. Should they be a target for the inactive Orpha codes? Should these codes be also considered as non-rare?

Thank you

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

Thank you for your message! Indeed, within 3 months Orphanet took multiple decisions regarding these entities. 
In March, we inactivated secondary CPP, as non rare based on an internal epidemiological quality control taking into account all the recent papers. Following a request from experts, we re-evaluate the prevalence by removing some outliners and debated studies and clarify the clinical perimeter for each gender.

After a second review with experts, we have decided to create two different entities more representative of the medical practice and currently rare. 

For non-rare entities, we can't put "target" as for obsolete or deprecated ORPHAcodes, but indeed these two new entities can be used instead of "secondary central precocious puberty" ORPHAcode: 169618. 

Best regards, 

Julie
