### ISSUE TITLE
Link OMIM 617281 to ORPHA:1934

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#114]
Dear all,

An expert from a patient registry requests to link the [OMIM # 617281](https://www.omim.org/entry/617281) with the [ORPHA:1934 Early infantile epileptic encephalopathy](https://www.orpha.net/consor/cgi-bin/Disease_Search.php?lng=EN&data_id=889).

He has not provided me with more information about it but it seems that the _[DENND5A](https://www.omim.org/entry/617278)_ gene is also responsible for the DEE49 subtype of this disease. Therefore, this would imply also linking said gene.

Please tell me if I need to ask the expert for more information.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Hello @Orphanet-ES, 

I need to validate that this OMIM number falls into the scope of ORPHAcode 1934. I will let you know ASAP. 

Thank you, 

Best, 

Julie

**Comment by Orphanet-ES** [comment]
Thanks Julie,

The expert also told me that there are several OMIM/genes that could be assigned to ORPHA:1934 (looking for "epileptic encephalopathy, early infantile"), so maybe you could do a broader review in search of these codes.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

Thank you for this information. I have reviewed the request: 
- As the expert raised, we will add the OMIM number 617281 to ORPHA 1934 Early infantile epileptic encephalopathy as BTNT relationship
- About the other OMIM numbers related to "epileptic encephalopathy, early infantile" I have detected 93 OMIM numbers that could be potentially linked to this ORPHAcode. I will check one by one and if needed, add to this entity. 

Unfortunately, due to a technical issue affecting the database we can not implement any changes for the time being. As soon as it is possible, I will do it. 

Thank you and I wish you a very happy festive season! 

Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear @JTorphanet ,

Thank you for taking into account the proposal of the Spanish expert.

I will inform him that the OMIM he proposed will be added once the database is workable, and that you will gradually review the rest of the OMIM to include those that apply.

Thank you and I wish you a very happy festive season!

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Hello @Orphanet-ES, 

Sorry we had a lot of modifications to implement and I forgot this one, I have just done the modification. It will be visible tomorrow on our website. 

Thank you very much for the reminder, 
Best, 

Julie
