### ISSUE TITLE
Folate transporter 1 deficiency and SLC19A1 gene' update

### ISSUE THREAD

**Issue by turnovec** [OD4RD/Main-Help-Desk#115]
Hello all,

I was asked by one Czech expert to update phenotype relations for gene SLC19A1, which was previously linked on Orphanet just to methotrexate (but now I don't see this relation). They published this paper https://pubmed.ncbi.nlm.nih.gov/32276275/ (patient with anemia), but there is also this https://pubmed.ncbi.nlm.nih.gov/36517554/, which refers another two patients (with immunodeficiency). On OMIM (600424) there is now also mention about megaloblastic anemia.

Thanks.

**Comment by turnovec** [comment]
Hi, I was again contacted by prof. Viktor Kožich (he also sent mail to disease.orphanet@inserm.fr and Aysegul.Dilsizoglu@inserm.fr) regarding this new disease, there is now another new paper about two more patients:
https://pubmed.ncbi.nlm.nih.gov/36745868/

**Comment by Orphanet-AysegulSenol** [comment]
Dear @turnovec , 

I would like to update you that following the evaluation of request from Pr. V Kozich, a new entity with the main name "Megaloblastic anemia-immunodeficiency  due to folate transporter 1 deficiency"  is now created (ORPHA: 661412). Gene SLC19A1 will be linked to this entity shortly. 

Best wishes, 

Aysegul
