### ISSUE TITLE
Behr syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#118]
Hi!  I am not finding this condition listed in Orphanet but it is listed in OMIM and it is rare. 

Please see OMIM: https://omim.org/entry/210000 and GARD: https://rarediseases.info.nih.gov/diseases/849/behr-syndrome
There is also a GR that includes Behr syndrome: https://www.ncbi.nlm.nih.gov/books/NBK487393/
Pubmed search: https://pubmed.ncbi.nlm.nih.gov/?term=Behr+syndrome

Note than when searching for it in Orphanet a list for Behr-like syndrome comes up: https://www.orpha.net/consor/cgi-bin/Disease_Search_Simple.php?lng=EN This does not include Behr syndrome.

Thank you! Gioconda Alyea

**Comment by JTorphanet** [comment]
Hello @galyea123, 

I rapidly checked our archives and this syndrome was excluded from the Orphanet nomenclature 6 years ago. It turned out to be a historical description corresponding to several syndromes. 

Some comments related to this decision: 
Since 1979, Behr syndrome is thought to be a manifestation of a heterogeneous group of disorders (PMID: 571977 suggested in its conclusion relationship to infantile neuroaxonal dystrophy). 
Several publications notes the heterogeneous nature of this "syndrome":
Cases cited as "Behr variant rather than Behr syndrome" : PMID: 17977780, PMID: 15924081, PMID: 15770348
« This clinical entity (Behr syndrome) is probably a heterogeneous group of disorders, whose real causes are mostly unknown. » (PMID: 21112924) 

This entity is now used as a keyword for: 
- ORPHAcode: 67047 3-methylglutaconic aciduria type 3
- ORPHAcode: 1215 Autosomal dominant atrophy plus syndrome 
- ORPHAcode: 320375 Autosomal recessive spastic paraplegia type 55
- ORPHAcode: 289560 Mitochondrial memebrane protein-associated neurodegeneration 

Considering the long time since this decision, I would prefer to take another look before rejecting this creation. 
FYI, we have a delay of 2 months to treat this kind of demand but I will let you know as soon as I have a decision.

Best,

Julie

**Comment by galyea123** [comment]
Thank you, Julie!  I appreciate it!

**Comment by galyea123** [comment]
Among the articles in PubMed this one seems helpful: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9223020/  (See also the GeneReview.

**Comment by JTorphanet** [comment]
Dear @galyea123, 

I just want to let you know that we are asking for an expert advice to help us and better define the perimeter with another entity we already have on Orphanet. 
I will give you more info ASAP. 

Best, 

Julie

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________

**Comment by JTorphanet** [comment]
Dear @galyea123, 

We have received experts' feedback and they confirmed that both entities are independent. Moreover, they have validated the reactivation of ORPHA: 1239 Behr syndrome. It will be visible in early March. 

Best regards, 

Julie
