### ISSUE TITLE
Tarlov cyst

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#119]
Hi!  Orphanet list this condition but it is not rare (only the symptomatic form).  Please let me know if this will be continued to be listed. The most recent published meta-analysis suggests a global prevalence rate of 4.27%; in the United States, it is 3.82% of the population. Tarlov cysts are more common in those of the female sex (female 7.01% vs. male 4.05%). The same study also showed that 15.59% of the cysts are symptomatic.[[](https://www.ncbi.nlm.nih.gov/books/NBK582154/#)

**Comment by MCecile-US14** [comment]
Dear @Gioconda, 

Thank you for your valuable comment. 
Indeed after reevaluation, Orphanet' medical and scientific committee decided to take out 'Perineural cyst' entity ORPHA:65250 (Synonym: 'Tarlov cyst') of its Nomenclature as this condition is considered non rare in UE based on the recent large meta analysis conducted by Klepinowski et al., (PMID:33452905). The corresponding ORPHAcode will be inactivated in the coming weeks.

Kind regards, 
Marie-Cécile

**Comment by galyea123** [comment]
Thank you for your review!  Much appreciated. Gioconda

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

Related to the "unlinked entities" task, I deleted a Spanish association for this disease, but the association disagrees with this decision because it considers that your disease is rare.

After reading the article on which you based your decision (PMID:33452905), I have been unable to extract a clear phrase that I can convey to the association.
Could you help me justify this decision?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Indeed, after evaluation of this entity, only symptomatic (minority) perineural Tarlov cyst were actually considered rare as the large form is more common and often asymptomatic.

See PMID:33452905 citations below you can use:

- "Spinal perineural Tarlov's cysts (TCs) are considered incidental findings that occasionally might exert pressure upon nerve roots and correspond with patients' signs and symptoms."

- "Global pooled prevalence of TCs was 4.18%"

- "Spinal perineural (Tarlov) cysts are found in a minority of population. S2 level of the sacral bone is affected most frequently. There is female predominance. Correspondence with symptoms is seen in less than one-fifth of TCs. Studies with stronger evidence level are needed to corroborate the results. The purported high incidence in PGAD requires confirmation in case-control studies for the risk-ratio calculation."

- "Spinal perineural Tarlov’s cysts are thought to be common radiological findings, often incidental and asymptomatic. They are a dilation of the nerve-root sheath and tend to communicate with subarachnoid space through a valve-like mechanism, which thus contain cerebrospinal fluid (CSF) as well as neural tissue"

Then if we consider only the rarity of the symptomatic TC when doing the point prevalence calculations based on the publication meta-analysis, it cannot be considered rare as:
"Pool prevalence of TC is 4.18%"
"Symptomatic TC represents one fifth of total TC" = 20%
4.18/20=0,209%
The threshold of rarity is 0.0005%; thus even just the symptomatic form of Tarlov Cyst is not rare.

Hope this helps to clarify, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 , 

Thank you very much for the extensive explanation about the exclusion of this disease from Orphanet.
In the case of patient associations, which often feel abandoned when this happens, it is important to be able to clearly convey Orphanet's decision to them.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Of course it is essential and we are here to provide updated informations as much as we can :)
We apologize again for the delay between decision implementation (for ORPHAcodes inactivations in particular) and access to the documentation and Orphanet rational for exclusion (as the 'disease meeting report').
As mentioned in the last meetings, we are hardly working to find a better way to communicate and produce monthly disease meeting decisions report with National Hubs and Orphanet teams. 

Thank you for your understanding, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-Italia** [comment]
Dear @MCecile-US14 and @Orphanet-ES ,
I've just received a phone call by the president of a commettee focused on undiagnosed/rare diseases, speaking on behalf of the representative of a PO dedicated to this disease in Italy. She asked about the possible inactivation of ORPHA:65250, saying that a spanish PO had been informed about the imminent exclusion of the disease from the Orphanet database, being thereby worried about it. I think I can confirm the imminent exclusion, but I also think she will ask me about an approximate date for this to happen, can you provide it? thanks.
Kind regards
Michele

**Comment by galyea123** [comment]
Hi!  I  have read all the related messages and I thought  about similar situations we have.  Sometimes we keep diseases with the disclaimer (as you also do) that the disease is not rare.  Thank you! Gioconda

**Comment by MCecile-US14** [comment]
Dear @Orphanet-Italia, 

Thank you for your message, ORPHA:65250 'Tarlov cyst' has been flagged recently as "Non rare In EU" by Orphanet medical and scientific commitee but as you know all Orphanet database is currently frozen (from 27/11 data version), preventing anyone to do the proper modification and update the changes into the database. 
I am also the one in charge to transmit the translation reports which are also postponed until all National Orphanet IS can also translated created and modified entities on the database.

You can consider ORPHA:65250 inactivated (because non rare in EU) from now on and you will already find the prevalence justifications  and PMID reference above in this conversation (answered to @Orphanet-ES) to help you answer to the italian professionnal who contacted you about this.

Kind regards, 
Marie-Cécile

**Comment by Orphanet-Italia** [comment]
> Hi! I have read all the related messages and I thought about similar situations we have. Sometimes we keep diseases with the disclaimer (as you also do) that the disease is not rare. Thank you! Gioconda

It's always difficult to communicate inactivations. Thank you for your contribution

**Comment by Orphanet-Italia** [comment]
> Dear @Orphanet-Italia,
> 
> Thank you for your message, ORPHA:65250 'Tarlov cyst' has been flagged recently as "Non rare In EU" by Orphanet medical and scientific commitee but as you know all Orphanet database is currently frozen (from 27/11 data version) in order to protect data, preventing anyone to do the proper modification and update the changes into the database. I am also the one in charge to transmit the translation reports which are also postponed until all National Orphanet IS can also translated created and modified entities on the database.
> 
> You can consider ORPHA:65250 inactivated (because non rare in EU) from now on and you will already find the prevalence justifications and PMID reference above in this conversation (answered to @Orphanet-ES) to help you answer to the italian professionnal who contacted you about this.
> 
> Kind regards, Marie-Cécile

Thank you Marie-Cécile, also for the documentation provided.
Kind regards

Michele

**Comment by Orphanet-ES** [comment]
Dear @caterina-lucano-orphanet ,

Sorry to bother you, but since Marie-Cécile left, I don't know who should be assigned to the topics.
I have reopened this topic because a Spanish doctor has contacted us to propose again the inclusion of this disorder in Orphanet.

I attach her letter in which she defends her position to consider this disease as rare and the request that has been made to the European Commission in this regard and its response.
As both documents are in Spanish, please let me know if you need us to translate any specific section.

I have located the link to the Spanish petition that has been made to the European Commission:
https://www.europarl.europa.eu/petitions/en/petition/content/0709%252F2024/html/Petici%25C3%25B3n-n.%25C2%25BA%25C2%25A00709%252F2024%252C-presentada-por-Carlos-Navarro%252C-de-nacionalidad-espa%25C3%25B1ola%252C-sobre-el-reconocimiento-del-s%25C3%25ADndrome-de-Tarlov-como-enfermedad-rara

Regarding the response given to this request, a previous request from a French association is mentioned, and I also link the page where this response is given.
https://www.europarl.europa.eu/doceo/document/PETI-CM-753801_EN.html

I think that the rarity of this disorder has been clearly ruled out, but I would like to convey all the arguments that have been sent to us so that you can consider them or in case you can provide a more forceful response that we can transmit to those interested (doctors or patient associations).

Kind regards, 

María Elena

[solicitud de inclusion de los Quistes de Tarlov en la lista de Orphanet.pdf](https://github.com/user-attachments/files/18183532/solicitud.de.inclusion.de.los.Quistes.de.Tarlov.en.la.lista.de.Orphanet.pdf)
[Respuesta de la comisión Europea a la solicitud de Inclusión de los QT como ER.pdf](https://github.com/user-attachments/files/18183534/Respuesta.de.la.comision.Europea.a.la.solicitud.de.Inclusion.de.los.QT.como.ER.pdf)

**Comment by caterina-lucano-orphanet** [comment]
Thank you Maria-Elena, I am receiving many solicitations on this topic, and we have therefore decided to investigate this issue again. We will have a new epidemiologist coming in January, and this will be one of the first issues she will treat as soon as she is trained to Orphanet's procedures.

Kind regards,
Caterina

**Comment by Orphanet-ES** [comment]
Thanks Caterina,

I hope we can give them a clear answer, for or against the definition of this disorder as a rare disease, since they consider the Orphanet criteria for excluding this disorder from our nomenclature to be insufficient.

Kind regards, 

María Elena

**Comment by galyea123** [comment]
[like]  Gioconda Alyea reacted to your message:
________________________________

**Comment by Orphanet-ES** [comment]
Dear @caterina-lucano-orphanet ,

Is there any news regarding this issue?

Kind regards, 

María Elena

**Comment by akukava** [comment]
Hello,

I would like to respond to your request with the research carried out to clarify the issue of the rarity of Tarlov cyst.
According to the most recent Meta-Analysis (PMID: 33452905) 22 radiologic studies of level 3 evidence (13,266 subjects) Random-effects model estimated global pooled prevalence of symptomatic Tarlov’s cysts is 4.18% (95% CI 2.47– 6.30).
According to the recommended review (PMID: 37828278) which contains 9 studies (MRI results,11198 subjects) calculated global pooled prevalence for sacral TCs is 3,6%.
In (PMID: 33452905) and (PMID: 37828278) several references are common. The calculated prevalence of TCs (PMID: 33452905: 4,18%; PMID: 37828278:3,6%) shows the prevalence of TCs among individuals who underwent medical examinations in the lumbosacral region due to various health problems. 
Therefore, we can’t directly generalize the result obtained above to the general population as the estimated prevalence of TCs, as it will be overestimated and biased.
In order to estimate the prevalence of symptomatic/all types of TCs in the general population the two-stage research was respected.
Was found the causes of the medical examinations (the references of the two aforementioned articles were checked).
Among the various causes the low back pain was chosen. To find the estimated prevalence of low back pain worldwide, the search was performed on PUBMED. A systematic review of the global prevalence of low back pain dated 2012 was found.
 

5% from individuals with low back pain who made medical exams, have symptomatic (?) TCs. In order to calculate symptomatic and/or all kind of TCs in general population based on the prevalence of TCs in patients with low back pain (LBP), the prevalence of LBP is needed. 
The mean global point prevalence of LBP = 18,3%
TCs Pr=0,92%
As only 1/5 of TCs are symptomatic, Pr of all type of TCs is 4,6%
In the global population, estimated prevalence of symptomatic TCs is roughly around 0,92% and all types of TCs – around 4,6%. As the threshold of rarity is 0.0005 (0,05%), neither symptomatic nor all types of TCs are rare.

Kind regardes,

Ana KUKAVA

ORPHANET - INSERM US14

**Comment by caterina-lucano-orphanet** [comment]
Thank you @akukava for giving insights on this issue.

I am tagging all people who interacted with this ticket before so that they all see your reply:
@galyea123 @Orphanet-ES  @Orphanet-Italia 

Thank you,
Caterina

**Comment by Orphanet-ES** [comment]
Dear @akukava ,

Thank you very much for the new analysis of the prevalence data for this disorder.
I will pass this information on to the Spanish patient association and others interested in the disease, and I hope we can definitively close the discussion about the non rarity of Tarlov cysts.

King regards, 

María Elena
