### ISSUE TITLE
Cerebral amyloid angiopathy-related inflammation (CAA-RI)

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#121]
Hello,

Please consider the inclusion in the nomenclature of the entity Cerebral amyloid angiopathy-related inflammation (CAA-RI).

The request comes from a coder at a Swiss hospital. They have a patient with this diagnosis (Cerebral amyloid angiopathy-related inflammation). We have no more context to provide.

Bibliographic references including case reports and an estimation of the prevalence in Japan:

- PMID: [33625036](https://pubmed.ncbi.nlm.nih.gov/33625036) - Cerebral amyloid angiopathy-related inflammation: current status and future implications
“There have been few epidemiological studies on CAA-RI. A nationwide survey demonstrated that its prevalence is about 0.13 per 100,000 population in Japan”
- PMID: [37239219](https://pubmed.ncbi.nlm.nih.gov/37239219) - Cerebral Amyloid Angiopathy-Related Inflammation (CAA-rI): Three Heterogeneous Case Reports and a Focused Literature Review
- PMID: [36453271](https://pubmed.ncbi.nlm.nih.gov/36453271) - Clinical, Neuroimaging, and Genetic Markers in Cerebral Amyloid Angiopathy-Related Inflammation: A Systematic Review and Meta-Analysis

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Thank you for your request and the details provided. I am adding this request in the December evaluation list 
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

After revewing this entity, Orphanet scientific and medical committee decided not to create it as it is not clear it is a distinct phenotype from ORPHA:85458 'Hereditary cerebral hemorrhage with amyloidosis' disorder or one of its 7 subtypes. It seems inflammation can happen as a consequence in CAA phenotypes (mentioned in the asbtract 'Management & treatment' section, "Corticosteroids can ameliorate symptoms caused by CAA-related inflammation").

Nonetheless, considering the current and numerous reports on CAA-rI, we are not sure our classification representation is relevant in the field.
In order to clarify this we will touch base with experts from the Greenberg lab (Boston, MA) and/or the International CAA association to see if modifications needs to be integrated.

This being said, as you know we are currently unable to update the database, as it has been frozen (27/11 data version) in order to protect data. As soon as it will available again we will modify and add 'CAA-rI' as a Keyword of ORPHA:85458 to facilitate the search. For the moment patients can be coded using this code and we will keep you updated if changes are being made according to CAA experts in the future.

Kind Regards, 
Marie-Cécile
