### ISSUE TITLE
Orpha.net down?

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#123]
Hello,

We cannot access Orpha.net in Norway. Is it our issue or is the database down?

What is the best way to let you know when this happens? Through GitHub, RIC or by e-mail (to who)?

Best regards,
Lene

**Comment by Orphanet-ES** [comment]
Dear @LeneMartinsen ,

In Spain it has also not been working all morning.
I hope they have been able to solve it tomorrow.

Best regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @OD4RD/coordinationteam, dear all

Thank you for your post indeed Orpha.net' servor is down In France and everywhere (since 30/10/23) as far as we know. The IT direction is actively working on it with our team, I will update this post as soon as it is solved

Thank you for your understanding and your patience
Kind regards,
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @OD4RD/coordinationteam, dear @LeneMartinsen, dear @Orphanet-ES,

**31/10/23 10:20 Orpha.net website is working (can be slower than usual)**

Best
