### ISSUE TITLE
Cohen-Gibson syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#128]
Hi!  I was not able to find this syndrome in Orphanet.  [OMIM page] (https://www.omim.org/entry/617561 url) for Cohen-Gibson syndrome links to Orphanet page for Weaver syndrome.  

Thank you for your help,
Gioconda Alyea

See this reference too: https://pubmed.ncbi.nlm.nih.gov/30793471/

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Could you please look at this request and see if Cohen-Gibson syndrome is to be considered as a separate entity from Weaver syndrome ?

Thank you, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear @MCecile-US14, 

Sure, I will look into it as soon as possible. 

Best, 

Aysegul

**Comment by Orphanet-AysegulSenol** [comment]
Dear @galyea123, 

I would like to update you on your request of creation for Cohen-Gibson syndrome. It has been decided to create this entity, however it will take some time to display it at the website due to some technical issues affecting the database. Thus for now I am not able to share the new Orpha code with you but you can consult it probably around mid-January at the website. 

Thank you for your attention, 

Kind regards, 

Aysegul

**Comment by galyea123** [comment]
Thank you for the update. Really appreciated!

Happy Holidays,

Gioconda Alyea

**Comment by Orphanet-AysegulSenol** [comment]
Dear @galyea123, 

Just wanted to update you that Cohen Gibson syndrome with the ORPHAcode: 659396 is now available at Orphanet website. 

Best wishes, 

Aysegul

**Comment by galyea123** [comment]
Thank you Aysegul!
