### ISSUE TITLE
Specific identifier available for the Nomenclature Package?

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#133]
We have received a request from a team of experts who want to implement the Alpha-ID SE into a HL7 FHIR resource (CodeSystem). To do so, they also need information about the underlying Orphanet Nomenclature package. Is there an OID or specific identifier available for the corresponding releases that refers to the Nomenclature Package? A canonical URL would also be appreciated.

**Comment by davidlagorce** [comment]
Dear user, the best way is to use the ORPHAcode RestAPI : https://api.orphacode.org/
Best regards
David

**Comment by MCecile-US14** [comment]
Dear @OrphanetDE, please find below complementary informations regarding this request:
There is no OID (Object IDentifier), we only provided version date of updated annual Nomenclature Pack since there was no need of numbering version so far (one version replacing the other, each July as published on orphadata.com and RD-CODE Github). API is following strightly Pack’version.

For further informations, questions or discussion do not hesitate to comment the current ticket and/or re open it as an ongoing request. Thank you
