### ISSUE TITLE
Wrong gene linked to Zimmermann-Laband syndrome

### ISSUE THREAD

**Issue by turnovec** [OD4RD/Main-Help-Desk#135]
Hello,

there are four genes linked to Zimmermann-Laband syndrome (ORPHA:3473) on Orphanet:

ATP6V1B2
KCNH1
KCNMA1
KCNN3

But according to OMIM there are only three types of this Syndrome, each with its specific gene:
Zimmermann-Laband syndrome type 1 (OMIM:#135500, gene KCNH1)
Zimmermann-Laband syndrome type 2 (OMIM:#618658, gene KCNN3)
Zimmermann-Laband syndrome type 3 (OMIM:#616455, gene ATP6V1B2)

The gene KCNMA1 is according to OMIM associated with some different diseases:
OMIM:618596 - {Epilepsy, idiopathic generalized, susceptibility to, 16}
OMIM:617643 - Cerebellar atrophy, developmental delay, and seizures
OMIM:618729 - Liang-Wang syndrome
OMIM:609446 - Paroxysmal nonkinesigenic dyskinesia, 3, with or without generalized epilepsy

So it looks like KCNMA1 shouldn't be linked to Zimmermann-Laband syndrome.

**Comment by MCecile-US14** [comment]
Dear @turnovec, 

Thank you for your message.
I will wait to assign your request as the new Orphanet gene manager will start in December, so this will be evaluated as soon as possible after his arrival.

Kind Regards, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @turnovec, 

Liang-Wang syndrome is considered in Orphanet to be part of the Zimmermann-Laband syndrome (Orpha:3473) and defined as a Keyword. In the past we decided with the scientifique and medical committee of Orphanet to not create the Liang-Wang syndrome because this entity is similar in presentation to Zimmermann-Laband syndrome. However, we still linked the responsible gene for this entity to Zimmermann-Laband syndrome.  You can find more information in [31152168 ](https://pubmed.ncbi.nlm.nih.gov/31152168/) where they aknowledge the overlapp between Liang-Wang and Zimmermann-Laband syndromes. 

If you have any more doubts, I will be happy to help out. 

Best regards, 
Mickaël
