### ISSUE TITLE
Epstein-Barr virus-positive diffuse large B-cell lymphoma of the elderly ORPHA:289661 (name change)

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#136]
Epstein-Barr virus-positive diffuse large B-cell lymphoma of the elderly name has changed.  Please see:  "Epstein-Barr virus (EBV)-positive diffuse large B cell lymphoma (DLBCL) is known for distinct clinical features. This disease was formerly designated as EBV-positive DLBCL of the elderly, but the restriction to elderly patients has been removed, and the World Health Organization classification revised 4th edition lists EBV-positive DLBCL, not otherwise specified (NOS). Epstein-Barr Virus-Positive Diffuse Large B Cell Lymphoma" 

Some sources that may be helpful for your review include:

- https://www.ncbi.nlm.nih.gov/books/NBK578250/ 
- https://hero.epa.gov/hero/index.cfm/reference/details/reference_id/786623
- https://ashpublications.org/bloodadvances/article/5/16/3227/476566/Clinicopathological-features-and-survival-in-EBV 
- https://www.nature.com/articles/s41375-022-01804-w
- https://onlinelibrary.wiley.com/doi/10.1002/ajh.26579

Thank you, Gioconda Alyea

**Comment by JTorphanet** [comment]
Dear @galyea123, 

Thank you for your suggestion. We have checked recent papers and we have decided to remove "of the elderly" in the main term of ORPHAcode 289661 and mentioned as synonym "Epstein-Barr virus-positive diffuse large B-cell lymphoma, not otherwise specificied". 

These changes will be visible on our website in the next coming days. 
Have a nice day, 

Julie

**Comment by galyea123** [comment]
Thank you for the update, Julie!  Gioconda Alyea
