### ISSUE TITLE
Congenital athymia

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#138]
Hi!  I am currently working on updating a NORD report in what is called "congenital athymia"  and I did not find this listed as it in Orphanet and started reviewing the related conditions to thymus anomalies in Orphanet.

The group "immunodeficiency due to absence of thymus" could be a synonym for congenital athymia but I found some other issues. 

Both "Immunodeficiency due to absence of thymus" ORPHA:331220 (which includes  22q11.2 deletion syndrome ORPHA:567
 CHARGE syndrome ORPHA:138 and  T-cell immunodeficiency with thymic aplasia (Nezelof syndrome) ORPHA:83471) and "Severe combined immunodeficiency due to FOXN1 deficiency"  are currently classified under "Syndrome with combined immunodeficiency"ORPHA:331217, but the immunodeficiency due to FOXN1 deficiency is listed separately and not under absent thymus:

•	Primary immunodeficiency due to a defect in adaptive immunity ORPHA:179006 
o	Syndrome with combined immunodeficiency ORPHA:331217 
o	Absent thumb-short stature-immunodeficiency syndrome ORPHA:2951
o	Anhidrotic ectodermal dysplasia-immunodeficiency-osteopetrosis-lymphedema syndrome ORPHA:69088
o	Autoinflammatory syndrome with pyogenic bacterial infection and amylopectinosis ORPHA:329173
o	Combined immunodeficiency due to CRAC channel dysfunction ORPHA:169090
o	Combined immunodeficiency-enteropathy spectrum ORPHA:436252
o	Developmental delay-immunodeficiency-leukoencephalopathy-hypohomocysteinemia syndrome ORPHA:619979
o	DNA repair defect other than combined T-cell and B-cell immunodeficiencies ORPHA:169346
o	Dyskeratosis congenita ORPHA:1775
o	Facial dysmorphism-immunodeficiency-livedo-short stature syndrome ORPHA:352712
o	Hennekam syndrome ORPHA:2136
o	Hepatic veno-occlusive disease-immunodeficiency syndrome ORPHA:79124
o	Hereditary folate malabsorption ORPHA:90045
o	Hoyeraal-Hreidarsson syndrome ORPHA:3322
o	Hyper-IgE syndrome ORPHA:331223
o	Hypohidrotic ectodermal dysplasia with immunodeficiency ORPHA:98813
o	Immunodeficiency due to absence of thymus ORPHA:331220 
	22q11.2 deletion syndrome ORPHA:567
	CHARGE syndrome ORPHA:138
	T-cell immunodeficiency with thymic aplasia ORPHA:83471
o	Immuno-osseous dysplasia ORPHA:169349
o	Laron syndrome with immunodeficiency ORPHA:220465
o	Multiple intestinal atresia ORPHA:2300
o	Pancytopenia due to IKZF1 mutations ORPHA:317473
o	Severe combined immunodeficiency due to FOXN1 deficiency ORPHA:169095
o	Transcobalamin deficiency ORPHA:859
o	Vici syndrome ORPHA:1493
o	Wiskott-Aldrich syndrome ORPHA:906

It is my understanding that the condition "T-cell immunodeficiency with thymic aplasia" is caused by compound heterozygous mutations in the FOXN1 (see [OMIM](https://www.omim.org/entry/242700) and also a review:https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8249278/  

My doubts are: 

- this condition "T-cell immunodeficiency with thymic aplasia" is, in fact, part of the FOXN1 deficiency
- FOXN1 deficiency should be classified under Immunodeficiency due to absence of thymus
- Can immunodeficiency due to absence of thymus be considered a synonym of congenital athymia?

Note that for congenital athymia there is plenty of literature and also an FDA approved treatment.

I appreciate your help on this!  Thank you very much!  Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @caterina-lucano-orphanet, 

As this concern clarifications and classification issue, could you please take a look at this request when you have time?

Thank you, 
Kind regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear Gioconda, 

I am sorry for this late update but I am currently working on your request and I hope I will be able to give you a detailed answer in a short time. Meanwhile, I was wondering whether it would be possible for you to provide a source for the information that I found in NORD page which says congenital athymia can occur as an "isolated" finding (in addition to being a part of a genetic syndrome). It would be great to have some information on these isolated cases.

Thank you very much in advance, 

Best wishes, 

Aysegul

**Comment by galyea123** [comment]
Hi Aysegul!  I believe that the report was referring to [T-cell immunodeficiency with thymic aplasia](https://www.orpha.net/en/disease/detail/83471).  I will make some changes to the NORD report so this is more clear. Thank you, Gioconda

**Comment by Orphanet-AysegulSenol** [comment]
Dear Gioconda, 

It is my pleasure to let you know that we have now finalized the classification revision-where we mainly followed the IUIS classification, PMIDs: 35748970, 36198931)- for the group of disorders ORPHA 331220:  Syndome with combined immunodeficiency due to thymic defect (main name of this group is changed during this revision, previously it was named Immunodeficiency due to absence of thymus). Here I tried to summarized all the decisions that had been taken. I hope it is clear but if not please do not hesitate to let me know: 

Creation of new ORPHAcodes for: "Combined immunodeficiency due to FOXN1 haploinsufficiency" (ORPHA: 676039) , "Combined immunodeficiency due to TBX1 deficiency"(ORPHA:685017), "10p15 microdeletion syndrome" (ORPHA:687424), "10p13-p14 deletion syndrome" (ORPHA:687695) are validated. Following the last two creations, classification level of "Distal deletion 10p" (ORPHA: 1580) is changed from "disorder" to "group of disorders". 

"Severe combined immunodeficiency due to FOXN1 deficiency" (ORPHA: 169095) and "Jacobsen syndrome" (ORPHA:2308) are validated to be classified under "Syndome with combined immunodeficiency due to thymic defect" (ORPHA: 331220) whereas "T-cell immunodeficiency with thymic aplasia (ORPHA:83471) is removed from this group. 

"Congenital athymia" is added as a keywords to all these entities mentioned above to fascilitate the research as in literature it is mainly used for the absence of the functional thymus.

Best wishes, 

Aysegul
