### ISSUE TITLE
Sarcoidosis: creation of subtypes?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#142]
Dear GitHub team,

We received the following request from Prof. Dr. Guy Brusselle, HCP representative for ERN-LUNG in UZ Gent:

_Sarcoidosis is a rare disease with a very heterogeneous clinical presentation, encompassing pulmonary sarcoidosis, cardiac sarcoidosis, neurological sarcoidosis, cutaneous sarcoidosis, ocular sarcoidosis, involvement of kidney, bone, liver and/or spleen, and/or rheumatological manifestations.
Please see a recent book “ERS Monograph: Sarcoidosis, edited by Francesco Bonella, Daniel Culver and Dominique Israël-Biet.
To my opinion, a further refinement of the Orphacoding for sarcoidosis (Orphacode 797) at a “subtype of disorder” classification level seems indicated._

In Orphanet, 3 ORPHAcodes are currently present in the nomenclature relating to sarcoidosis:
- ORPHA:797   (Disorder)   [Sarcoidosis]
- ORPHA:90341   (Disorder)   [Early-onset sarcoidosis]
-  ORPHA:90340   (Disorder)   [Blau syndrome]

Would it be possible to create more specific ORPHAcodes, depending on the organ mainly affected for example (as is done by SNOMED CT)?  See: https://www.findacode.com/snomed/31541009--sarcoidosis.html 

Thank you for reviewing this request, kind regards,

Annabelle (Orphanet Belgium)

**Comment by JTorphanet** [comment]
Hello @Orphabe, 

Thank you for your message. I will manage this issue but it will be included in a bigger work that we need to start with ERN Lung. This collaboration will start in 2024 but we don't have a precise date. I will keep you informed ASAP. 

Thank you for your understanding, 
Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @Orphabe, 

I would like to inform you that the Orphanet committee has rejected the requests related to the creation of sarcoidosis subtypes. Indeed, it is well described that sarcoidosis is a multi-systemic disorder and can have multiple presentations with a proportionally different organ involvement. 

It is not possible to have a clear perimeter and an isolated form for each organ affected; we advice to use ORPHA:797 to represent all the clinical situations met in order to better represent all the patients. 

Moreover, in the abstract authors mentioned the different possible presentations: "The lung and the lymphatic system are predominantly affected, but virtually every organ may be involved. Other severe manifestations result from cardiac, neurological, ocular, kidney or laryngeal localizations. In most cases, sarcoidosis is revealed by persistent dry cough, eye or skin manifestations, peripheral lymph nodes, fatigue, weight loss, fever or night sweats, and Löfgren syndrome (an acute form characterized by fever, bilateral ankle arthritis and/or erythema nodosum and bilateral hilar lymphadenopathy)."

Do not hesistate to come back to us if needed, 
Best, 

Julie
