### ISSUE TITLE
Undiagnosed RD and ORPHAcode?

### ISSUE THREAD

**Issue by OD4RDFIN** [OD4RD/Main-Help-Desk#147]
Hi,

in Finland, clinical geneticists have specific questions related to undiagnosed rare diseases.

If there is no ORPHAcode (disorder), is it meaningful to use many different group codes for different phenotypes in the same patient? We have though about adding them group code(s) and also a code ORPHA:616874  (Rare disorder without a determined diagnosis after full investigation), because otherwise we cannot find the undiagnosed ones from the EPR systems or registries.

BR,

Satu Wedenoja
Finnish Institute for Health and Welfare

**Comment by uunter98** [comment]
Hi Satu,
Orpha coding is NOT suitable for describing a phenotype, so you should not use more than 1 Orpha code for a specific disease. It is recommended that this should be done by HPO terms (if possible in the documentation system used). 
Apart from this, the use of group codes is of course subject to local decisions, but the international agreement is that coding only happens at the disease (or subtype) level, i.e. at the level of the definite diagnosis ("aggregation level"). 
ORPHA:616874 should strictly only be used if "all reasonable efforts have been done by rare diseases experts to determine a diagnosis according to the state of the art and available diagnostic capabilities, but did not enable to conclude on a clinically known concept" (refer to the definition of this entity). 
If a patient cannot be coded because the entity does not yet exist in Orphanet, you can create a ticket for the disease team so that creation of the entity can be evaluated.
Kind regards
Ursula

**Comment by MCecile-US14** [comment]
Dear @OD4RDFIN, dear Satu, 

@uunter98 correctly answered about the ORPHAcoding recommendations Orphanet is providing saying
- More than 1 ORPHAcode should not been used for coding (except if your patient is carrying multiple RD). ORPHAcodes describe diagnosis not patients and should not been used as phenotypical descriptors (ie: HPO terms are made for this)
- The use of Group of Disorders for coding is unrecommended (except for national rules and legislatives situations eg: specific reiumbursment purposes), so that you wont biase your clinical data sorting (aggregation level corresponds to the most precise level of diagnosis assessment eg: disorder or subtype fo disorder when applicable)
- ORPHA:616874 'Rare disorder without a determined diagnosis after full investigation' should be used after its description **only** "A rare disorder for which all reasonable efforts have been done by rare diseases experts to determine a diagnosis according to the state of the art and available diagnostic capabilities, but did not enable to conclude on a clinically known concept. It is recommended to restrict the use of this entity for coding purposes to rare disease experts."

Finally, if there is no ORPHAcode existing for the diagnosis, the clinical practionner are looking for and it is a rare homogeneous condition described in the literature (affecting less than 1 person in 2000 in UE population) you should transmit us a request of creation here with the relevant documentation (see ticket label 'creation' examples).

Please keep in mind that all the justification and argument are detailed in:
- the dedicated Wiki section https://github.com/OD4RD/Main-Help-Desk/wiki/3.-Coding-Recommendations 
- the Training material (Advanced training and RD CODE guidelines) you can freely disseminate in Finland https://network.orphanet.org/od4rd2-scientific-content/

Hope this helps, 
Kind Regards
Marie-Cécile
