### ISSUE TITLE
Suitable ORPHAcode for stomach duplication

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#148]
We received a request from a physician who has a patient with a very rare stomach duplication. She is asking for a suitable ORPHAcode for this diagnosis, because stomach duplication is not included in the Orphanet nomenclature. We think that most likely ORPHAcode 238, Digestive duplication, could fit here. Is that correct?
If yes, would this ORPHAcode be suitable also for oesophagus duplication, intestinal duplication, gall bladder duplication etc.?

If yes, would it make sense to create new ORPHAcodes for the diagnoses mentioned, and classify ORPHAcode 238 as group of diseases?

During our research we have found that f.e. Esophageal duplication cyst, 100047, rectal duplication, 171220, Digestive duplication cyst of the tongue, 141071, have their own ORPHAcode and are all also classified as disorders like Digestive duplication is. Also when looking at the classification there is no connection between these 3 examples and Digestive duplication. Can you check this and reorganise it if necessary?

**Comment by MCecile-US14** [comment]
Dear @OrphanetDE, 

Thank you for your question.
Indeed you are correct that in absence of other code ORPHA:238 'Digestive duplication' would be the best option and seems appropriate regarding the diagnosis your are mentioning. Nevertheless looking deeper, it shows that Orphanet classification and representation of isolated digestive duplications is not correct with the presence of overlapping entities. 
Also we agree that there is no consistent reason to have dedicated ORPHAcodes for some of the duplications (eg. ORPHA:100047; ORPHA:171220; ORPHA:141071) classified by organ group of disorders but not in an exhaustive way.

We are currently thinking about the best proposal to overcome this issue in accordance with Orphanet classification rules.
Most likey we will create individual organ-digestive duplication missing disorder codes (ie: stomach, oropharyngeal, intestinal...) based on the reported literature. And classified it in relevant Groups of Disorders > 'Digestive tract malformation' [Group of disorders - Category] ORPHA:98039 for the most part.
Subsequently we will inactivate ORPHA:238, since it will be confusing to keep both way to codes this kind of duplication.

I will let you know the decisions taken and new codes created once it is validated (coming weeks/month)
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @OrphanetDE, 

Orphanet medical and scientific committee validated the creation of all the Gastro intestinal isolated duplications that were missing in Orphanet, please find below the list of Disorders and notably the one you request for the patient diagnosis you mentioned:

**- ORPHA:662376 'Gastric duplication' (Syn: Stomach duplication)**
- ORPHA:662388 'Gallbladder duplication'
- ORPHA:662405 'Pyloric duplication'
- ORPHA:662392 'Colonic duplication'
- ORPHA:662456 'Small intestine duplication' with 2 subtypes:
* ORPHA:662473 'Duodenal duplication'
* ORPHA:662480 'Jujeno-ileal duplication' 

All these entities will be classified under ORPHA:108967 'Non-syndromic intestinal malformation' [Group of disorders - Category] for now as Orphanet' classification for Digestive tract malformation is not correct anymore and is missing some representation, we will work on it with the help of ERNICA experts in the near future.
Therefore as a consequence ORPHA:238 'Digestive duplication' will be obsoleted and refer to the group ORPHA:108967.
Please keep in mind that from now on all Nomenclature changes will be visible the next week (and not within 24 hours as before).

Thank you for your contribution,
Kind Regards, 
Marie-Cécile
