### ISSUE TITLE
ORPHAcodes for healthy carriers?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#155]
Dear GitHub team,

We received questions from patient registry managers regarding the registration of healthy carriers:

1) **Asymptomatic form of muscular dystrophy of Duchenne and Becker in female carriers**
There is a specific ORPHAcode for "Symptomatic form of muscular dystrophy of Duchenne and Becker in female carriers" (ORPHA: 206546) but there is no ORPHAcode for non-manifesting DMD/BMD female carriers. Since ORPHAcodes are **diagnosis** codes, we assume that it makes sense not to create ORPHAcodes for the carriers who have no symptoms. However being an healthy carrier is also a kind of (genetic) diagnosis and the registration of that type of patients can be useful in the framework of healthcare planning (screening in the family, etc.). The manager of the Belgian NeuroMuscular Disease Registry (BNMDR) noticed that some non-manifesting carriers are registered by clinicians. She explained to me that these patients can be classified using CRAMP ("Computer Registry of All Myopathies and Polyneuropathies") and NIHDI classification but there is no matching ORPHAcode. So how is the registry manager supposed to deal with the coding of such healthy NMD patients? 

2) **Lynch syndrome and FAP mutation-carrier** 
Most patients remain asymptomatic for years or never develop the associated disease. However they carry the mutation(s). In the Belgian Central Registry of Rare Diseases (CRRD), these kind of patients are registered by the clinicians using the existing ORPHAcodes (respectively ORPHA:144 and ORPHA:733). But in this case, the manager of the registry cannot make the distinction between "carriers" and "actually being ill", because the centres don't always specify this info --> here again, how are those patients supposed to be registered? Is this a good idea to use the ORPHAcodes of the diseases and add a note in a separate field to clarify that in practice they were diagnosed as carriers? Please note that a closely related question to this issue is currently waiting to be answered (GitHub#129).

Thanks for your help on this matter. Kind regards,

Annabelle (Orphanet Belgium)

**Comment by Orphabe** [comment]
Dear colleagues,

Kind reminder regarding this issue. The Belgian NeuroMuscular Disease Registry manager would like to know if Orphanet could give its advice on the way to deal with "asymptomatic form of muscular dystrophy of Duchenne and Becker in female carriers". 

Thank you for the support, kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 
As mentioned in the last Nomenclature/Coding Open Session this is an ongoing request, a text is currently validated by Orphanet Scientific and medical committee, and a dedicated wiki post will be made. I will publish it as soon as I receive it !(hopefully this week)

Thank you for your patience, 
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Here the rational and kind of answer that can be use to send out to coders/manager of registry etc

**In general, ORPHAcodes describe the Rare Diseases clinical diagnosis and not phenotypic abnormalities or genetic variations to describe individual patients.
In this sense, it is improper to use ORPHAcodes to code healthy subjects or asymptomatic carriers in order to track their genetic diagnosis (i.e. carrier of a genetic mutation) and potentially related information in the EHR.**
 
Regarding your specific example 1. Asymptomatic form of muscular dystrophy of Duchenne and Becker in female carriers
Orphanet has included ORPHAcodes related to 'Symptomatic form of' certain diseases such as **'Symptomatic form of muscular dystrophy of Duchenne and Becker in female carriers' (ORPHA:206546)** but there is no ORPHAcode for asymptomatic DMD/BMD female mutation carriers. 
It is important to rely and use the ORPHAcode based on its main name 'Symptomatic form...' and/or the definition of the clinical entity.

I will come back to you soon as possible about 2. Lynch Syndrome and FAP mutation carrier; Briefly those are cancer predisposition syndromes with a clinical presentation. Individual with no clinical presentation should not be coded using these ORPHAcodes (cf general arguement, 'it is improper to use ORPHAcodes to code healthy subjects or asymptomatic carriers in order to track their genetic diagnosis'
Please note I will add here the link to the Wiki page with the standard justification (and exemples to illustrate) as soon as will upload it.

Hope this helps, 
Marie-Cécile

**Comment by Orphabe** [comment]
Dear Marie-Cécile,

Thank you very much for your answer.

Regarding the DMD/BMD healthy female carriers, we understand that no ORPHAcode can be used, since these people are not suffering from a rare disease. But how can managers of registries make these people visible in RD registries? Then using only codes that are not specific for RDs (with an additional comment if relevant)? Or do you consider these people should not be registered in registries focused on rare diseases ? 

Thanks, kind regards,

Kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
please see my edited post above and the last bold part mentioning the use of dedicated field and/or others standard genetic annotations

**Comment by Orphabe** [comment]
Perfect, thank you. I will get back to the expert with this explanation.

Thanks again, kind regards,

Annabelle

**Comment by MCecile-US14** [comment]
Please for future references see the new Wiki post about this topic (same answer provided with other examples) https://github.com/OD4RD/Main-Help-Desk/wiki/3.-Coding-Recommendations#coding-healthy-subjects-or-asymptomatic-carriers
