### ISSUE TITLE
Inactive codes in diff file / tab "newly included Orpha codes"?

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#158]
Hi,
when implementing the coding list of 2023, we noticed that the tab "newly included Orpha codes" in the nomenclature diff file contains 2 inactive codes, one is a group of disorders, and one is a disorder (ORPHA:642737 OBSOLETE: Spondyloepimetaphyseal dysplasia with severe short stature).
Is this on purpose (if so, why is an inactive code newly included or vice versa?), or is it a mistake? 

My problem now is that when comparing our modified nomenclature file of 2023 (the big nomenclature file, filtered for active codes, diseases, and subtypes) to the one from 2022, we have 138 new entries; this would be in accordance with the numbers from the diff file, which lists 114 new disorders plus 24 new subtypes.
However, as mentioned above, one of the 114 new disorders is inactive, and it does, accordingly, not show up in our coding list. 

So I am wondering where we found the ominous 114th new disorder, and if the diff file is correct, or if maybe an active new disorder was erroneously replaced by ORPHA:642737.

thxx
Ursula

**Comment by MCecile-US14** [comment]
Dear @uunter98, 

Indeed, ORPHA6:42737 'OBSOLETE: Spondyloepimetaphyseal dysplasia with severe short stature' is an entity that was erroneously created in 2023 and inactivated subsequently also in 2023. As we found out it was a clinical entity already represented by ORPHA:370015 - Spondyloepimetaphyseal dysplasia, Isidor-Toutain type (the target code). 
As a consequence it is normal that it does not appear in the newly inactivated ORPHAcodes list (as it was not even existing in 2022 so the number is not found nor comparable).

We assume it is the same situation for the Group of Disorder ORPHA:642013 OBSOLETE 'Adrenal Cushing syndrome due to isolated adrenocortical benign tumor' (targeted to ORPHA:647758 'Adrenal Cushing syndrome) but not so critical as it is a group (so not useful for coding purposes).
This taken into account, the diff file 2023 is fully correct.

Is this clarifying your issue? If not completely could you clarify your last question?

Thank you and sorry for the inconvenience
Marie-Cécile

**Comment by uunter98** [comment]
Hi Marie-Cecile,
thank you so much for this valuable info!! 
xx
