### ISSUE TITLE
Laryngeal dystonia 

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#159]
Hi!  We have a NORD report about this condition buy I noticed that it is obsoleted in Orphanet.  I could not find the history behind the decision and would like to know more about it if possible.

Thank you!  Gioconda Alyea

**Comment by galyea123** [comment]
Thank you very much for your detailed response!  Best! Gioconda

**Comment by galyea123** [comment]
Spasmodic dystonia, better known as "laryngeal dystonia" was obsoleted in Orphanet (I sent a ticket before to Orphanet to know the reasons for obsoleting it and it was explained that it was obsoleted in 2004 after an expert review who stated that "the pure focal forms like laryngeal dystonias are not diseases but clinical manifestations occurring mostly alone or simultaneously in hereditary dystonias". Orphanet decided to keep only the genetic forms under ORPHA1866 (Focal, segmental or multifocal dystonia). https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=1866). However, after a more detailed review I think that this condition is still considered as a disease in several sources and I wanted to know if it will be possible to review new evidence as the decision was made back in 2004.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8205448/ (I found this one very helpful)
https://www.nidcd.nih.gov/health/spasmodic-dysphonia (this is from the National Institute of Health)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5536965/
https://aao-hnsfjournals.onlinelibrary.wiley.com/doi/10.1177/0194599817728521
https://www.researchgate.net/publication/343898191_The_prevalence_and_clinical_features_of_spasmodic_dysphonia_A_review_of_epidemiological_surveys_conducted_in_Japan
https://emedicine.medscape.com/article/864079-overview#a7
https://www.aans.org/en/Patients/Neurosurgical-Conditions-and-Treatments/Dystonia
https://dystonia-foundation.org/what-is-dystonia/types-dystonia/spasmodic-dysphonia/

Thank you! Gioconda Alyea

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Coming back to this request, we discussed it during Orphanet disease meeting and first, my apologies when I replied the first time looking back in our archive the decision for inactivation was made in 2014 (not in 2004) based on approuval from an italian expert of Dystonias group of disorders for the reasons mentioned above. Several focal dystonias ORPHAcodes were inactivated at the same time targeted to the Group ORPHA:1866 on purpose (keeping only the genetics form of dystonias) based on expert's comment. 
Orphanet aims to be a sustainable nomenclature so eventually, it has been 10 years since so we will reevaluate this group and the decision, but this is rather a large revision (especially if final decision is to "undo" what has been previously validated) to evaluate the representation of dystonias and how experts of the fiels feel about it. This goes in our long term line group of revisions conducted with European Reference Network RND experts planned after prioritized groups in 2025.
We will update you if/when changed are made about this.
For this kind of requests you can follow up Orphanet ongoing and planned collaborations for revision at this link https://github.com/OD4RD/Main-Help-Desk/wiki/8.-Orphanet%E2%80%90ERN-collaborations

Thank you for your valuable input, 
Kind Regards, 
Marie-Cécile
