### ISSUE TITLE
Early-onset immune dysregulation due to DOCK11 deficiency

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#163]
Dear all,

We would like to inform you of the comments of an expert on the following diseases, included in the created diseases names file from December 2023 received on 30Jan24. 

PatId 31951
Early-onset autoimmune disorder due to DOCK11 partial deficiency (Pat)
Early-onset autoimmune disorder related to dedicator of cytokinesis 11 protei (Syn)

PatId 31952
Early-onset immune dysregulation due to DOCK11 complete deficiency (Pat)
Early-onset immune dysregulation due to dedicator of cytokinesis 11 protein complete deficiency (Syn)

They were described by a team in the Sant Joan de Deu Hospital, in Barcelona, and one of the experts happened to be a member of our Scientific Committee, so we asked him to validate our translation into Spanish. He agreed with the way we translated but not with the English names. Here you have his comments for your consideration:

- These entities are best described as “dysregulation” instead of “disorder”
- In any case, no difference should be made between the “partial” and the “complete” forms, in the sense that the first is referred to as “disorder” and the second as “dysregulation”
- In his opinion, the Syn is unnecessary and can create confusion. Once the definition/summary is produced,  it can be explained what the DOCK11 acronym stands for. 

Kind regards, 

María Elena

**Comment by Orphanet-EmilieGaillard** [comment]
Dear @Orphanet-ES 

We have modified the main name of ORPHA:658946 (PatID 31951) in accordance with the expert’s advice and we thank him for his valuable contribution :

ORPHA:658946 Early-onset immune dysregulation with autoimmunity due to DOCK11 partial deficiency (Main name)

Regarding the synonym, as you may know it is a general rule in Orphanet nomenclature that whenever an acronym is used in the main name of an entity, its developed form shall be provided in a synonym in order to avoid any ambiguity. This rule also applies to the acronyms used as names of genes or proteins, when included in the disease name.
You can find additional information regarding the use of acronyms in Orphanet nomenclature in the ‘Procedural document for Rare diseases nomenclature in English’ :
https://www.orpha.net/orphacom/cahiers/docs/GB/eproc_Disease_naming_rules_in_English_PR_R1_Nom_01.pdf

Kind regards,
Emilie

**Comment by Orphanet-ES** [comment]
Dear Emilie,

Thank you for taking into account the expert's comments.
We will correct the name once the file is injected.

I was almost sure that the development of acronyms was an Orphanet rule, but I preferred to pass on the expert's comment just in case.

Kind regards, 

María Elena
