### ISSUE TITLE
Is pulmonary hypertension due to left heart disease a RD?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#165]
Dear all,

A Belgian expert working in an "Expert centre for pulmonary hypertension" belonging to ERN-LUNG asked us to register the clinical trials she is participating. Among them, there is the following trial: "CADENCE: A Phase 2, Double-blind, Randomized, Placebo-controlled Study to Evaluate the Effects of Sotatercept Versus Placebo for the Treatment of Combined Postcapillary and Precapillary Pulmonary Hypertension (Cpc-PH) Due to Heart Failure With Preserved Ejection Fraction (HFpEF)".

Link: https://clinicaltrials.gov/study/NCT04945460 

The targeted disease is "Combined Postcapillary and Precapillary Pulmonary Hypertension (Cpc-PH) due to Heart Failure with Preserved Ejection Fraction (HFpEF)" (Pulmonary hypertension WHO group 2: Pulmonary hypertension due to left heart disease, ICD-10-CM code I27.22). I am not convinced this is a RD since it is the most common complication of left heart disease resulting from a wide range of cardiac disorders. However I could not find precise data on prevalence.

Could you please check whether this disease should be considered rare or not based on the European definition?

Thank you, kind regards,

Annabelle (Orphanet Belgium)

**Comment by moi-epiUS14** [comment]
Hello all, 

In summary, PH due to left heart failure is NOT rare. 

Here is the quote from PMID: 35983183 "he prevalence and survival of pulmonary hypertension due to left heart failure: A retrospective analysis of a multicenter prospective cohort study" : 

"Pulmonary hypertension (PH) has become an increasingly common global health issue. It is estimated having the prevalence of about 1% of the global population increases up to 10% in individuals older than 65 years (1). The clinical classification of PH is categorized into five groups, PH due to left heart failure (PH-LHF) is categorized as group 2, and is defined as post-capillary PH [mean pulmonary arterial pressure (mPAP) ≥ 25 mmHg and pulmonary arterial wedge pressure (PAWP) > 15 mmHg] (2). The overall incidence of left heart failure (LHF) is increasing due to the rapid global rise in the number of people older than 65 years, LHF is becoming a leading cause of PH, affecting around 5% of individuals aged 65 years or older (1, 3, 4).

Pulmonary hypertension due to left heart failure is a frequent co-morbidity of left ventricular diastolic dysfunction heart failure with preserved ejection fraction (HFpEF) or heart failure with reduced ejection fraction (HFrEF), the prevalence reported in previous studies ranges from 40 to 75% for PH-HFrEF and from 36 to 83% for PH-HFpEF (1, 5). However, this prevalence is derived from a non-uniform application of the gold diagnostic standard (RHC). "

Best, 
M

**Comment by Orphabe** [comment]
Dear Moi,

Thank you very much for your feedback.

Kind regards,

Annabelle (Orphanet Belgium)
