### ISSUE TITLE
X-linked intellectual disability, Turner type

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#168]
@Hi!  I see that this term was excluded and moved to non specific intellectual disability.  Do you know the reason for this?  There are currently a number of sources for this condition, many with the name "HUWE1-related neurodevelopmental disorder" or "HUWE1-related disorder" or "HUWE1-related intellectual disability". 
https://rarechromo.org/media/singlegeneinfo/Single%20Gene%20Disorder%20Guides/HUWE1%20related%20ID%20QFN.pdf
https://www.nature.com/articles/s41431-017-0038-6 
https://www.huwe1.org/what-is-huwe1 
https://pubmed.ncbi.nlm.nih.gov/38021253/ 
https://www.huwe1.org/research
HUWE1 gene variants were found in people affected with several other similar X-linked disorders, including Juberg-Marsidi syndrome and Brooks-Wisniewski-Brown syndrome, as well as nonspecific syndromic X-linked neurologic disorders with impaired intellectual development and additional features, thus indicating that all these conditions are part of the same disorder.
Thank you!  Gioconda

**Comment by MCecile-US14** [comment]
Dear @Mickael-Orphanet, 
Can you please look into the reason why this entity was depreciated to ORPHA:528084?
Thank you, 
Kind regards, 
Marie-Cécile

**Comment by galyea123** [comment]
Hi Mickael: Thank you very much for your response. I understand the reasons under your decision, however, the variants in HUWE1 [are being currently researched more actively](https://www.huwe1.org/data-collection),  and according to the same source from Moortgat and to others, people affected with HUWE1 typically present with moderate to profound ID, short stature, severe speech difficulties and nonspecific but "recurrent" dysmorphic facial features such as deep set eyes and a broad nasal tip. 
Best, Gioconda

**Comment by Mickael-Orphanet** [comment]
Dear @galyea123, 
Based on current literature and expert advice, Orphanet medical and scientific committee has not validated the activation of "X-linked intellectual disability, Turner type" because the available new literature and the expert advice statement show that there is not a clear homogeneous phenotype for the HUWE1 patients. The clinical signs are too broad. However the genes HUWE1 is linked to "Non-specific syndromic intellectual disability" ORPHA:528084. 

Best regards, 
Mickaël
