### ISSUE TITLE
Why do some diseases "disappear" from Orphanet? What happens to activities assigned to those diseases? 

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#17]
In some cases, a disease is inactivated and the related activities deleted.
Because the reason of the inactivation is not explained anywhere, affected experts don't understand these changes.
Furthermore, some diseases that are on the borderline of the rare disease definition become active again, creating even more confusion.

**Comment by Marlies99** [comment]
Hi 

I know the problem as well. The Orphanet database is very dynamic. Due to new findings (research, new diseases, new epidemiological figures, etc.), codes can become inactive or active again. They can also be moved in the classification (included into other orphacodes) or excluded from it. There is a description file on orphadata that explains all the variants (deprecated entity, obsolete entity and non rare in Europe):
https://www.orphadata.com/docs/ORPHAnomenclaturexmlcontent.pdf
We therefore work with the Orphadata Nomenclature pack, which is updated annually in July. This makes it possible to track the changes.

PS: Orphanet's data visualiser can also be used to display non-rare codes. this is sometimes helpful. https://dataviz.orphacode.org/

Cheers
Marlies

**Comment by Orphanet-ES** [comment]
Hi Marlies,

Thanks for the explanation.
The problem is that there is no document that compiles all the changes over time, and they can only be seen from year to year in the the description file on orphadata. I think it would be very interesting to also have that cumulative information available.

Cheers, 
María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES , dear @Marlies99, 

Thank you for rising up this important topic. 
Indeed, Orphanet entities can be inactived for different and justified reasons (Obsolescence, deprecation or non rare) and associated data are then unlinked from the entity since they are considered out of the Rare Diseases scope.

Unfortunately, Orphanet will not provide detailed list of inactivated entities each year. To overcome this need we suggest to work with different files that can be used independantly or in combination:

- Information Scientists (IS) could go through the _CR total RM_ file they can access on ONW [CR total RM](https://network.orphanet.org/disease-meeting-total-report-files/) to find detailed information about the reason(s) for inactivation and then transmit specific information to expert center (or user, patient organisation, registry...) 

- Anyone can extract _Nomenclature Pack_ file and use excel filters to track changes over time and create a 'differential file' upon request .

- IS can also extract _PatAls_ file from Plator tool and use Excel filters, for which a recent training has been provided IS tools for Orphanet  [IS tools for Orphanet](https://network.orphanet.org/training-sessions-2023/).

I will add a dedicated Wiki post about inactivated entities and how to track changes
Kind regards, 
Marie-Cécile
