### ISSUE TITLE
Mapping ORPHAcodes-SNOMED CT: why only exact mappings?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#175]
Dear Julie, dear all,

I received this question from a registry manager: why is the Orphanet-SNOMED CT collaboration only aims to align **EXACT** concepts? 
Why not working also on NTBT and BTNT proximity relationships (as it is done with mappings between ORPHAcodes and ICD-10 and ICD-11)?

We heard that some hospitals in our country would like to complete the ORPHAcodes-SNOMED CT mapping files by searching for correspondence between SNOMED concepts and ORPHAcodes which do not have an exact equivalence relationship. Does it make sense?  In such a case, we would rather encourage the request for creation of a new entity in Orphanet.

Can you enlighten us on this?

Thank you, kind regards,

Annabelle (Orphanet Belgium)

**Comment by JTorphanet** [comment]
Dear @Orphababe,
 
Thank you for your message and for raising this point probably not clear for the Orphanet community.

We align ORPHAcodes with 8 international medical terminologies. Among them, only mappings with ICD-10 and ICD-11 are defined according to two relationships (proximity and specificity). Moreover, OMIM numbers are only mapped with a proximity relationship. Finally, we align ORPHAcodes with 5 terminologies as exact match: UMLS, MeSH, MedDRA, GARD and SNOMED-CT.

More precisely, we have two outstanding collaborations for the long term: ICD-11 and SNOMED-CT to improve the visibility of rare diseases in the European/international health systems.

The collaboration with SNOMED-CT is based on a licensed agreement and the interoperability rules have been defined together with the SNOMED-CT team at the beginning of the project. Indeed, ORPHAcodes are only aligned as exact match because it was agreed and formalized before starting the collaboration. This is because SNOMED-CT committed to include all RD terms (exact match to ORPHAcodes) that fitted the SNOMED-CT terminology rules.
This is of course possible because we closely work with the SNOMED-CT terminology team: we meet every month to compare our content, define a priority list to align, discuss about discrepancies and identify new entities to include in the SNOMED-CT.
Orphanet is the only terminology producing a rare disease nomenclature, so SNOMED-CT is basing their RD inclusions on our updates. Therefore, by definition, there is always a delay between the creation of a new ORPHAcode and the mapping with a SNOMED ID due to a reviewing process and the production of a definition (that is necessary to create/align a SNOMED ID)
It will be counter-intuitive to use broader SNOMED ID to code patients as we try to incorporate as much as possible RDs into this terminology. When a new ORPHAcode is created, SNOMED-CT will review it and decide if they create a SNOMED ID with exactly the same concept or exclude this entity.

We have reached a 95% coverage at the disorder level and every year for the release, SNOMED-CT propose new concepts to facilitate the coding of patients affecting by a rare disease.

Do not hesitate to transmit us a list of disorders that you identified without a SNOMED ID and we can look into it. 
And, of course, if you need more precision, please, come back to us :) 

Best regards, 

Julie
