### ISSUE TITLE
Down syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#179]
Hi!  I see that Orphanet maintains a page for DS, where it states that prevalence varies from 1/400 to 1/3000 live births". This is interesting, as a disease that was not rare may change the status due to the reduction in the population prevalence of Down syndrome because of selective terminations. We have not included DS in our NORD RD list as there are over 400,000 people with DS in USA. 

Is this a condition you would like to review as I find that its prevalence in Europe as a whole does not meet the RD definition?

Thank you!  Look forward to your response! 

Gioconda Alyea

**Comment by moi-epiUS14** [comment]
Hello, 

Thank you for your inquiry. I took a look, and there are a few things I would like to highlight: 

1. "1/400 to 1/3000 live births" indicates prevalence at birth. This means a baby with DS is born every 300 to 4,000 live births in the European population. This does not directly translate into point prevalence, the measure Orphanet uses to determine a disease's true rarity. 

2. According to PMID: 33130823, the point prevalence of DS in Europe was 5.7 per 100,000 population in 2015. This is slightly over the threshold that we apply to determine the rarity of a disease (<5 per 100,000 general pop). However, since then, there have been a few articles from Europe that suggest a steady decline in the birth prevalence of babies with DS. This finding is important to understand the true prevalence of DS; it may not be at 5.7 per 100k, and could even be low enough to be rare. 

For the reasons I stated, Orphanet decided to keep DS in our rare diseases database until some new studies show otherwise.

I hope this is clear to you, and do let me know if you want me to further clarify. 

Best, 
Moi

**Comment by galyea123** [comment]
Hi Moi!  
Thank you for your message.  I understand the concept of live birth vs prevalence and the likehood of the decrease over time due to the selective termination (same phenomena is happening in US as well and we are lookin closely at the changes as it may meet the rare status criteria soon).  
The following seems to be very helpful (it includes the references; see also: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7940428/- the one you mentioned) and the report from the WHO (https://gateway.euro.who.int/en/indicators/hfa_603-7120-births-with-downs-syndrome-per-100-000-live-births/#id=19698) and have an interesting statistic depending on the specific countries.  
This is  a "borderline" condition regarding the rare status, i.e., as you mentioned, it is slightly above the threshold . 
Thank you! Gioconda
