### ISSUE TITLE
KCNMA1-linked channelopathy

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#186]
Hello,

We received a request from a Swiss coder concerning a patient with the diagnosis “KCNMA1 channelopathy (heterozygous "de novo" sequence deviation in the KCNMA1 gene)”.

Please consider the inclusion in the nomenclature of the entity “KCNMA1-linked channelopathy”.

PMID: 34224328, 31427379
“KCNMA1-linked channelopathy is a recently characterized neuromuscular disorder essentially defined by the presence of a mutation in the KCNMA1 gene, associated with various combinations of movement disorders, seizures, developmental delay, and intellectual disability”.

And here is the link to the KCNMA1 channelopathy international advocacy foundation, based in the USA: https://www.kciaf.org/

Thanks

**Comment by MCecile-US14** [comment]
Dear @Mickael-Orphanet, 

This could be part of entities your previously evaluated. Please check this request as well when you get the chance
Thank you, 
Kind Regards, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetSwitzerland , 

KCNMA1 seems to be responsible for the channelopathy "Generalized epilepsy-paroxysmal dyskinesia syndrome" ORPHA:79137.  

Otherwise we decided to create another entity linked to KCNMA1 called "Gingival fibromatosis-aortic root dilatation-facial dysmorphism-intellectual disability syndrome" ORPHA:664438 also called Liang-Wang syndrome (added as synonym) that will be display on the website next week. 

Best regards, 
Mickael
