### ISSUE TITLE
ORPHAcodes associated with ERN GENTURIS

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#187]
Dear all,

As part of the HCP-survey carried out for the OD4RD2 project, I received the following information from a Belgian medical coordinator for ERN GENTURIS:  

"The data for the monitoring indicators we send to GENTURIS are grouped per thematic group (cfr. Infra). Only the Thematic group 3 (HBOC) corresponds with an ORDO-code. The subgroups do all correspond with an ORDO-code, but currently we only send data per thematic group as detailed data per subgroups are too time-consuming to compile.

In the future we will also contribute to the ERN GENTURIS registry, which uses ORDO-codes.

** numbers can be assembled as follows per Thematic Group:									
- TG1: the 3 neurofibromatosis syndromes together (NF1, NF2 and Schwannomatosis; if feasible, also specify per syndrome.)							
- TG2: Lynch syndrome and polyposis together; if feasible, please specify per syndrome.									
- TG3: Hereditary Breast and Ovarian Cancer (HBOC; BRCA-genes and non-BRCA genes together; if feasible, also specify per syndrome.)					
- TG4: The other malignant genturis together (PTEN hamartoma tumour syndrome, Li-Fraumeni Syndrome, Birt-Hogg-Dubé Syndrome, Familial Malignant Melanoma, Constitutional Mismatch repair deficiency, Rhabdoid Tumour Predisposition Syndrome 2, CDH1 related Hereditary diffuse gastric cancer', Carney Complex, Hereditary Papillary Renal Cell Carcinoma, Ataxia-Telangiectasia, Bloom syndrome, Nevoid basal cell carcinoma syndrome / Gorlin syndrome, Werner Syndrome, Hereditary Leiomyomatosis and Renal Cell Cancer, Von Hippel –Lindau disease,  Fanconi anemia, Paraganglioma, Hereditary pheochromocytoma-paraganglioma; if feasible, also specify per syndrome.)"

I am a bit confused by this reply. Could you please help me to understand it better?

1) The expert talks about “ORDO-codes”. Can “ORDO-codes” (I suppose for “Orphanet Rare Disease ontology” (ORDO)) be considered synonymous with ORPHAcodes?

2) The RDs included in TG1, TG2 and TG4 of GENTURIS do have ORPHAcodes (e.g. Neurofibromatoses type 1 ORPHA636, Neurofibromatoses type 2 ORPHA637, Schwannomatoses ORPHA93921, Lynch syndrome 0RPHA144, etc.). If I understand the expert's answer correctly, he does not use them because it would take too much time and he only wants to use 1 code per TG. Do you understand his response the same way? In such a case, should we advice him to use ORPHAcodes related to groups of disorders (like ORPHA:634518 [Neurofibromatosis/schwannomatosis] for TG1)? I know we strongly encourage coding at the "disorder" level (or subgroup level) but in a case like this, how can we best react to promote the use of ORPHAcodes?

3) In the past, on the EC website dedicated to ERNs, I could find an Excel file with ORPHAcodes associated with each ERN (see attached). I can't find it anymore. Do you know about this very useful Excel file? Is this work still in progress and can we have access to a more recent version?

[specificcriteria_en_Version Apr 2023.xlsx](https://github.com/OD4RD/Main-Help-Desk/files/14569390/specificcriteria_en_Version.Apr.2023.xlsx)

Thank you for your support, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Annabelle,

Thank you for your message.

We would like to clarify that the term “ORDO-code” should not be used interchangeably with “ORPHAcode” as it is incorrect and misleading. An ORPHAcode is a unique numerical identifier for a rare entity, whereas ORDO refears to “Orphanet Rare Disease ontology”, which is a structured vocabulary for rare diseases capturing relationships between diseases, genes, and other relevant features. We encourage to promote the use the correct terminology, which is ORPHAcode.

We need more details to better understand the coding issue.

- Which are the ORPHAcodes that correspond to each TG? For instance, for TG1, are they using “Neurofibromatosis/schwannomatosis ORPHA:634518”? We strengthen to use of the specific codes existing for the disorders under this group instead of the ORPHAcode of the group of disorders. The same is recommended for TG2 and TG3: when coding with the ORPHAcode of the group of disorders they lose the granularity and specificity.

- Why the TG4 is so large? To what ORPHAcode corresponds? We would like to know the underlying logic of this TG (what are the commonalities of the patients, is the cancer predisposition?). With this information, we will be able to orientate the expert toward the most suitable coding system (maybe in that case the ORPHAcodes are not the best choice).

Finally, the list of the ORPHAcodes associated with each ERN is a deliverable of the OD4RD2 project. We will release the actualized version in the following months.

I hope this information is helpful. Anyway, to better understand your questions, we can propose you a short meeting in the few following weeks. We will send you an email soon.

Thank you very much.
Best regards,
Marta

**Comment by Orphabe** [comment]
Dear Marta,

Thank you for your message.

We understand that you need more details to better understand this coding issue. We believe, however, that the important questions you raise should be asked directly to the board of ERN GENTURIS, to know their recommendations on this matter. As you know, we (the Orphanet Belgium team) are not involved in the definition of thematic groups for any ERN.

Therefore, I am not sure that a meeting with me would be of any use on this subject.  I can of course forward your questions to our Belgian experts who are members of ERN GENTURIS to get their opinion, but I am not sure they can answer questions like "which are the ORPHAcodes that correspond to each TG? " or "why is the TG4  so large?". In my understanding, this is more the prerogative of the ERNs themselves.

Based on the Belgian expert's response (see the copy-paste in my previous message), I understand that he sends ERN GENTURIS information on the **number** of patients treated in his centre by thematic group (and therefore, that he does not currently use ORPHAcodes).

Please let me know if I can be of any help in this matter and if I have misinterpreted your answer.

Thank you, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Annabelle,
Thank you for your message.
All good then, what they asked for is the document related to the ORPHAcodes by ERN. The release is planned for 2024 as OD4RD2 deliverables.
In the future, I suggest inviting experts to contact me directly via email for questions about ERNs. Do not hesitate to share with experts the ERN coordiator contact.
Thank you and kind regards,
Marta
