### ISSUE TITLE
What is the benefit of using ORPHAcodes in addition to SNOMED-CT?

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#19]
What is the benefit of using ORPHAcodes in addition to SNOMED-CT?

**Comment by JTorphanet** [comment]
Dear @OrphanetDE, 

SNOMED-CT, as for “Systematized Nomenclature of Medecine Clinical Terms”, is a comprehensive, multilingual clinical healthcare terminology that enables the representation of clinical content in electronic health records and is currently in use in use in more than eighty countries. SNOMED CT is not a terminology dedicated to code rare diseases and it does not include any mention to specify if a given disease is rare or not. Moreover, rare diseases included in SNOMED-CT do not have a dedicated classification of rare diseases for data aggregation but are mixed together with non-rare diseases. Therefore, using only SNOMED CT to code rare patients will not allow to retrieve any specific rare disease data nor to make any specific statistical analysis on rare diseases. It is also important to mention that interoperability with other systems that don't use SNOMED-CT and registers of rare diseases (that use ORPHAcodes) is not granted just by using SNOMED-CT codification.
ORPHANET is the only existing medical terminology dedicated to Rare Diseases. Orphanet produces the Nomenclature of rare diseases following the evolution of knowledge in the research and clinical literature and by consulting experts of the domain. Rare disease inclusion and modification in the Orphanet Nomenclature is evaluated by Orphanet according to standardized procedures, working with international rare disease expert networks.
In a second time the information produced by Orphanet is transmitted to SNOMED CT as part of an ongoing collaboration. This proposed updated information is then evaluated by SNOMED CT according to their internal rules for inclusion. Because of the different inclusion criteria, a 100% equivalence between the two nomenclatures is not possible to achieve. Therefore, despite the high level of alignment between the two terminologies that consents an optimal level of interoperability, the entirety of rare disease is not represented in SNOMED CT.


At the moment, Orphanet is working on a document, that will be released in the following weeks, aimed at explaining in detail the importance of using ORPHAcodes to complement the SNOMED-CT codification.

Best, 

Julie
