### ISSUE TITLE
Creation of Paediatric acute respiratory distress syndrome (PARDS)

### ISSUE THREAD

**Issue by OrphanetDE** [OD4RD/Main-Help-Desk#193]
Dear all,

We received a request from a German coder concerning a patient with the diagnosis <Paediatric acute respiratory distress syndrome> (PARDS).  

Please consider the inclusion in the nomenclature of the entity <Paediatric acute respiratory distress syndrome>
PMID: 30361119, PMID: 36661438
Here you will find pediatric-specific definitions for acute respiratory distress syndrome and management as well recommendations/statements. 

thanks and kind regards,
Kathrin

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetDE,

Thank you for your message.
We will evaluate the request in the coming months and inform you of the decision made following the medical and scientific committee meeting.

Best regards,
Marta

**Comment by OrphanetDE** [comment]
Dear Marta,

Thank you very much for your reply. According to literature, PARDS is defined as a disease with an age limit of <18 years. This excludes the perinatal period. You can find the relevant literature at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10880453/ Could you please check this again. 

Many thanks in advance for your efforts. 

All the best, 
Orphanet Team Germany

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetDE,

Thank you for the provided reference.  We will consider your request and get back to you with a decision in the coming weeks.

Best regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetDE,

Based on current literature, Orphanet medical and scientific committee has validated the creation of ‘Pediatric acute respiratory distress syndrome, ORPHA: 685082’. The code will be available from next week on the Orphanet website.

Since PARDS (ORPHA: 685082) includes patients from 0 to 18 years, 'Infant acute respiratory distress syndrome, ORPHA:70587' is now considered as part of PARDS diagnosis, and so, it has been deprecated and moved to 'Pediatric acute respiratory distress syndrome, ORPHA: 685082'.

Kind regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Hello,

We reopen this issue because a Swiss coder has a question regarding the deprecation of ORPHA:70587 (Infant acute respiratory distress syndrome) to ORPHA:685082 (Pediatric acute respiratory distress syndrome - PARDS).

Specifically, she is unsure if the new code can still be used for premature infants with respiratory distress syndrome caused by developmental insufficiency of surfactant production.

The definition of ORPHA:70587 previously described it as “a lung disorder that affects premature infants caused by developmental insufficiency of surfactant production”. However, the new code (ORPHA:685082) explicitly excludes perinatal-related lung diseases (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10880453/). She is uncertain whether this exclusion also applies to “premature infants with respiratory distress syndrome caused by developmental insufficiency of surfactant production”.

Thank you

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetSwitzerland,

Thank you for your message. 

PARDS includes patients from 0 to 18 years of age, so neonates (patients from birth to the 4th week of life) are included. 

In the following months we will evaluate whether it is appropriate to use this ORPHAcode for premature infants with respiratory distress syndrome according to medical literature.
I will confirm its usage or inform you about the creation of a specific ORPHAcode for these cases, if necessary.

Kind regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Thank you for your reply. We await the decision regarding the use this ORPHAcode for premature infants with respiratory distress syndrome.

**Comment by OrphanetDE** [comment]
Dear Marta,

thanks for the feedback! I was fine with coding proposed, just opened the issue as the answer to Orphanet Switzerland is still reamaining..  kind regards, Kathrin

**Comment by Orphanet-MartaFructuoso** [comment]
Thank you @OrphanetDE for your comment. 
@OrphanetDE, @OrphanetSwitzerland I hope that my last post will help you to choose the most suitable ORPHAcode.
On the contrary, feel free to reopen the ticket for further discussion or additional information.

Best regards,
Marta

**Comment by OrphanetDE** [comment]
Dear Marta,
thanks a lot for clarification. Maybe you should consider to remove the synonyms "Hyaline membrane disease" and "Neonatal RDS" from ORPHAcode 217563, because they might also fit to the new PARDS (ORPHAcode 685082).
Kind regards,
your Orphanet team Germany

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetDE,

Thank you for your message.

Can you please provide some references? 
According to the ones consulted, the synonyms seem quite unique for the ORPHA:217563 since they have been historically applied to neonates. Here some of them:

- https://www.childrenshospital.org/conditions/infant-respiratory-distress-syndrome-hyaline-membrane-disease
- https://www.ncbi.nlm.nih.gov/books/NBK560779/
- DOI: 10.7363/030255
- DOI:10.7363/030263: (The term “hyaline membrane disease” refers to the histological aspect of the most frequent pulmonary pathology in preterm newborn patients.)

Best regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Hello,

We are reopening this issue in order to follow up from Switzerland, as the situation for the coders is still confusing.

Do you know if the changes to the main term and disease definition will be implemented soon?
(Your message from last September mentioned: “_Thanks to your comment, we have identified some improvements that need to be made to ORPHA:217563. The main term and disease definition will be updated soon. Specifically, we will show that neonatal RDS can occur also as a result of SP-C deficiency, and that the majority of patients are preterm infants_”).

At present, the situation remains confusing because the current definition for ORPHA:217563 still states:
“_A rare **genetic** interstitial lung disease characterized by progressive, life-threatening, refractory respiratory distress in **full-term neonates**_.”

This would be contradictory for instance with listing “Hyaline membrane disease” as a synonym since, as you pointed out, “_The term “hyaline membrane disease” refers to the histological aspect of the most frequent pulmonary pathology in preterm newborn patients_”.

Could you let us know when the update will be visible?

Thank you,

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetSwitzerland,

Thank you for your message. 
The action was planned but not yet applied due to high volumes. Thank you again for bringing this matter to our attention. We understand its relevance for coding purposes, and the corrected information will be visible from next week.

Best regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Hello Marta,

Thank you for updating the text. 

There are still questions regarding the term “genetic” at the beginning of the definition: “A rare genetic interstitial lung disease characterized by…”. 

Should we understand that non-genetic cases in preterm infants should not be coded, as they are not rare? This is the interpretation of some of the hospitals involved in the discussion: They do not code these patients because they are frequent.

If the entity is meant to refer only to genetic forms, would the sentence “It is primarily observed in preterm infants” still be accurate?

Kind regards,
Martin

**Comment by Orphanet-MartaFructuoso** [comment]
Dear Martin,

Thanks for reporting the problem of coding. We will come to you with a clearer answer in the following weeks. 
Kind regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Kind reminder

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetSwitzerland,

Thank you for the reminder!  I will come to you as soon as the adequacy of the perimeter has been confirmed and the changes have been made, if applicable. If so, please bear in mind the internal monthly validation cycles for the delay in my feedback.

Sorry for the inconvenience and thank you for your patience.

Best,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @OrphanetSwitzerland,
  
I apologize for the delay in my response, but I am now able to update you on this issue.

First, regarding the name of the ORPHA:217563, Neonatal acute respiratory distress syndrome, the medical and scientific committee has validated the name change, and the clinical entity will be named as it used to, with the specific mention of the protein B (Neonatal acute respiratory distress due to SP-B deficiency), and remove the linked gene ABCA3 since there is an specific ORPHAcode for this. 
Indeed, the change of the main name has been a mistake: it can lead to the misunderstanding of a more general diagnosis than the perimeter is supposed to cover (only the genetic forms associated with mutations in this gene).
Actually, we do have specific codes for other mutations:
ORPHA:440427
ORPHA:440402
ORPHA:440392

Second, we decided to seek expert advice on the potential need or adequacy of creating an ORPHA code for Neonatal acute respiratory distress syndrome, not only the genetic forms already present in the nomenclature. We will be working with ERN LUNG experts this year, and it will be the perfect occasion to have their feedback on this matter. I will keep you updated of course !

Again, thank you very much for your help and patience.

Best regards,
Marta

**Comment by OrphanetSwitzerland** [comment]
Ok, thank you Marta!
