### ISSUE TITLE
Request to revise the aceruloplasminemia classification

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#195]
Dear all,

A colleague has sent us a request to make a change to the classification of Aceruloplasminemia, ORPHA 48818. 

Here you have the text of the message:

“Aceruloplasminemia is due to an inherited deficiency of ceruloplasmin, which is an enzyme involved in copper metabolism and transport.

Aceruloplasminemia is an inherited disorder caused by genetic defects in the ceruloplasmin gene. The disorder is characterized by diabetes, retinal degeneration, iron-refractory anemia (low plasma iron concentrations, high plasma ferritin levels, significant iron accumulation in the basal ganglia), development of progressive neurological symptoms, including extrapyramidal symptoms, ataxia and dementia (due to "neurodegeneration with iron accumulation").

Ceruloplasmin is a multicopper oxidase with ferroxidative activity that mediates the ferrous iron oxidation and subsequent transfer to extracellular transferrin. As a copper-dependent  ferroxidase, the lack of ceruloplasmin is the root cause of this disorder and its manifestations. That is why the anemia is iron-refractory, as it is a consequence of the alteration of copper-dependent enzymatic chains, among which some are secondarily involved in iron oxidation.

Therefore, I suggest you consider including this disorder within ORPHA:309839 Disorder of copper metabolism group, along with MEDNIK, MENKES, and other. Anemia and iron accumulation are secondary (correspondence to ICD10-Mortality, E83.0). Also, evaluate if it should remain within the ORPHA 98360 group (Constitutional anemia due to iron metabolism disorder).

In addition, If the mild anemia described in aceruloplasminemia patients is iron-deficient, the ICD10-Mortality would exclude it from E83.1
E83.1 Disorders of iron metabolism
It excludes:
-	iron deficiency anemia (D50.-)
-	sideroblastic anemia (D64.0-D64.3)"

Thank you for your consideration and kind regards,

María Elena

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES, 

In the case of Aceruloplasminemia the problem is the iron cycle with ceruloplasmin playing a role in the iron cycle. Furthermore in the classification of IEMbase [https://www.iembase.com/disorder/872](url) is part of the iron metabolism. 

We will keep aceruloplasminemia in the iron metabolism classification. 

Here are some PMID 12055353 (2022)
"Ceruloplasmin plays a critical role in the iron cycle by establishing a rate of iron oxidation sufficient for iron release from the reticuloendothelial system"
"Although ceruloplasmin has been recognized as the major copper-containing protein in plasma for more than half a century, the past few years have witnessed considerable progress in our understanding of the biological function of this protein. Given the critical role of iron in early cognitive development as well as recent studies that implicate copper in a number of neurodegenerative diseases, the recognition that ceruloplasmin plays an essential role in brain iron metabolism and neuronal survival provides much needed molecular insight into the mechanisms of iron homeostasis within the central nervous system."

PMID: 33376659 (2020)
“Ceruloplasmin is a ferroxidase that can bind up to six atoms of copper. It plays a vital role in iron homeostasis, especially in the brain where it performs a neuroprotective function by safely oxidizing ferrous iron without the generation of free radicals, promoting iron efflux and reducing oxidative damage. Although ceruloplasmin binds up to 95% of the body’s total copper in the plasma and is needed for copper to maintain its three-dimensional structure and enzymatic activity, it is not involved in copper metabolism.

Best regards, 
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet , 

Thanks for your answer.

I will pass your response on to the expert and if he has any comments on this, I will come back to the topic.

Kind regards, 

María Elena
