### ISSUE TITLE
Vertebral artery dissection

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#200]
Hi Marie-Cécile! 
We received a message from a patient who is a stroke  asking to add this condition listed at NORD.  Currently it is not listed in NORD and it is not in Orphanet. Orphanet does list familial cervical artery dissection  (note that cervical artery dissection occurs when there's a tear in either a carotid or vertebral artery).  It is, in fact, a rare condition.
Please let me know your thoughts.  

Some useful sources include: 

https://www.ncbi.nlm.nih.gov/books/NBK441827/ 
https://emedicine.medscape.com/article/761451-overview#a1
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2588305/
https://www.cureus.com/articles/51091-vertebral-artery-dissection-a-pain-in-the-neck#!/

Thank you for your consideration,

Best,

Gioconda Alyea

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @galyea123,
Thank you for your message.
We will evaluate the creation of the ORPHAcode and inform you of the decision following the Medical and Scientific Committee meeting in September 2024.
Best regards,
Marta

**Comment by Orphanet-MartaFructuoso** [comment]
Dear @galyea123,

Orphanet medical and scientific committee has validated the creation of ‘Isolated spontaneous vertebral artery dissection’, ORPHA: 689001. The entity covers both carotid and vertebral artery dissections. Major clinical features are: head and neck pain, transient ischemic attack or stroke and partial Horner’s syndrome, although some patients remain asymptomatic. 

During the revision process, 'Familial cervical artery dissection, ORPHA:36382' has been obsoleted because both the familiar and non-familiar cases share multiple comorbidities including genetic factors. Please, refer to 'Isolated spontaneous vertebral artery dissection, OPRHA:689001' instead of 'Familial cervical artery dissection, ORPHA:36382'.

Kind regards,
Marta
