### ISSUE TITLE
Could preferred parent be visible in Dataviz?

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#201]
Hello,

I think this question has been answered before but I don't remember and it has come up again in our team.
Would it be possible to somehow make it visible on Dataviz which classification is the parent in the linearization? It is a bit complicated to open the XML file in the nomenclature file to find the answer :)

Kind regards,
Lene

**Comment by MCecile-US14** [comment]
Dear @LeneMartinsen, 

Indeed this might have been discussed before and I am not sure of which reason has been given. For now unfortunately due to the lack of resource to manage and upgrade tools developed by Orphanet IT team such as DataViz, we are not in capacity to implement this infomation currently to DataViz.
Our suggestion either to use the XML file from the Nomenclature Pack as you said, alternatively you can also download the 'PatPrt' table file from Plator where you can recover the preferential parent (only accessible by Orphanet teams) .
Please see issue #36 about this and the Wiki page https://github.com/OD4RD/Main-Help-Desk/wiki/2.-Orphanet-classification#how-to-find-the-preferential-parent-of-a-rare-disease-in-orphanet-classification

Hope this helps, 
Kind Regards
Marie-Cécile

**Comment by LeneMartinsen** [comment]
Dear @MCecile-US14,
Thank you very much. We totally understand.
I have made a simplified version of the XML file for our medical advisors so if they want to see the preferential parent they can use this file.

Kind regards,
Lene
