### ISSUE TITLE
adrenal medullary hyperplasia

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#202]
Hi 
I am trying to assign this message to e @MCecile-US14  but the function is not working:

Dear Marie-Cécile:

We received a message from an inquirer about adrenal medullary hyperplasia.  I was unable to find a prevalence for this condition but most of the literature points that it is in fact a rare condition which prevalence remains unknown  and I was wondering if Orphanet may consider adding it.  

The following references may be helpful: 

https://academic.oup.com/jcem/article/108/9/e885/7075217
https://academic.oup.com/jes/article/3/8/1518/5512655
https://www.sciencedirect.com/science/article/abs/pii/S0002962920302913
https://thekingsleyclinic.com/pheochromocytoma-explained-symptoms-diagnosis-treatment-self-care/

Thank you!

Best,

Gioconda Alyea

**Comment by Mickael-Orphanet** [comment]
Dear @galyea123, 
Based on current literature and experts advice, Orphanet medical and scientific committee has validated the creation of ‘Isolated adrenal medullary hyperplasia’, ORPHA:688649. rare adrenal disease characterized by a benign isolated lesion of the medulla of the adrenal gland that causes hypertension, sweating, palpitations, headache and anxiety. Excessive catecholamine excretion and abnormal uptake in the adrenal gland can be detected. Patients show an enlargement of the adrenal medulla. This disorder can affect one side of the medulla (unilateral) or both sided of the medulla (bilateral). This disorder is isolated because there is a possibility of adrenal medullary hyperplasia to be a precursor of pheochromocytoma. The prevalence is unknown but the rarity has been established.

Best regards, 
Mickael
