### ISSUE TITLE
Add Beck-Fahrner syndrome

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#206]
Hi M. Cecile!   I am requesting to add the condition "Beck-Fahrner syndrome".  Please see OMIM 618798 and also a GR: https://www.ncbi.nlm.nih.gov/books/NBK591837/  

Currently Orphanet does not list any particular disease for the TET3 gene but includes it under Non-specific syndromic intellectual disability.

 Thank you! Gioconda Alyea

**Comment by Mickael-Orphanet** [comment]
Dear @galyea123 , 

Based on current  literature, Orphanet medical and scientific committee has validated the creation of ‘Intellectual disability-facial dysmorphism-joint hypermobility-hearing loss syndrome’, ORPHA:684216. This Rare genetic disorder caused by gene variant of the TET3 gene. Clinical signs show developmental delay, intellectual disability, hearing loss and  musculoskeletal findings like joint hypermobility. This disorder is  within the spectrum of Mendelian disorders of the epigenetic machinery also called chromatinopathies. One third of patients show epilepsy . 

Please wait one week to see this entity in the Orphanet website. 

Best regards, 
Mickael
