### ISSUE TITLE
2q13 deletion syndrome

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#207]
Hello,

Please consider the inclusion in Orphanet of the entity 2q13 deletion syndrome. 

The request comes from a geneticist at the Geneva University Hospitals who wants to code a patient with this syndrome

References: 
PMID: 26236398
PMID: 34763108
https://rarechromo.org/media/information/Chromosome%20%202/2q13%20microdeletions%20FTNW.pdf

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 
Thank you for your request. 
Please note that due to the prioritized release of the Orphanet Nomenclature Pack 2024, this type of request for creation will be evaluated within 6 months delay (after summer). We will come back to you with a proper answer about this as soon as possible.
Thank you for your patience, 
Kind Regards
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Based on the medical and scientific litterature, Orphanet committee has validated the creation of '2q13 microdeletion syndrome' under ORPHA:684742. Major clinical features are: developmental delay, cardiac and urogenital malformations, and minor facial anomalies. Congenital heart defects (CHDs) are the most frequent malformations associated with del2q13. Please wait until next week to see it in the website.

Kind Regards,
Marie-Cécile
