### ISSUE TITLE
Synonyms for SATB2-associated syndrome ORPHA:576278 - PatId 28850

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#21]
Dear all,

A Spanish PO for this disease proposes adding some synonyms, such as those included in MedlinePlus:
https://medlineplus.gov/genetics/condition/satb2-associated-syndrome/#synonyms 

    2q32 deletion syndrome
    2q33.1 microdeletion syndrome
    Chromosome 2q32-q33 deletion syndrome
    Glass syndrome
    
Please, let me know if you agree and I will add the Spanish translation.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 
I am currently documenting your request and will come back soon with validated news. It seems @caterina-lucano-orphanet already consulted experts regarding synonyms and prefered terms attributions for ORPHA:576278 when the entity was created.
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

Here, the current classification and related informations on Orphanet:
*ORPHA:576278, SATB2-associated syndrome [disorder] has 2 etiological subtypes:
	-Syn: SAS
	-KW: Glass syndrome
		*ORPHA:251028, SATB2-associated syndrome due to a chromosomal rearrangement [subtype]
			-Syn: 2q33.1 microdeletion syndrome (old main name); Del(2)(q33.1); Monosomy 2q33.1
			-KW: Glass syndrome
		*ORPHA:576283, SATB2-associated syndrome due to a pathogenic variant [subtype]
			-Syn: SATB2-associated syndrome due to a point mutation
*ORPHA:251019, 2q32q33 microdeletion syndrome [disorder]
			-Syn: Del(2)(q32); Monosomy 2q32; Del(2)(q32q33); Monosomy2q32q33
			-KW: Glass syndrome
			
ORPHA:576278 has been created as a disorder and reviewed by clinical experts recently (2021) with creation of the 2 etiological subtypes in order to better represent all patients and distinctive phenotype/genotype correlations. For instance, patients presenting with a 2q32q33 microdeletion present SAS and others abnormalities that need specific care management, this is why we have kept ORPHA:251019, 2q32q33 microdeletion syndrome as a separate disorder entity. All the detailed information and the decision are written in the CRtotalRM file you can consult.

As you can see Glass syndrome is already keyword for ORPHA:576278, ORPHA:251028, ORPHA:251019 as it is not consider exact same syndrome perimeter it cannot be added as a synonym. Regarding other suggestions, there are already synonyms of one of the other entity mentionned and 2 entities cannot have the same synonym (only keyword).
Kind Regards,

**Comment by Orphanet-ES** [comment]
Dear Marie-Cécile,

Thanks for the explanation and sorry for not answering sooner.

Kind regards, 

María Elena
