### ISSUE TITLE
Specific ORPHA codes for the symptomatic form of the disease in female carriers

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#214]
Dear all,

A Spanish expert has questioned us about the need to create a specific code for the symptomatic form of a disease in female carriers. 
He considers that it is unnecessary and that assigning the ORPHA code of the disease would be sufficient.

I have searched for these specific codes and have only found the following:
ORPHA:177926 (Subtype of disorder) [Bleeding disorder in hemophilia A carriers](https://www.orpha.net/en/disease/detail/177926) 
ORPHA:177929 (Subtype of disorder) [Bleeding disorder in hemophilia B carriers](https://www.orpha.net/en/disease/detail/177929) 
ORPHA:280229 (Subtype of disorder) [Pelizaeus-Merzbacher disease in female carriers](https://www.orpha.net/en/disease/detail/280229) 
ORPHA:276630 (Disorder) [Symptomatic form of Coffin-Lowry syndrome in female carriers](https://www.orpha.net/en/disease/detail/276630) 
ORPHA:449291 (Disorder) [Symptomatic form of fragile X syndrome in female carriers](https://www.orpha.net/en/disease/detail/449291) 
ORPHA:206546 (Disorder) [Symptomatic form of muscular dystrophy of Duchenne and Becker in female carriers](https://www.orpha.net/en/disease/detail/206546) 
ORPHA:604680 (Disorder) [Symptomatic form of X-linked centronuclear myopathy in female carriers](https://www.orpha.net/en/disease/detail/604680)

Why these diseases? And why not others?

In the [Wiki](https://github.com/OD4RD/Main-Help-Desk/wiki/3.-Coding-Recommendations#coding-healthy-subjects-or-asymptomatic-carriers) you mention the use of these codes, but not the justification for their creation.

And for example, why is it necessary to differentiate these two diseases? Wouldn't it be enough to indicate the difference in the description of the disease?

ORPHA:604680 (Disorder) [Symptomatic form of X-linked centronuclear myopathy in female carriers](https://www.orpha.net/en/disease/detail/604680)
ORPHA:596 (Disorder) [X-linked centronuclear myopathy](https://www.orpha.net/en/disease/detail/596)

I have chosen these two diseases without really knowing them, but since they share the same name, it can lead to confusion when coding.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear @caterina-lucano-orphanet ,

As I mentioned in my previous message, could you explain why in some cases an ORPHA code has been created for asymptomatic carriers?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

When such diseases have been revised, it has been considered and consensually decided by the working group of experts that a single code was not enough to represent at best the clinical situation and possible outcomes/genetic counseling. Therefore, a dedicated code for female carriers was a need.
All disease examples are different but the rational remains the same:
For instance, in the case of Hemophilia ORPHA:98878 it can be important to distinguish a female symptomatic carrier from a child affected by hemophilia as it is not consider the same disease, as their clinical condition, follow up and care can be very different. See details in the summary recently reviewed with experts [ORPHA:98878](https://www.orpha.net/en/disease/detail/98878?name=98878&mode=orpha). Also this particular request came from the MHEMO network in order to better recognize women in hemophilia in epidemiological and clinical practices (similarly in the fragile X syndrome ORPHA:449291)

For more details about ORPHA:177926, OPRHA:177929 (p2590), ORPHA:604680 (p2591), ORPHA:449291 (p1479) and extensive explanations and references justifying the creations of these codes please refered to the Orphanet total disease meeting report in the respective mentionned pages.
Please note some disease prefered term in Orphanet are not specifying 'female' but the consideration is the same as written in the  short description (e.g. [ORPHA:85338](https://www.orpha.net/en/disease/detail/85338?name=85338&mode=orpha), historic)).

Hope this can help you to better reply to the spanish expert, 
Kind regards,
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 , 

Thanks for your answer.

I have forwarded your comment to the expert and, if he has anything to add, I would tell you.

Kind regards, 

María Elena
