### ISSUE TITLE
Add synonym to ORPHA:329224

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#217]
Dear all, 

A Spanish expert suggests adding the synonym Schuurs-Hoeijmakers syndrome to the ORPHA:329224 [Intellectual disability-craniofacial dysmorphism-cryptorchidism syndrome](https://www.orpha.net/en/disease/detail/329224). 

And these are the references that he has provided me:
https://omim.org/entry/615009
https://www.ncbi.nlm.nih.gov/medgen/767257
 https://pubmed.ncbi.nlm.nih.gov/34068396/
https://www.sciencedirect.com/science/article/abs/pii/S1059131123002558

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

I will check this soon and let you know if there is a change of nomenclature about this entity
Regarding the creation requests as discussed it will be evaluated after the summer
Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

Thank you for the suggestion. actually this entity has already been renamed using 'Schuurs-Hoeijmakers syndrome' few months ago as prefered term it is more relevant and very much use term in the literature than the Orphanet clinical name. 
It allowed us to detect a problem in the update of the database for this entity as the old name was still visible but not the new one.
Now everything should be correctly edited and visible next week on Orphanet website, FYI I also added the following synonyms: "PACS1-NDD", "PACS1-neurodevelopmental disorder"

Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear Marie-Cécile,

Thank you for handling this request so quickly.
I will also translate the new name and synonyms into Spanish.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear Marie-Cécile,

After checking the names assigned to this clinical entity, I have seen that you have not kept the previous one as a synonym: Intellectual disability-craniofacial dysmorphism-cryptorchidism syndrome. 
Is this a mistake? Wouldn't it be preferable to keep it for those who have been using it under that name?

Furthermore, the definition of the entity corresponds to that previous name.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Indeed the original prefered term was not kept as synonym as it was an "Orphanet clinical name" but not a known one. We do kept it as a synonym when it is representative and meaningful in the literature and "common knowledge", _eg: old names used by scientists and clinicians, patronymic names after princeps publications etc ..._
In this case all the literature and references are mentioning 'Schuurs-Hoeijmakers syndrome', I just found few references (laboratories) using the other name because they probably aggregated historically RD list from Orphanet.

I take not for the definition, this is indeed more problematic and FYI, we have an ongoing curation by the edition manager to avoid using the prefered term in the definition, this way changes of Nomenclature wont impact the definition.

Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 

Thanks for the clarification.
In that case I will delete that name in Spanish, which I saved in case it was a mistake.

Kind regards,

María Elena
