### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by OD4RDFIN** [OD4RD/Main-Help-Desk#22]
How to find tutorials on ORPHA codes?

**Comment by MCecile-US14** [comment]
You can find all resources and specific training information material produced by Orphanet for members of the network at [Training material and Orphanet resources](http://network.orphanet.org/training-calendar-2/). RD-CODE & EJP-RD: [Trainers toolkit](http://network.orphanet.org/ejprd_t14-1_trainers-toolkit/). From September 2022 nomenclature trainings (slideshows/scripts/recorded audios) + Quiz provided to National Hubs trainers are available on [OD4RD WP4 network](http://network.orphanet.org/od4rd-wp4-internal-page/).

Please use the Wiki page for official answers on this topic: https://github.com/OD4RD/Main-Help-Desk/wiki/Training,-Tutorial-&-Communication#where-to-find-tutorials-and-training-materials-on-orphacodes

PS: kind reminder @OD4RDFIN, do not forget to assign your issue to yourself directly when you are creating it so that you get all notifications and changes about it. Unlike Redminor here we can have multiple assignees at the same time.
