### ISSUE TITLE
ICD-10 assigned to the group Rare hemorrhagic disorder due to a qualitative platelet defect ORPHA:275736

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#233]
Dear all,

Regarding the group of disorders [Rare hemorrhagic disorder due to a qualitative platelet defect](https://www.orpha.net/en/disease/detail/275736) ORPHA:275736, a Spanish coder suggests to modified the assigned ICD-10.

Some of the disorders included in this group are linked to "[D69.8 Other specified haemorrhagic conditions](https://icd.who.int/browse10/2019/en#/D69.8)", but according to this expert it is too non-specific and should be linked to [D69.1 Qualitative platelet defects](https://icd.who.int/browse10/2019/en#/D69.1) like the other disorders in the group.

As an exception, ORPHA:52530 [Pseudo-von Willebrand disease](https://www.orpha.net/en/disease/detail/52530) could be linked to [D68.0 Von Willebrand disease](https://icd.who.int/browse10/2019/en#/D68.0).

Please, let me know what you think about it.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
[ORPHA 275736 Rare hemorrhagic disorder due to a qualitative platelet defect.xlsx](https://github.com/user-attachments/files/15883332/ORPHA.275736.Rare.hemorrhagic.disorder.due.to.a.qualitative.platelet.defect.xlsx)

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

This will be assigned and updated once the new Orphanet Nomenclature and alignments manager will arrive, in September.
Thank you for your patience, 
Kind Regards,

**Comment by MCecile-US14** [comment]
Dear @Seed-Orphanet,

Could you please check this request for ICD-10 alignment and let @Orphanet-ES know the final decision ?
(General reminder: the database is currently not accessible for any modifications, we cannot guarantee when the changes can be implemented)
Thank you,
Marie-Cécile

**Comment by Seed-Orphanet** [comment]
Dear @Orphanet-ES,
	
Thank you for your message and for sharing this suggestion.
We are currently doing a quality check of ICD-10 codes for a wide range of disorders, and the changes will be implemented progressively over the next few months. For this group, the alignments will be as follows:
	
ORPHA:420566 (Disorder) Bleeding disorder due to CalDAG-GEFI deficiency → D69.1
ORPHA:73271 (Disorder) Bleeding diathesis due to a collagen receptor defect → D69.1
ORPHA:52530 (Disorder) Pseudo-von Willebrand disease → D68.0
ORPHA:806 (Disorder) Scott syndrome → D69.8
ORPHA:36355 (Disorder) Bleeding disorder due to P2Y12 defect → D69.1
ORPHA:849 (Disorder) Glanzmann thrombasthenia → D69.1
ORPHA:477787 (Disorder) Cytosolic phospholipase-A2 alpha deficiency associated bleeding disorder → D69.1
	
Thank you for the valuable input, indeed many of the suggested codes align with our reviw!
Please feel free to reach out if you have any additional questions or input.
	
Kind regards,
Seed
