### ISSUE TITLE
Adding ORPHA codes

### ISSUE THREAD

**Issue by OD4RDFIN** [OD4RD/Main-Help-Desk#24]
Is adding an ORPHA code mostly done by clinical geneticists or paediatricians?

**Comment by MCecile-US14** [comment]
Propositions for the creation/modifications of ORPHAcodes are done documented according to the most up-to-date literature by Orphanet Information Scientists (IS) with a medical/scientific background. These suggestions are then validated on a monthly basis by the Orphanet medical and scientific Orphanet committee, composed by medical doctors and IS. When the committee is not able to make a clear decision based on the literature, specific medical experts of the field are consulted.

PS: kind reminder @OD4RDFIN, do not forget to assign your issue to yourself directly when you are creating it so that you get all notifications and changes about it. Unlike Redminor here we can have multiple assignees at the same time.
