### ISSUE TITLE
Coding of neonatal seizures

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#240]
Dear Marie-Cecile,
a coder from Austria is asking how/if it is possible to code neonatal seizures that are not familial or part of a syndrome. She says they are also rare. I wonder if it is considered only a sign in Orphanet, not a separate entity? Is it then correct that these patients are not considered RD patients? Or will it change in the frame of the alignment with the ILAE classification?
Thank you for your help!
Ursula

**Comment by MCecile-US14** [comment]
Dear @uunter98, 

Thank you for your request.
Looking at this quickly, it does not seems that isolated neonatal seizures are rare
- PMID:22000307 (2011) "Neonatal seizures are common, and often comprise the first clinical indicator of central nervous system dysfunction."; 
- [https://www.ncbi.nlm.nih.gov/books/NBK554535/](https://www.ncbi.nlm.nih.gov/books/NBK554535/) (2021) "Neonatal seizures are a commonly encountered neurologic condition in neonates"; 
- PMID:24524454 (2013) Seizures occur in approximately 1 to 5 per 1000 live births and are among the most common neurologic conditions".

According to literature, it can be considered as an individual diagnostic per se (primary or secondary to other condition), nonetheless not rare. If you find contradictory documentation and case reports stating it is rare please sent it us to support your request as usual.
Otherwise unfortunately this cannot be considered for creation, thus not particularly discussed with EpiCARE experts in the frame of ILAE classification.

Let me know if further clarification are needed, 
Kind Regards, 
Marie-Cécile

**Comment by uunter98** [comment]
Dear Marie-Cecile,
thank you so much for your quick response! 
Just for clarification: what number would it take to be considered rare in this case? Would it be incidence (instead of prevalence), and would it be the same as for rare cancers? And, most importantly, would we have to relate it to live births, or to the entire population?
thxx
Ursula

**Comment by uunter98** [comment]
Dear Marie-Cecile,
may I ask again how the epidemiology would be assessed in this case? I am not sure if this isn't a rare condition after all.
thank you!
U

**Comment by moi-epiUS14** [comment]
Hi Ursula, 

First of all, thank you for your patience :)

Without knowing if Neonatal seizure is associated with other diseases (e.g. infectious), it is difficult to say what measure of frequency to use. 
However, if it is observed within the first four weeks of life, it is safe to use birth prevalence (per # live births) as MC described above.

The rarity of a disease is, as you know, determined by the point prevalence of the disease, which is <50/100,000 population (<1/2000 population). 

Point prevalence can be calculated from birth prevalence if we know the life expectancy of the babies affected by the condition (in this case, neonatal seizure). Here is the formula: 

Point prevalence = birth prevalence x (life expectancy of the affected / life expectancy of the general population) 

The life expectancy of the general population is 81 years. Let's **hypothetically** say that those affected with neonatal seizures live up to 40.5 years. And that the birth prevalence is 3 per 1000 live births (PMIDs in previous comment by MC). 

100,000 / 1,000 = 100
100 x 3 = 300

Birth prevalence is 300 per 100,000 live births 

Point prevalence of neonatal seizure = 300 x (40.5 / 81) = 150 per 100,000 population 

This is over the threshold, therefore, neonatal seizure is not rare. 

**I want to reiterate that the life expectancy is made up, and it is not an actual figure.** 
I just wanted to show you how to calculate on your own :) 

I hope it is clear now!

Best, 
Moi

**Comment by MCecile-US14** [comment]
Dear @uunter98 
I hope the details helped and clarify your request
Kind regards,

**Comment by uunter98** [comment]
@moi-epiUS14 , thank you so much, this helps a lot!! xxUU
