### ISSUE TITLE
New ORPHAcodes already included in Nomenclature Pack 2023

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#241]
Dear all,

Regarding the ORPHAnomenclature_diff_en_2024, I have realized that some of the ORPHAcodes included in the "Newly included ORPHAcodes" were also included as new in the ORPHAnomenclature_diff_en_2023.

If I'm not mistaken, there are 166 ORPHAcodes that are not really "new" in 2024, which may cause confusion for our users.
See file attached.

In view of this error, I have checked if the same thing happened between 2023 and 2022, but the information was correct.

Kind regards, 

María Elena

[Newly included ORPHAcodes_REPEATED.xlsx](https://github.com/user-attachments/files/16159612/Newly.included.ORPHAcodes_REPEATED.xlsx)

**Comment by caterina-lucano-orphanet** [comment]
Thank you Maria Elena, we are looking into this issue! We will let you know asap.
Caterina

**Comment by caterina-lucano-orphanet** [comment]
Hello Maria Elena, for info we have corrected the file.
Indeed the tabs:
- Newly included ORPHAcodes
- Newly Inactive ORPHAcodes
- Classification level update
had the differential data of 2022 and 2023 cumulated instead of only 2023.
This was not a problem for all other tabs, that are correct.
The new file will be substituted in the released pack zip folders next week.

Kind regards,
Caterina

**Comment by Orphanet-ES** [comment]
Hello Caterina,

I'm glad to have been of help.

Kind regards, 

María Elena
