### ISSUE TITLE
Missing in Orphanet: OMIM # 619004 DEEAH Syndrome

### ISSUE THREAD

**Issue by uunter98** [OD4RD/Main-Help-Desk#244]
Hi Marie-Cecile,
an expert from Austria pointed out that OMIM # 619004 DEEAH Syndrome (linked to MADD gene) is missing in the database (the gene is only linked to Non-specific syndromic intellectual disability in Orphanet). I think it should be crreated.

thanks!
Ursula

**Comment by MCecile-US14** [comment]
Dear @uunter98, 

Thank you for your request. Could you please provide specific clinical context and references helping us to assess that the OMIM reference is specific to RD clinical diagnosis. The fact that it is present in OMIM as an indvidual entry is not a proper indicator as their inclusion criteria are different from ours. As you mentioned, this gene is linked to ORPHA:528084 might say it is not specific enough to be considered (or MADD gene involved in different phenotypes as well)
Thank you for clarifying, then this will be assigned to someone in the team, it may take up to 6 months to be reviewed in Orphanet disease meeting.

Kind Regards, 
Marie-Cécile

**Comment by uunter98** [comment]
Dear Marie-Cecile,

thank you for your consideration! My request was too incomplete, sorry for that. Actually, mutations in the MADD gene cause either "Neurodevelopmental disorder with dysmorphic facies, impaired speech and hypotonia", which in Orphanet was apparently considered unspecific, or DEEAH syndrome (developmental delay with endocrine, exocrine, autonomic, and hematologic abnormalities). The latter was now encountered by a coder here, and it sounded rather specific to me (the clinician suspected it because the child has, among other things, pancreatic exocrine dysfunction). In general, patients have "additional systemic involvement, most notably endocrine abnormalities".
Here is the link to the gene: https://www.omim.org/entry/603584
and here to the disorder: https://www.omim.org/entry/619004

Apparently, at least 15 cases have been reported. The respective literature is mentioned in OMIM.

I hope this is helpful. Thank you and kind regards
Ursula

**Comment by MCecile-US14** [comment]
Thank you for the details @uunter98 !

@Mickael-Orphanet please consider this new entry in the coming Orphanet disease meeting 

Kind Regards, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @uunter98 , 

Based on current literature, Orphanet medical and scientific committee has validated the creation of ‘MADD-related developmental delay-endocrine dysfunction-hypohemoglobinemia syndrome’, ORPHA:686495. A rare developmental anomaly, due to the mutation of MADD gene, characterised by developmental delay, respiratory distress like apnea, severe muscular hypotonia and possibly hypoglycaemia. Other findings can be exocrine pancreatic insufficiency and endocrine dysfunction as hypothyroidism, growth hormone deficiency and hypopthypituitarism. Furthermore haematological abnormalities with low levels of haemoglobin can be found in patients. 
Because there was two groups of patients with different clinical signs we have linked the gene MADD to also Non-specific syndromic intellectual disability ORPHA:528084.

Please be aware the informations will be only visible next week on the Orphanet website. 

Best regards, 
Mickael

**Comment by uunter98** [comment]
Dear @Mickael-Orphanet, thank you, this is fantastic!! I checked the entity on Consor, and for some reason, I get an error message when clicking on it. I have never seen this type of error message before, sending you a screen shot as an attachement. Maybe it is just me though..?!
![2024-10-01](https://github.com/user-attachments/assets/98ae0214-5a44-470a-b70c-d41232163250)

thxx again
Ursula

**Comment by uunter98** [comment]
Ahh ok, thank you so much @Mickael-Orphanet !!
