### ISSUE TITLE
OMIM numbers linked to ORPHA:511 Maple syrup urine disease

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#245]
Dear all,

Regarding ORPHA:511 Maple syrup urine disease, a Spanish expert suggests assigning OMIM [620698](https://omim.org/entry/620698).
I have reviewed the OMIM numbers assigned to ORPHA, and it would also be necessary to link OMIM [620699](https://omim.org/entry/620699).

When seeing the information that appears in Arbor about ORPHA:511, I was surprised how you have assigned the OMIM to this entity and its children.

There are two OMIM assigned to ORPHA:511:
**ORPHA:511** Maple syrup urine disease			
OMIM : 248600 (E)	
OMIM : 615135 (BTNT)	

But then, one of the OMIMs is assigned to all the children, and the other to only one of them:
**ORPHA:268145** Classic maple syrup urine disease		
OMIM : 248600 (NTBT)
**ORPHA:268162** Intermediate maple syrup urine disease		
OMIM : 248600 (NTBT)
OMIM : 615135 (BTNT)
**ORPHA:268173** Intermittent maple syrup urine disease		
OMIM : 248600 (NTBT)
**ORPHA:268184** Thiamine-responsive maple syrup urine disease		
OMIM : 248600 (NTBT)

Since it is assigned to the parent, shouldn't both OMIMs be assigned to all children?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your request, this will be reviewed in the coming months with your suggestion by the next Orphanet Nomenclature Alignements manager starting in September. We will keep you update once it is done.
Kind Regards, 
Marie-Cécile

**Comment by Mickael-Orphanet** [comment]
Dear @Orphanet-ES,

I agree that the previous information was misleading. I have updated the OMIM entries based on the understanding that Maple Syrup Urine Disease (MSUD) can be caused by mutations in the BCKDHA, BCKDHB, or DBT genes for the following subtypes:

- Classic Maple Syrup Urine Disease (ORPHA:268145)
- Intermediate Maple Syrup Urine Disease (ORPHA:268162)
- Intermittent Maple Syrup Urine Disease (ORPHA:268173)

For these subtypes, as well as for Maple Syrup Urine Disease (ORPHA:511), I have linked the following OMIM entries: 248600, 620698, 620699, and 615135 (for BTNT).

For Thiamine-Responsive Maple Syrup Urine Disease (ORPHA:268184), the only gene involved is DBT, so I have linked OMIM entry 620699 (NTBT).

Additionally, for Intermediate Maple Syrup Urine Disease (ORPHA:268162), I will include OMIM 615135 (BTNT).

I have also unlink the genes BCKDHA and BCKDHB from Thiamine-Responsive Maple Syrup Urine Disease (ORPHA:268184) as a quality control.

Please note that these changes will be visible next week.

Best regards,
Mickael

**Comment by Orphanet-ES** [comment]
Dear @Mickael-Orphanet ,

Thank you for the thorough review of this classification and the corrections.
I have informed the expert about it.

Kind regards, 

María Elena
