### ISSUE TITLE
Subtypes of facioscapulohumeral dystrophy

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#257]
Dear all,

I have to update a diagnostic test (dgsID 35200) related to facioscapulohumeral dystrophy (ORPHA:269). 

The lab distinguishes between:
1) **Facioscapulohumeral muscular dystrophy type 1**, due to contraction of the D4Z4 macrosatellite repeat identifiable by southern blot (targeted mutation analysis). See: https://gentest.healthdata.be/genetic_test/17 
https://omim.org/entry/158900 

2) **Facioscapulohumeral muscular dystrophy type 2**, identified based on the hypomethylation of the D4Z4 repeat array by PCR-based techniques (methylation analysis). See: https://gentest.healthdata.be/genetic_test/33
https://www.omim.org/entry/158901 

In the Orphanet nomenclature, we don't have subtypes for this disorder. Is this because, despite the fact that FSHD types 1 and 2 have different genetic causes, the clinical features are not distinct enough to consider the creation of subtypes in Orphanet?

Thanks in advance for your feedback, kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Thank you for your message. Actually, in my former lab, I worked intensively on research about FSHD with various clincial cases so I am happy to get to answer you on this one :)
Indeed as you are mentioning clinical distinction between FSHD1 and 2 patients is almost impossible and not really consistent with the molecular diagnosis (i.e. SMCHD1 gene disregulated in both FSHD1 and FSHD2). Also, despite advancement on the understanding of the physiopathology mechanisms (that are still not fully understood), within FSHD1 patients there is still about 30% of them remaining fully asymptomatic/ showing incomplete penetrance (even if all carrying D4Z4 contraction).

Therefore considering the criteria Orphanet uses to create individual entities as subtypes of the same disorder; here it does not seems there is a clinical or etiological need to distinguish both forms (e.g. since few years, some papers are even describing FSHD3 type, PMID:32467133) as there have always been several genes disregulated in the subtelomeric region containing D4Z4 macrosatellite.
The abstract have been recently reviewed by the the expert Pr Sabrina Sacconi who showed that 'FSHD1 and 2 form a disease continuum' (PMID:30979860), and conforting the idea subtyping the patients in Orphanet is not relevant (as for now).

Hope this helps, 
Kind Regards
Marie-Cécile

**Comment by Orphabe** [comment]
Dear Marie-Cécile,

Thank you very much for your answer and your expert's eye on this question ;-)

It helps for sure.

Kind regards,

Annabelle
