### ISSUE TITLE
Is assignment of ORPHA code ORPHA:199627   (Disorder)  “Atypical autism” sufficient in patient with atypical autism with no additional symptoms (epilepsy, organ defect, dysmorphia, ID), after wide molecular testing?

### ISSUE THREAD

**Issue by AMPilarczyk-PL** [OD4RD/Main-Help-Desk#27]

**Comment by MCecile-US14** [comment]
Dear @AMPilarczyk-PL , 

ORPHA:199627 'Atypical autism' have been created in order to fit:
*patients who does not present specific autism features (_since autism per se is not rare_) 
*patients for whom atypical autism features are not clinical signs of another disease.

As the definition stands, it is characterized by milder developmental and social delay and less stereotypical autistic behavior. 
If extensive and exhaustive molecular and clinical diagnosis have been assessed then it is the correct ORPHAcode to use. 
Please note that it may be revised if new clinical or genetic data are identified so please encourage clinicians to publish a case report if patient diagnosis are refined /clarified.

Your inital answer was correct :)
Kind regards, 
Marie-Cécile

**Comment by AMPilarczyk-PL** [comment]
Dear Marie-Cecile,
Thank you very much for your comment!
AMPilarczyk-PL
