### ISSUE TITLE
Auto-Brewery Syndrome

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#280]
Hello,

Please consider the inclusion in the nomenclature of the entity Auto-Brewery Syndrome or Gut fermentation syndrome.

The request comes from a coder at the Inselpistal in Bern where they have at least one patient with this condition.

References: PMID: 33209539, 30020718

Thanks

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetSwitzerland , 

We treated this creation few months ago, from another request. Here is our decision: 

According to Orphanet's rules, an entity has to meet several criteria to be included into the nomenclature: a clear homogeneous phenotype, at least 2 minimum cases and a prevalence under 1/2000. Based on the current scientific literature, Orphanet medical and scientific committee have detected that one or several criteria is/are missing: strong epidemiological data to state that is rare knowing that most literature states that it may not be rare. Furthermore it is not a disorder per se but a condition that is link to other comorbidities and/or food habits. Do not hesitate to contact us if supplementary information could be considered or to inform us about new publications in order to re-evaluate the decision. 

Best, regards, 
Mickael

**Comment by OrphanetSwitzerland** [comment]
Thank you for the feedback.
