### ISSUE TITLE
SNOMED IDs-ORPHAcodes: extension of the mapping

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#283]
Dear all,

In Belgium, a university hospital is working on a **SNOMED CT rare disease list extension**, in order to include all SNOMED children of the SNOMED terms that occur in the Orpha mapping in the list of rare SNOMED codes.

During a discussion with members of this team, I recalled the importance of having these mappings validated by medical experts but also, I mentioned the fact that there are (very few) exceptions where certain subtypes of rare disorders are not themselves rare. It seems to me that an example was shown by someone from the nomenclature team (Caterina? Marie-Cécile?) during training or an open session. But I can't come across it. Can you help me? Or are my memories wrong?

More generally, what are the points of attention for teams who wish to do the work themselves of completing the SNOMED-ORPHAcodes mapping to extend it to classification levels other than that of "disorders"?

Thanks in advance for your feedback, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Seed-Orphanet** [comment]
Dear @Orphabe,

Thank you for your message.

In Orphanet, to my knowledge, we do not have subtypes that are not rare. This is because subtypes must completely cover the entire perimeter of the disorder level, and if a subtype is not rare, the disorder would not be rare either.

Regarding mappings with SNOMED CT, we prioritize the disorder level. Since all the subtypes we include in Orphanet are rare, if there are corresponding SNOMED entities for these subtypes, the hospital team can proceed to map them.

I hope this helps clarify. Let me know if further details are needed!

Kind regards,
Seed

**Comment by Orphabe** [comment]
Dear Seed,

Thank you for your reply. The professional (a RD coordinator in a Belgian university hospital using SNOMED CT in their local system) would like to provide the following clarification, as she is not sure whether her question was properly understood:

"_What we would in fact be doing is to map the Snomed subtype to the Orphacode of its parent. It means that if Snomed 1 is mapped to Orpha A, and Snomed 1.1 is the child of Snomed 1 but itself not mapped to an Orphacode, we map it to Orpha A.
So the question is: would Snomed 1.1 always be rare, even though it is not itself mapped to an Orphacode in the official mapping release?_".

Is this methodology of mapping a SNOMED subgroup to an ORPHAcode corresponding to the SNOMED parent correct? And can you confirm that it respects the fact that all codes in this situation represent rare conditions ?

I hope this is clearer. If not, I will suggest to the professional to continue the conversation with you directly, either via GitHub or by email.

Thank you, kind regards,

Annabelle (Orphanet Belgium)

**Comment by Seed-Orphanet** [comment]
Dear @Orphabe 
I reached out to our contact at SNOMED, to be sure that the rules at SNOMED on adding children concepts are the same as in Orphanet (i.e. that the child concept of a rare parent is also rare in the case of SNOMED CT, like it is for us in Orphanet).
I will update you as soon as I have their answer.
Have a nice day!
Kind regards,
Seed

**Comment by Seed-Orphanet** [comment]
Dear @Orphabe 
here is the reply from SNOMED directly:
"The scope of the SNOMED CT to Orphanet map is at disorder level and as you mention, the maps are 1:1 (exact matches). Subtypes of disorder would usually be excluded from the maps. The proposal to map subtypes to the parent ORPHA code does not align with the use case for the published map. This proposal is not something we would support because of the complexity of rare diseases. 
In SNOMED CT we don’t use the term ‘rare disease’ or have a hierarchy relating to rare disease, the content is classified by the characteristics of each disease and **so we cannot assert that a concept will always be rare**.
All content mapped for this project is 1:1 and our mapping principle is to review each concept separately for mapping purposes."

Therefore, if the RD expert chooses to proceed with this alignment, it would be at their own discretion and risk. This is an additional argument for medical professionals to code patients using ORPHAcodes, since this way the rarity would be assured, and this would enable statistical analysis of rare disease.
Please feel free to share this feedback with them!
Kind regards,
Seed
