### ISSUE TITLE
 I have difficulty finding the “Preferred Parent” of rare diseases. This is a very useful concept, could you explain to me how to find it?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#36]
**Our reply:** "When you want to find the preferential parent of an ORPHAcode, you have to use the linearization file. You can find it in the nomenclature package on Orphadata".

**Response from the person asking the question:** "To be sure that I have understood the structure of the linearization document (because I am not used to xml documents):
- the preferred parent for Al-Gazali type multiple epiphyseal dysplasia (ORPHA:166024) is Rare bone disease (ORPHA:93419)?
- the preferred parent for Alexander disease (ORPHA:58) is Rare neurological disease (ORPHA: 98006)?"

**Our reply:** Regarding the xml linearization file: you can always open it in Excel.

You do it like this:
1. Save xml file.
2. Open excel and open xml file in xls.
3. Select Open xml ‘As a read-only workbook'.
Then you can just save the file as an xls document.

When you open the xls document, you will find the ORPHAcode in the AD column and the preferred parent in the X column.

To answer your question :
- the preferred parent for Al-Gazali type multiple epiphyseal dysplasia (ORPHA:166024) is Rare bone disease (ORPHA:93419) --> Yes
- the preferred parent for Alexander disease (ORPHA:58) is Rare neurological disease (ORPHA: 98006) --> Yes

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Your answer is correct, thank you for bringing it up, I reused the mini step by step procedure you wrote to implement the Wiki page here:[Preferential parent](https://github.com/OD4RD/Main-Help-Desk/wiki/Orphanet-classification#how-to-find-the-preferential-parent-of-a-disorder-in-orphanet-classification-how-to-access-the-information-in-the-linearisation-file)

Each entity in the Orphanet nomenclature is assigned one preferred classification group = reflecting the specialty or system it is more affected in the disease (or according to a set of explicit rules where no major affected system is recognisable). This is called a "**preferential parent**".  
This is done by Orphanet in order to enable the sorting out of all clinical entities by medical domain, and to avoid bias counting of multi-classified entities in statistical analysis when using Orphanet datasets.  

This process is called **« linearisation »**, and a procedure is available on the Orphanet website [Linearisation rules](https://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_linearisation_rules.pdf).
