### ISSUE TITLE
What could we do if there is no ORPHAcode for a patient?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#37]
Question received from a clinician: "What could we do if there is no ORPHAcode for a patient. For instance, I have a patient with a POLR2A mutation. I put her in the registry, without a code, but with a comment. I hope the information will be transferred to the registry. 
Is this OK? ".

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Since ORPHAcodes are meant to describe Rare Disease phenotypes only, acccording to European Regulation on orphan medicinal products it is common to not find a corresponding ORPHAcode to any patient. 
Indeed, many gene mutations and genetic diseases are not rare and hence they are not part of the Orphanet Nomenclature classification.  

In that case, POLR2A mutations are represented in various clinical context and syndromes and you can find dedicated information in OMIM database, the online catalog of Human genes and genetic disorders.  
 It is suitable to keep the genetic mutation information in any relevant space in the registry (comment text box, supplementary or genetic information field etc...) as a comment.  

Kind Regards, 
Marie-Cécile
