### ISSUE TITLE
Creation of a new clinical entity for "CHD8 overgrowth syndrome"?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#39]
**Question with regard to a registration in the Belgian central registry of rare diseases (CRRD):**
"We received a request for the registration in CRRD of a patient with ‘CHD8 overgrowth syndrome’. No ORPHAcode exists for this RD, CHD8 is known to be linked to Autism but now several pubs (> 2) also link this to an overgrowth syndrome.

_Please note that this question was also posted in Redminor (Disease Gene IS #20091)._

**Our current analysis (waiting for the OCT feedback):** 
Currently, no specific ORPHAcode exists for this condition. In Orphanet, the CHD8 gene is only listed as a major susceptibility factor in NON RARE IN EUROPE: Autism (ORPHA:106).
See for more info on this syndrome: 
https://pubmed.ncbi.nlm.nih.gov/31721432/
https://pubmed.ncbi.nlm.nih.gov/31980904/
https://pubmed.ncbi.nlm.nih.gov/28475857/
In OMIM, there is no confirmed Gene-Phenotype relationship but "Autism, susceptibility to, 18" (# 615032) includes some cases with macrocephaly.

In Spectrum, a source of news and expert opinion on autism research, it is stated that: "People with mutations in CHD8, a top autism gene, tend to be tall and have large heads, according to a new study. They also tend to have intellectual disability. The traits define a unique condition that the researchers call ‘CHD8 overgrowth syndrome'".

However, we are not convinced that a distinct clinical entity should be created for “CHD8 overgrowth syndrome, based on info available in this publication: https://www.nature.com/articles/s41398-022-02189-1.pdf 

Indeed, it is already known that the syndrome caused by pathogenic variants in CHD8 consists of a very broad range of phenotypic abnormalities in multiple organ systems (involving overgrowth but also developmental delay, neurological, behavioural and psychiatric, gastrointestinal, musculoskeletal, and genitourinary abnormalities). So should they all be considered a specific condition, I am not sure… Could you please take a look at this request and see if this syndrome should be created in Orphanet as a new separate clinical entity?

Thank you,
Annabelle

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 
I take note of this request of creation, I also checked the recent ticket on Redmin, it will be assigned to the person in charge as soon as possible depending on his priority.
As a good pratice, remember it is not necessary to double post these requests here and there as it will comprise quality of data for project report/annual statistics.
Our suggestion is you can keep to post issue in the GitHub for Orphanet Nomenclature issue in particular, and when it concerns National Hubs (from/for). Since this request concerns an expert centre I suggest to keep it as a ticket in Redmin and I will close this issue here.
Thank you for your understanding, 
Kind Regards,
