### ISSUE TITLE
A question about ORDO

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#43]
Dear Marc,

Last week we gave a course on the Orphanet nomenclature to professionals in Catalonia.
One of them, a data analyst, asked me questions about ORDO, which I was able to answer later by email.
But I think I have reached the limit of my knowledge with ORDO, so I pass these questions/comments to you:

_In the ORDO database, would it be possible to include in the records at the level of disorder the groups of which they are part of in the "parents" section and not only in the "part_of" variable?
Otherwise, can we deduce that the variable "Parents" only lists child-parent relationships between entities of the same type and that the variable "Part_of" only lists child-parent relationships between different types? How these two fields differenciate by definition?_

Kind regards, 

María Elena

**Comment by caterina-lucano-orphanet** [comment]
Dear Maria-Elena, thank you for your question, I am passing it on to the IT team and will come back to you when we have an answer.
Best regards,
Caterina

**Comment by davidlagorce** [comment]
Dear user,
first of all ORDO (Orphanet Rare Disease Ontology) is not a database but an ontology, which means that ORDO is a description in a formal graph-based computer reading language of the objects, concepts, definitions and relationships stored in the Orphanet knowledge database, and obviously its nomenclature.
So, it depends on the way and the tools you employ in order to display and browse ORDO (on the web like OLS or Bioportal, on a software like Protégé or via a SPARQL querying facility for instance by using the Blazegraph that we offer on Orphadata).
I'm not sure to understand your question because some solutions like Protégé offer the ability to infer the ontology hierarchy and then find out from which parents a disorder is a subclass of and/or from which disorder type a subtype is part of. This is available in all directions of the graph by querying ORDO in SPARQL for example, regardless of the "disorder type" as you mention and note that the parent is not a "variable".
Note that the new ORDO model in the coming days on Orphadata will be easier to use and interpret.

Furthermore, in order to explore the hierarchy of the Orphanet normenclature (parent-child relationships), you can also use the RDCODE API (https://api.orphacode.org/) and the Datavisualiser (https://dataviz.orphacode.org/). 
Finally, I also advise you to have a look at the Orphapackets (which are a unique extraction of the Orphanet knowledge database per single active entity, in a json format, integrating according to your question the parent-child relationships. They are free available at https://github.com/Orphanet/orphapacket and will be updated at the same time that ORDO in few days. 
Best regards
David

**Comment by Orphanet-ES** [comment]
Dear David,

Thanks for your answer.

I have forwarded your message to the expert who asked, and as soon as he tells me if he has more doubts or everything has been clarified, I will inform you.

Best regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear David,

Regarding your comment "Note that the new ORDO model in the coming days on Orphadata will be easier to use and interpret", could you tell me what is the release date?

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Sorry, I have seen that the last version is from the 6th of December.
Have the improvements you mentioned been implemented in this version?

Kind regards, 

María Elena

**Comment by caterina-lucano-orphanet** [comment]
Hi Maria Elena,
I am not sure that David saw your reply, I am tagging him to that he can have a notification!
@davidlagorce I think that the improvements have indeed been implemented in the latest release, but could you please confirm that?

Thanks,
Caterina

**Comment by davidlagorce** [comment]
Yes the last 4.2 version at https://www.orphadata.com/ordo/ embed this capability to discover partOf and subclassOf elements, but visualisation depends on which facility do you employ to discover the ontology (SPARQL querying or Protégé....) 
Please also note that OLS still have not deployed this last version. 
Thanks 
David

**Comment by Orphanet-ES** [comment]
Thanks David!
I will inform the expert.

Kind regards, 

María Elena
