### ISSUE TITLE
Hypothalamic Hamartoma

### ISSUE THREAD

**Issue by MartinArles** [OD4RD/Main-Help-Desk#44]
A couple of questions received from a Swiss coder at the Kinderspital Zürich concerning Hypothalamic Hamartoma:

1-
How would you recommend to code a patient with _Central precocious puberty with hypothalamic hamartomas_, given that:
      -	The text for ORPHA 86906 (Hypothalamic hamartomas with gelastic seizures) says “Some patients also present a precocious puberty”.
      -	The text for ORPHA 759 (Central precocious puberty) says: “It is idiopathic or secondary to hypothalamic lesions such as tumors (hypothalamic hamartoma, glioma, astrocytoma)”.

Should we use both codes?

2-
Can we use the code ORPHA 86906 (Hypothalamic hamartomas with gelastic seizures) for a child with Hypothalamic hamartomas but, for now, without seizures?
Hypothalamic hamartomas seem to be rare: https://rarediseases.org/rare-diseases/hypothalamic-hamartoma.

Thank you

**Comment by MCecile-US14** [comment]
Dear @MartinArles @OrphanetSwitzerland, 

Thank you for sharing these coding issues and sorry for our late reply. Regarding:
1- Does this patient also #present gelastic seizures ? In this case, and often hypothalamic harmartomas are early congenital anomalies leading to puberty troubles later on such as 'Central precocious puberty'. We do not recommend to use both codes, but ORPHA:759 only (as written implies 'it is idiopathic or secondary to hypothalmic lesions..'
This entity is currently under re evaluation with an expert about prevalence (unlikely it will be consider non rare) but keep in mind some changes can happen in the near future.

2-In the same frame, most likely the child patient does not present yet gleastic seizures because he is too young but ORPHA:86906 definition described 'early-onset gelastic or dacrystic seizures [...] In many patients, seizures progress to other seizure types including focal and generalized seizures' but ORPHA:86906 'Hypothalamic hamartomas with gelastic seizures' is the right code to use and we will probably revise the prefered term to extend the perimeter accordingly to the definition (including all types of seizures).

Hope this answer your coding issues, 
Kind Regards, 
Marie-Cécile

**Comment by OrphanetSwitzerland** [comment]
Thank you for the answer, we will transmit it to the coder involved.
