### ISSUE TITLE
Rule which governs ORPHA code assignment

### ISSUE THREAD

**Issue by AMPilarczyk-PL** [OD4RD/Main-Help-Desk#46]
Key to assignment of an ORPHA code to an RD entity in the Orphanet - these codes are sometimes 3-digits, but sometimes even 6-digits. Is there any rule which governs this process or is it random?

**Comment by MCecile-US14** [comment]
Dear @AMPilarczyk-PL, 

Thank you for your question. One of the main rule of Orphanet Nomenclature and classification is that an ORPHAcode always correspond to a single entity and despite any modification or inactivation applied to it, it can never been reused. This is because an inactivate entity can be reintroduce in the Nomenclature and for consistency within our classification system.

Because of this, there is no rule consistency between an ORPHAcode digit number of a head of classification and ORPHAcode # disorders below it. But it is not random either, you can only be sure that 3-digits ORPHAcode have been created first in the first years of the database while 5 or 6-digits ORPHAcodes are the recent ones created since we implement them increasingly with time.

Kind Regards, 
Marie-Cécile

PS: please note for general Nomenclature/Classification and Coding issues you can assign me, the alias @Orphanet is Marc who is mostly in charge of the IT related issue :) thank you
