### ISSUE TITLE
Questions on mapping files ICD-10 and Snomed CT 

### ISSUE THREAD

**Issue by bh666666** [OD4RD/Main-Help-Desk#47]
Hi there

Using ORPHA codes, we are undertaking a research on rare diseases in our UK cohort using both linked hospital (SUS,ICD-10) and primary care datasets(SystmOne ,Snomed CT ). We have a few quick questions on the ORPHA codes and we hope you could help us.

1.	For the mapping of hospital data using ICD-10 codes, we used ORPHAnomenclature_MasterFile_2022 excel file in the Orphanet nomenclature pack 2022. For the mapping of GP data in SystmOne, we used ORPHA-SNOMEDCT_Mapping_File_production.csv file on the same webpage on Orphanet. Are these the correct files to use for mapping? 

2.	To identify rare diseases cases in our cohort, we mapped all relevant codes to these two files mentioned above. It is right to say any identified person would have a rare disease using this method? 

3.	There were some large differences in identified participants in our cohort using hospital data only and using primary care data only. Why would this be the case? Are there any differences in terms of identifying a rare diseases using ICD-10 and Snowmed CT mapping files on Orphanet?  

4.	Some papers have only used ICD-10 mapping to identify rare diseases. Would it be better to use both GP and Hospital data to identify a rare disease where these data were available? Are these two mapping files complementary to each other- in the sense it will give a fuller mapping of the cohort with a rare disease? Or should we only use ICD-10 codes? 

Thanks a lot for answering these questions!

**Comment by JTorphanet** [comment]
Dear Bo,

Please find below our answers for each point: 

1. Indeed, Orphanet has two separated alignment files, one to each terminology due to different alignment procedures and timing of release. Orphanet- SNOMED mapping is released every year in October whereas Orphanet-ICD10 alignment is released in July in the Orphanet Nomenclature pack. The two files you mention are indeed the correct ones.
For your information:
-	Procedural document for ICD10 alignment 
https://www.orpha.net/orphacom/cahiers/docs/GB/Orphanet_ICD10_coding_rules_R1_Nom_ICD_EP_06.pdf
-	Release notes for SNOMED CT mapping
https://www.orphadata.com/docs/SNOMEDCT_Release-notes-1.pdf

2.  For SNOMED CT, we generate the alignment based only on an exact relationship. Therefore, when an alignment Orphanet-SNOMED exists, it means that the disease is rare. For ICD10, however, the mapping is qualified by 4 proximity relationships (always in the sense ORPHAcode -> ICD10 terminology):
-	Exact match
-	NTBT (narrower term to broader term): the Orphanet entity has a narrower range than the ICD10 code used to represent it.
-	BTNT (broader term to narrower term): the Orphanet entity has a broader range than the ICD10 code used to represent it. 
-	ND (not yet decided or unable to decide): is reserved for complex cases when the alignment cannot be qualified by any of   the preceding labels. 
In that sense, your approach is good for correctly representing rare diseases for the SNOMED CT alignment. When using ICD-10 you will have 2 possible cases:
1) Only the exact and NTBT relationships for the ICD10 alignment correspond to rare diseases;
2) The BTNT and ND matches do not allow to have the level of precision necessary to state that the patients are affected by a rare disease.
This is because the ICD10 terminology is less granular than the Orphanet terminology and is not focused on rare diseases (this will ameliorate in the following year in the ICD11, thanks to an ongoing outstanding collaboration between Orphanet and the WHO). To have access to the proximity relationships, you have to use another file in the nomenclature pack named “ORPHA_ICD10_mapping_en”. The Masterfile is useful when you look for an ICD10 code from an ORPHAcode. 

3. See my previous answer, that explains why there are differences by using the two mapping files.

4. If you assume that all patients coded with an ICD10 code that is aligned to an ORPHAcode has a rare disease, unfortunately you are highly overestimating the number of rare diseases patients. This is because of the 4 proximity relationships explained in point 2. In order to surely identify only rare diseases you should only include in your analysis “Exact” and “NTBT” aligned codes. However, with this approach, you will for sure underestimate the number of rare diseases patients (because you are excluding BTNT and ND matches, that might or might not be rare diseases, but the level of precision is not available in ICD10).
Neither ICD10 nor SNOMED-CT is a terminology focused on rare diseases, unlike Orphanet. In the case of SNOMED CT, an ongoing long-term collaboration has allowed us to perform an exact mapping by adding rare diseases concepts coming from Orphanet in SNOMED-CT (In the last release, the coverage was 88%). This means that you will have a more precise result using the SNOMED-CT alignment, even if you will still miss a portion of patients (18% of rare diseases). Therefore, in order to detect as many rare diseases as possible in your cohort, I advise you to use the both systems as complementary. 
For all the reasons stated above and for the impossibility to recover the totality of all rare disease patients from other terminologies not focused on rare diseases, Orphanet strongly promotes the use of ORPHAcodes to ensure, facilitate and improve the visibility of rare diseases in European Health information systems. 

In the next coming months, we will update the wikipage about alignments and I invite you to consult it !
(https://github.com/OD4RD/Main-Help-Desk/wiki/Alignements-with-others-terminologies)

Let us know if you need more clarifications, 

Best regards, 
Julie
