### ISSUE TITLE
ERKNet orphacodes

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#50]
Dear all, 

Expert kidney disease centers in Catalonia have asked us about the ORPHA codes of ERKNet registry.

Comparing, for example, the glomerulopathies of the Orphanet classification and that of ERKNet, there are some discrepancies.
https://www.erknet.org/fileadmin/files/user_upload/v.4_Rare_Kidney_Diseases_List_with_Orphacodes___instructions.pdf
https://www.erknet.org/patients-registry/useful-documents/orphacode-renal-diagnoses-hierarchical-tree

Some entities are not classified under the same group, there are some inactive codes and some "new" ones.
For instance, these"new" glomerulopathies that I have identified are:

- Nephrotic syndrome, syndromic, not otherwise specified (9999972.0)	
- IgA nephropathy (9999982.0)	
- Alport syndrome, digenic (9999965.0)	
- Microscopic (including familial) hematuria (9999976.0)	
- Collagenopathy, not further specified (9999977.0)	
- Immune complex associated membranoproliferative glomerulonephritis, not otherwise specified (9999975.0)	
- Monoclonal gammopathy of renal significance (9999974.0)	
- C3 glomerulopathy secondary to MGRS (9999970.0)	
- Proliferative glomerulonephritis with monoclonal immune deposits (PGNMID) (9999971.0)	

Are you going to create these new entities in Orphanet?
If not, what ORPHAcode should they use to code those clinical entities?

I haven't reviewed the rest of the kidney disease groups but I assume there will be similar discrepancies as well.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your comment, we take not of these requests. Orphanet completed the revision of the renal diseases classification (including glomerulopathies) in 2019 throughout collaboration and discussion with experts from ERKNet. 
I believed some inactivated codes come from this revision. We will look more in details in the "new" ones you identified and come back to you with a precise answer. Looking briefly at the list, some of them does not seem rare to be created. 
Then, no ORPHAcode can be used to code those clinical entities, clinicians should use ICD-10/11 corresponding codes.

Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

For now, it seems some are not specific enough, such as 'Collagenopathy, not further specified' ?
In order to better adress these requests, we would consider the creation even if it is rare in only one 'age-group' of patients but we need to assess the **proportion and a clear age definition** based on the literature. e.g. ORPHA:2828 'Young-onset Parkinson disease'
You can now refer to the wiki page for the detail of categories: [Orphanet classification of the age of onset](https://github.com/OD4RD/Main-Help-Desk/wiki/Epidemiology-in-Rare-Diseases#orphanet-classification-of-the-age-of-onset)

Could you please ask the expert and/or provide us specific PMID for those diseases with proportion or clear age definition? 
The epidemiology project manager @moi-epiUS14 started to collect information and she will complete this soon but without literature evidence that it is rare in a sub population groups it will be hard to confirm.

Thank you, 
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear Marie-Cécile,

I have asked the expert for rare kidney diseases for a specific population, and if he had any literature on it, and I will let you know as soon as I have an answer.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear Marie-Cécile,

I have not had a response from the experts who informed me of this problem with the codes created by ERKNet, but have you had the opportunity to discuss this issue with the members of the network?

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

For the moment I will exclude these entities (below) for the reviewing process, it's not possible to clearly define a perimeter:
Nephrotic syndrome, syndromic, not otherwise specified (9999972.0)
Collagenopathy, not further specified (9999977.0)
Immune complex associated membranoproliferative glomerulonephritis, not otherwise specified (9999975.0)

Otherwise, @moi-epiUS14 has already studied the epidemiological status of IgA nephropathy and it seems not rare in Europe. However, there are several orphan drugs registered related to this disease, so we will discuss it at the Orphanet committee meeting to make a decision. 

I will let you know for the others ASAP. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES, 

We have just validated the creation of Digenic Alport syndrome under the ORPHAcode 653722. 
About the request left: 
- **Microscopic (including familial) hematuria (9999976.0):** it's not a disease but a clinical sign and it's not rare. 
- **C3 glomerulopathy secondary to MGRS (9999970.0):** please consult ORPHA 329918 and 329903 

And for Monoclonal gammopathy of renal significance  and Proliferative glomerulonephritis with monoclonal immune deposits (PGNMID): both are groups of disorders, so please try to re-contact your experts to clarify which diseases are needed. I can also advise you to propose to your experts to contact directly ERKnet to clarify the missing entities. 

Thank you, 
Best, 

Julie

**Comment by Orphanet-ES** [comment]
Dear @caterina-lucano-orphanet , 

Thank you for letting me know about the review of this disease.
Once its inclusion in Orphanet is approved, I will inform the Spanish professionals who requested that it be considered a rare disease, and I will review and register all the clinical trials that I previously discarded on this disease.

Kind regards, 

María Elena

**Comment by JTorphanet** [comment]
Dear @Orphanet-ES,

Just to inform you, I have reactivated the ORPHAcode 34145 corresponding to IgA nephropathy based on the last publication provided by ERKnet.  

Best regards, 

Julie
