### ISSUE TITLE
Subtype of disorder that has subtypes

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#54]
Dear all, 

Consulting Arbor, I have seen that there is a subtype of disorder that in turn has subtypes.
Is this correct?
I had always thought that a subtype was the lowest level of the classification and not that there could be several levels of subtypes.

18082 (Subtype of disorder) Obesity due to congenital leptin resistance	

- 11020 (Subtype of disorder) Obesity due to pro-opiomelanocortin deficiency
- 11021 (Subtype of disorder) Obesity due to prohormone convertase I deficiency
- 11022 (Subtype of disorder) Obesity due to melanocortin 4 receptor deficiency
- 18083 (Subtype of disorder) Obesity due to leptin receptor gene deficiency

How do you define what is a disorder and what is a subtype?

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear Maria Elena, 

Thank you for the notice.
Indeed there is few examples in Orphanet classifications where you can find subtype(s) of subtype. This has been done on purpose for specific classification situation and request. 
As you can imagine, in general this rarely makes sense since subtypes of disorder are meant to be necessary subdivision upon level of precision need for clinical practice or as confirmed diagnosis. You can find all these details and definition in the [classification description](https://github.com/OD4RD/Main-Help-Desk/wiki/Orphanet-classification#classification-description) and in the Orphanet nomenclature and classification of RD [procedure](https://www.orpha.net/orphacom/cahiers/docs/GB/eproc_disease_inventory_R1_Nom_Dis_EP_04.pdf.)

Kind regards, 
Marie-Cécile
