### ISSUE TITLE
Intestinal atresia type IV

### ISSUE THREAD

**Issue by MartinArles** [OD4RD/Main-Help-Desk#55]
Hello,

A Swiss coder received a patient report with “Intestinal atresia type IV”. She wonders if she can use the ORPHA:1201 (Atresia of small intestine).

Another coder suggests that, as type IV is defined as producing “multiple atresias” (https://www.omim.org/entry/243600), the patient could be coded using ORPHA:2300 (Multiple intestinal atresia), and therefore added as a synonym.

What do you think?
Thanks,
Martin

**Comment by MCecile-US14** [comment]
Dear @MartinArles, @OrphanetSwitzerland, 

Apologies for the delay of response.
Thank you for your message, this has been discussed in our last disease meeting and it is clear for us that in this case **ORPHA:1201 'Atresia of small intestine'** is the only ORPHAcode to be used as following the short description: "... The malformation may be classified in four different types of small bowel atresia (SBA) based on the anatomical obstruction.", implicitely including 'Intestinal atresia type IV'.

But thanks to your coding question, it seems there has been some confusion with the synonyms of ORPHA:1201 so we decided to rename it actually as ' Small bowel atresia'; remove 'Apple peel syndrome' and 'Intestinal atresia type IIIb' as they are not exact same concept phenotype (small perimeter). + 'Atresia of small bowel' and 'SBA' have been added as EN synonyms and 'Atrésie intestinale iléale' as FR synonym.

Regarding ORPHA:2300, it describes "... numerous atresic segments in the small bowel (duodenum) or large bowel" so not specific to the small intestine. And the synonym 'Familial intestinal polyatresia syndrome' (or the prefered term) are also wrongly associated as well as the corresponding OMIM# since it is describing a very different phenotype familial disease/immunodeficiency syndrome. I will reevalute perimeter of this disease and let you know if we do nomenclature changes for ORPHA:2300 in the future.

Hope it helps and clarify your coding issue, 
Kind Regards,
Marie-Cécile
