### ISSUE TITLE
Cleft palate, cardiac defects, and mental retardation - MEIS2 gene

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#58]
Hello,

This is a question received from a  Swiss Hospital:

"One patient was diagnosed in our genetics department with a variant in the MEIS2 gene that corresponds to the phenotype described for NM_170674.5, c.905C>T : https://omim.org/entry/601740
I cannot find in Orphanet the equivalent for this mutation, which is not a 15q14 deletion.
How can my genetics colleague code this patient?"

In this case, do you need more information to assess if a new entity should be created? Would you recommend to link this patient to Non-specific syndromic intellectual disability - ORPHA:528084 (and link the MEIS2 gene to this entity)?

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Thank you for the coding request and the details provided, Have the patient been published in a case report yet?
@JTorphanet Can you look into this issue please and see if we need to consider it for creation or if it should be link to NS syndromic ID? For your own note, 'cleft palate' phenotypes could be part of a further revision with ERN CRANIO.

Thank you, 
Marie-Cécile

**Comment by OrphanetSwitzerland** [comment]
To answer your question “Have the patient been published in a case report yet?”: No this patient specifically, but there are other case reports published for this phenotype with the variants in this gene:
https://pubmed.ncbi.nlm.nih.gov/30735726/
https://pubmed.ncbi.nlm.nih.gov/33427397/

**Comment by mutaz-amin** [comment]
Dear @OrphanetSwitzerland ,

I don't think this entity falls within Non-specific syndromic ID, because there are some distinguishing features such as the cleft palate and some reported skeletal anomalies are distinct. We have several entities in Orphanet that also feature cleft palate, skeletal and cardiac anomalies, so I will need to review all those to see if the phenotype falls within one of these spectra and if otherwise to create it. I will document and present this issue and come back to you with the decision. Thank you very much

My best regards,

Mutaz

**Comment by JTorphanet** [comment]
Dear @OrphanetSwitzerland, 

Following Mutaz's decision, I have reviewed the creation. The clinical picture is very different from the entity ORPHAcode 261190, 15q14 syndrome due to specific mutation into MEIS2 gene (PMIDs: 27225850 and 30055086). 
So the decision was: 
1. Creation of a new ORPHAcode to represent the entity OMIM 600987 as a subtype: Cleft palate-congenital heart defect-intellectual disability syndrome due to MEIS2 mutation
2. Classification level changes: ORPHAcode 261190 from disorder to subtype and renaming done: Cleft palate-congenital heart defect-intellectual disability syndrome due to 15q14 microdeletion 
3. Creation of a new entity as disorder to represent the spectrum of these both entities ORPHAcode: 652519: Cleft palate-congenital heart defect-intellectual disability syndrome. 
4. Re-organization of the classification (in the coming days)

So, your genetics colleagues can identify patients with two different ORPHAcodes according to the clinical picture related to the genetic anomaly. 

Thank you for your contribution, 
Best regards, 

Julie

**Comment by OrphanetSwitzerland** [comment]
Thank you
