### ISSUE TITLE
ORPHA:1872 Cone rod dystrophy - add OMIM 617547?

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#61]
One of our expert centers (for dental care for patients with rare disorders) have a patient with mutation in the gene CFAP410. The geneticist says this patient's mutation is compatible with OMIM 617547. In Orphanet the gene CFAP410 is linked to the diagnosis ORPHA:1872 Cone rod dystrophy. We therefore ask you to evaluate whether OMIM number 617547 should be added to ORPHA:1872.

Kind regards,
Lene
Norway National Hub

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Thank you for your message. I will check the relation between this OMIM number and ORPHA 1872. I will keep you informed at the beginning of May at the latest. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Sorry for the delay. I have checked your request and for the moment I can't link this OMIM number to the ORPHA 1872 because this ORPHA concept concerns Cone rod dystrophy as an isolated affection (You can code with this ORPHAcode only if the patient met this criteria). Indeed, in two papers related to this OMIM number and the CFAP410 mutation, some patients have other variable features as truncal obesity, skeletal abnormalities, short stature, etc. 
This has raised the question of a creation as a syndromic form. I will present this point at the next Orphanet committee meeting in July. 

Best, 

Julie

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

We have decided to create a new entity named "Cone rod dystrophy-short stature syndrome" under ORPHAcode: 653709 and linked to the OMIM number 617547. 

Sorry for the delay and thank you very much for your patience, 

Julie
