### ISSUE TITLE
Transthyretin amyloid polyneuropathy: missing ORPHAcode?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#68]
Dear GitHub team,

We received the following request from Prof. Dr. Kristl Claeys, HCP representative for Euro-NMD in UZ Leuven:

**Transthyretin amyloid polyneuropathy** (for which she noticed that a corresponding SNOMED concept was missing in their electronic patient record) is not synonym for "ATTRV30M amyloidosis" (ORPHA85447), contrary to what is mentioned in the Orphanet nomenclature.

So it appears that in Orphanet there is at the moment no ORPHAcode available to define this medical condition and that also the other terms listed as synonyms of ORPHA85447  in Orphanet are not completely correct.

She suggests that "Familial amyloid polyneuropathy" (SNOMED code: 42295001) is currently the closest concept to this condition.

Could you please analyze this request?

Thank you, kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
Dear @Orphabe, 

Thank you for your message and suggestion. We will review this as soon as possible, in June and come back to you to clarify the Nomenclature issue and possible new creation.

Kind Regards, 
Marie-Cécile

**Comment by MCecile-US14** [comment]
Dear @JTorphanet , 

Could you please take a look at this request when you have time. 
Thank you
Marie-Cécile

**Comment by Orphabe** [comment]
Dear all,

Any news on this issue?

Thanks in advance for any feedback, kind regards,

Annabelle (Orphanet Belgium)

**Comment by JTorphanet** [comment]
Dear @Orphabe, 

Sorry for the delay, this request will be treated in the next Orphanet committee this month or maximum in October. 

Thank you for your patience and understanding, 

Julie

**Comment by Orphabe** [comment]
Thank you, Julie, for the follow-up.

I will let the Belgian expert who made this request know that we are working on an update to the amyloidosis classification.

Wishing you a very nice day!

Annabelle

**Comment by JTorphanet** [comment]
Dear @Orphabe, 

I am sorry for the delay, we are still waiting for an available expert. We have sent a new batch of e-mails. I will let you know as soon as I receive more information. 

Thanks, 

Julie

**Comment by JTorphanet** [comment]
Dear  @Orphabe, 

Thank you for your patience. We have received two replies from ERN experts and a recent publication (also from an ERN expert): [https://www-sciencedirect-com.proxy.insermbiblio.inist.fr/science/article/pii/S1474442223003344?via%3Dihub](url)

Based on the documentation (PMIDs 32110029, 31209302, 37863593) and expert advice, please find below our conclusions : 
- the creation of Familial amyloid polyneuropathy has not been validated; this term and its acronym (FAP) will be added as keywords to ORPHA 271861 "Hereditary ATTR amyloidosis". Familial Amyloid Polyneuropathy (FAP) was an old name for hereditary TTR amyloidosis but its use is no longer recommended by the International Society of Amyloidosis Nomenclature Committee.
- ORPHA 271861 Hereditary ATTR amyloidosis: Change main term for "Hereditary transthyretin amyloidosis"
- A classification modification for ORPHA 271861 "Hereditary ATTR amyloidosis" from Group to disorder
- Classification changes for ORPHA 85451 "ATTRV122I amyloidosis" and ORPHA 85447 "ATTRV30M amyloidosis" from disorder to subtypes of disorder 
- Mode of inheritance autosomal dominant will be added to ORPHA 271861 "Hereditary ATTR amyloidosis"
- Supplementary synonym: "Hereditary transthyretin amyloid with polyneuropathy", Hereditary TTR amyloid polyneuropathy", "Hereditary TTR amyloidosis" and "ATTRv amyloidosis" + "hATTR" (for hereditary transthyretin amyloidosis)
- A quality control will be performed by the Editorial team for recently written abtracts for these entities and to clarify the ambiguity
- As consequence, all the alignements will be checked 

Moreover, I will present this issue to the SNOMED team to discuss the discrepancies and improve the classification. 

As you probably know, we have a technical issue affecting the database and we are not able to do any implementation for the time being. As soon as this issue is fixed I will do all these modifications.

I remain at your disposal if you need more information.
I wish you a very beautiful Christmas and new year !

Julie
