### ISSUE TITLE
Rare Events

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#70]
Hello,

There was a discussion in the context of the Swiss Rare Disease Registry (in its Steering Board and inside a working group on Orpha coding) concerning what they called “rare events”.

The issue emerged as some hospitals tried retrospectively to obtain the consent from patients or families with OC such as Apnea of prematurity (ORPHA:99981) and Meconium aspiration syndrome (ORPHA:70588). The parents were surprised to receive a letter announcing a rare disease as their children were fine.

The discussion was whether these entities should be coded at all. And if the decision was not to code them, can Orphanet provide a list of these “rare events”.

Do you have a recommendation concerning this situation? Do you use terms such as “rare events” or “rare accidents”? Can we assume that if these entities have an ORPHAcode they can be coded? If it is the case, I guess that when contacting retrospectively to obtain the consent the letter should be adapted.

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland,
 
Thank you for your comment and sharing the Swiss RD registy discussion with the OD4RD community :)

As for any other ORPHAcodes and Nomenclature in general, describing a clinical phenotypes it is important to keep consistency and not adapt the use of the codes to the different patients/situations.
Both 'Apnea of prematurity' (ORPHA:99981) and 'Meconium aspiration syndrome' (ORPHA:70588) are Rare diseases that can lead to aggravated consequences (even more rare). Even if it is a sponatenous medical event not leading to any long term disease or deficiency  (need to be further assessed) these entities should be coded for patient presenting the condition described by the ORPHAcode.

Orphanet through ORPHAcodes is a Nomenclature tool provider for RD identification, in this sense our goal is to provide the most up to date RD Nomenclature for good and adapted clinical practice. But is not responsible for the (mis)usage as well as the management of each ORPHAcode in HCPs. It is the responsability of hospitals and patient registries to decide how and which RD to trace and develop consistent management rules.
Orphanet do not use 'rare events' or 'rare accidents' terms nor listed it otherwise, it would means that Orphanet would have to oddly monitor and reflect individual clinical situation about each non chronic rare diseases and particular situation/outcome,

As for personal comment we do understand how surprised the parents can be after receiving such letter announcing a rare disease for their healthy children retrospectively, our recommendation is to sensibilise and adapt carefully this kind of letter to the situation/clinical patient they are adressed to.

Hope it helps further discussions with the registry

Kind Regards, 
Marie-Cécile
