### ISSUE TITLE
Inactivated ORPHAcodes related to pharmacogenetic diagnostic tests (toxicity or dose selection)

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#71]
Dear all,

We have been contacted by an expert regarding recently inactivated ORPHAcodes that were related to pharmacogenetic diagnostic tests (toxicity or dose selection).
Since this change is not reflected in the "Disease meeting report", I would appreciate it if you could provide me with some justification for this inactivation to inform the expert, and also the list of these inactivated ORPHAcodes.

I have also seen that some ORPHAcodes related to toxicity are still active:
ORPHA:31828 Digitalis poisoning [Keyword(s): Digoxin toxicity]
ORPHA:529831 Letrozole toxicity
ORPHA:565782 Methotrexate toxicity
ORPHA:43116 Serotonin syndrome [Synonym(s): Serotonin toxicity]
Is it correct that these codes are still active?

Thank you in advance for your help.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your request.
Indeed as you know due to the hard maintenance of genetics panels in the diagnostic tests Orphanet references, causing a loss of specificity it has been decided to simply the model for diagnostic tests registered in Orphanet and removing Pharmacogenetics and Non rare entities existing only for diagnostics tests reference purposes.

We are currently proceeding to the obsolescence of these entities, so this is why this is not appearing in the Disease meeting report yet, but as soon it is done it will be explicitely mention enclosed with the list of concerned entities (next disease meeting report will be published in September and more regularly from then on), also you will find them in the next 'Translation report files' to add the term 'Obsolete' in each Orphanet translated languages.

Regarding the list of ORPHAcodes you mentioned, ORPHA:31828 Digitalis poisoning [Keyword(s): Digoxin toxicity]; ORPHA:529831 Letrozole toxicity; ORPHA:565782 Methotrexate toxicity; ORPHA:43116 Serotonin syndrome: these are all clinical entities and not Pharmacogenetic entities then not concerned and will remain active.

Hope this clarify the situation.
Kind Regards, 
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

Thanks for the information.
I await the publication of the list of inactivated pharmacogenetic entities to inform the expert who requested this information.

Kind regards, 

María Elena

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14,

Maybe I missed it, but have you published the list of inactivated pharmacogenic entities?
The expert is still waiting for this information.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

My apologies for the delay, you did not miss anything but we just verified this list and updated it with the Non rare entities.
In the attached excel file you will find all entities resumed (Pharmacogenetics and Non rare) and impacted by the evolution of diagnostics tests associated resources to ORPHAcodes.
* 39 Pharmacogenetics entities that have been OBSOLETED (inactivated); the ORPHAcodes are mentioned for tracing matters but are not displayed on Orphanet anymore.
* 116 Non Rare Diseases are now unlinked status/No resources (DGS) can be associated to these entities anymore. Few are still listed in red as some resources are still legally linked to those. Similarly as the obsoleted pharmacogenetics, the ORPHAcodes are mentionned for internal use only and are not foundable neither displayed on Orphanet website. 
[PatId_OBSOLETE_Pharmaco_NON-RARE_DGS_Nov2023.xlsx](https://github.com/OD4RD/Main-Help-Desk/files/13451169/PatId_OBSOLETE_Pharmaco_NON-RARE_DGS_Nov2023.xlsx)

I hope this clarify the information, 
Kind Regards
Marie-Cécile

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

Thanks for your help.
I will send the list of pharmacogenetics terms to the expert.

When the expert asked me about these terms, I was also surprised that they used them to code a diagnosis, but I am afraid that in many institutions they are not using the codes properly.

The terms "obsolete" and "not rare" I will translate and add when you send the next TREP.

Kind regards, 

María Elena
