### ISSUE TITLE
Undiagnosed RD: equivalent in SNOMED CT?

### ISSUE THREAD

**Issue by Orphabe** [OD4RD/Main-Help-Desk#72]
Dear all,

We received a question during a training from a RD coder (UZ Leuven) regarding the ORPHAcode for undiagnosed patients ("Rare disorder without a determined diagnosis after full investigation", ORPHA:616874). 

They would like to know if there is an equivalent in SNOMED CT. They made their own research and propose the following condition: SNOMED CT 3219008 "Disease type AND/OR category unknown".
See: https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=3219008 

In the last release of the ORPHAcodes-SNOMED CT mapping files, there is of course no (not yet?) equivalent to ORPHA 616874. Do you know  if such an alignment is planned or if this concept will remain a specificity of the Orphanet nomenclature which will not have an exact equivalent in the SNOMED terminology?

Thank you in advance for your feedback, kind regards,

Annabelle (Orphanet Belgium)

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 

Could you look up this request when you have time?
Thank you, 
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @Orphabe, 

Thank you for this question. Indeed, this entity is not mapped due to our own alignment guidelines, contrary to what was announced in the RD-code project. For SNOMED-CT, only exact concepts are mapped. The SNOMED ID 3219008 is included in the clinical finding classification (as parent) and not as a disorder, it does not correspond to the concept represented by the ORPHAcode:616874. For the moment, this alignment will not be present in the next ORPHANET/SNOMED release. 

Best regards, 

Julie
