### ISSUE TITLE
Osteogenesis imperfecta Type XX

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#73]
Hello,

Please find below a request form a Swiss coder:  

"I have a patient with Osteogenesis imperfecta Type XX (OI20), OMIM # 618644. The OMIM Number is not listed in Orphanet. In Orphanet there are five types of OI. My question is now whether a new subtype is needed or whether the OMIM # 618644 can be assigned to one of the existing subtypes. Could you ask the Orphanet team?"

Thanks

**Comment by OrphanetSwitzerland** [comment]
As discussed yesterday in the open session, we received a new request (from a different hospital) concerning OI. In this case, OI type 6 was mentioned in the diagnosis of a patient. In Orphanet, OI type 6 appears as a keyword for OI type 4. Could you please clarify also this issue? Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Apologies for my late reply, as I wanted to collected and update all data prior to answer here.
Orphanet currently leads a large Nomenclature and Classification revision with ERN BOND and ISDS regarding all phenotypes included in OPRHA:364526 'Primary bone dysplasia' [Group of disorders - Category] and ORPHA:364559 'Dysostosis' [Group of disorders - Category]. 
Lots of discussion regards the revision of the OI Group of Disorders and we are trying to update Orphanet Nomenclature in accordance with the new Nosology version 2023 published by the ISDS group of experts (PMID:36779427).
As you can see (compare to the 2019 version) they are now representing and classifying all the bond clinical entities by the genetics assessment (gene related diagnosis) in regards of the OMIM classification. 
The historical Sillence classification (OI type 1 to 5, as it is reprensented in Orphanet) is still mentioned and use as the reference in the field. To facilitate the overview I am adding attached the table from Nosology 2019 (updated and changed in 2023 version).

- Regarding OI type XX, this is form of OI is related to MESD gene mutation (currently linked to OI type 2 ORPHA:216804 ) but indeed this is a more recent type of OI described and we are missing the entity as well as the corresponding OMIM#618644. This is not consider as a new subtype of OI (as per the 1 to 5 historically described).
According to the Nosology we added 'Osteogenesis imperfecta type 20' as a KW of ORPHA:216812 ' and the OMIM# will be updated as well.

- Regarding OI type 6 as a KW of OI type 4 in Orphanet, there is no genetic correlation yet for this form. As presented in the few publications I found PMID:11771667, 17127117 (2007) and the phenotype seems to overlap with OI type 4 ORPHA:216820 as they "conclude that type VI OI is a moderate to severe form of brittle bone disease with accumulation of osteoid due to a mineralization defect, in the absence of a disturbance of mineral metabolism. The underlying genetic defect remains to be elucidated." 
If you have better proofed assessment regarding OI type VI and references from your requester to provide we will be happy to reanalyse it.

- Regarding OI type 8 as a KW of OI type 2 and 3 in Orphanet. Indeed as showed in the 2023 Bond diseases Nosology (PMID:36779427), OI type 8 is associated to mutations in P3H1 gene (LEPRE1) and recognised as an Osteogenesis imperfecta, progressively deforming type (OI type 3) and identified also in perinatal lethal form (OI type 2).

Hope this clarify these issues and will help you answer.
FYI, I am updating and reviewing all Nomenclature data (gene, OMIM, KW, PMID...) changes will be visible in the next 24 hours on the website.

Kind Regards
Marie-Cécile
![OIclassif_Nosology2019](https://github.com/OD4RD/Main-Help-Desk/assets/104562554/f6bcfef4-f233-40fd-bea7-67a13e762165)

**Comment by OrphanetSwitzerland** [comment]
Hello,

We are reopening this issue because some of the announced actions do not seem to have been performed:

“Regarding OI type XX, this is form of OI is related to MESD gene mutation (currently linked to OI type 2 ORPHA:216804 ) but indeed this is a more recent type of OI described and we are missing the entity as well as the corresponding OMIM#618644. This is not consider as a new subtype of OI (as per the 1 to 5 historically described). **According to the Nosology we added 'Osteogenesis imperfecta type 20' as a KW of ORPHA:216812 ' and the OMIM# will be updated as well**.”

We can’t find 'Osteogenesis imperfecta type 20' as a KW for ORPHA:216812, and the same for the OMIM number.

Thank you

**Comment by Mickael-Orphanet** [comment]
Dear @OrphanetSwitzerland , 
I have updated the information. 

Best, 
Mickael
