### ISSUE TITLE
Orphanet nomenclature updates Obsolete terms

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#75]
Dear all,

We would like to share with you a concern brought to our attention by the Catalonia Health Department. Although we understand that, in the end, the decision has to come from each hospital/registry/health authority, perhaps it would be interesting to share practices and experiences among countries and institutions. 

Here you have the text of the message:
“_The management of patient records with cases registered in the past using an ORPHAcode that becomes obsolete is a challenge that for now is not solved in an agile way. If individualized re-analysis of each case is necessary to determine the new code, it will take a great effort to keep the records up to date (and even more in the IT systems of hospitals where many professionals monitor the patient: knowing who assigned the code now obsolete, decide who reviews the code, when, etc.……)_.”

Thank you in advance and kind regards,

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your message and to share this comment with the OD4RD community and all National Hubs.

Indeed, Orphanet is in charge and aim to provide a sustainable Nomenclature and classification coding system for Rare Diseases but cannot be a guaranteed keeper of the management of ORPHAcodes in each Health Care System along time and among different national policies.
Therefor, Orphanet is providing a replacement code or a suggested Groups of disorders to code with for Obsolete and Deprecated entities as well as the release of a differential file in the Pack nomenclature once a year resuming all the code changes.
But it remains to the patient's registries' responsability to set and apply a qualitative politics guaranteeing the traceability and updates of the patient records over time.

I would suggest to keep this discussion going and kindly ask @Orphabe @Orphanet-Italia @OrphanetSweden @OrphanetSwitzerland @OD4RDFIN  @uunter98 @OrphanetDE @OrphanetNL @LeneMartinsen @AMPilarczyk-PL @turnovec  if they want to share or discuss how each national policies/patient' registries deal with updates and maintenance of inactivated ORPHAcodes in their respective country. Please feel free to comment below.

Kind Regards, 
Marie-Cécile

PS: I am closing this issue but I pinned it on top of the issues section for quick access and the comments are still active.

**Comment by Orphanet-ES** [comment]
Dear @MCecile-US14 ,

Thanks for your answer.
Let's see if the colleagues from other teams have something to contribute that can serve as a guide.

Kind regards, 

María Elena

**Comment by OrphanetSweden** [comment]
Dear @Orphanet-ES 

Since Orphanet Sweden have not yet reached the  level of implementation to encounter this issue ourselves, we unfortunately do not have a solution to this problem. It is however an interesting and important issue to discuss further, and we will bring it up with our IT department as well as the parties responsible for hosting healthcare codes and in the future, ORPHAcodes.

Warm regards,
Orphanet Sweden

**Comment by Orphanet-ES** [comment]
Dear @OrphanetSweden ,

Thanks for your feedback.

If you discuss this issue with your technical team, please let us know what conclusions you come to.
And I await the comments of other countries that have faced this problem.

Warm regards,

María Elena

**Comment by LeneMartinsen** [comment]
Dear all,
Thanks @Orphanet-ES for bringing up this important question. In Norway we have not yet encountered this because we are in an early phase of the implementation of ORPHAcodes. However, it will definitely be something that we need to have a solution for. For now, we manually enter patients into the Norwegian registry on rare disorders and can catch these cases if they turn up. However in the future there will be automatic data capture from electronic patient records in the hospital to the registry and we need to think of a solution for the obsolete/depricated codes.

We will discuss this futher in our team after the summer holiday.

All the best,
Lene
Norway

**Comment by Orphanet-ES** [comment]
Dear @LeneMartinsen ,

Thanks for your feedback.

The expert who raised this issue had been using ORPHA codes for years but had not considered code inactivation. 
Suddenly they realized that they had inactive codes, and although we were able to guide them to correct the deprecated and non rare disease codes, the obsolete codes are creating many doubts for them.

Any conclusions you come to when discussing this topic will be very helpful.

All the best,

María Elena

**Comment by Orphanet-Italia** [comment]
Dear @Orphanet-ES , 
we are sorry for the late reply; unfortunately all we can say is that we have not received any comment on this issue from italian professionals so far. Maybe the professional who raised the matter may find useful a file/tool where every inactivated ORPHA code and possibly its inactivation date can be found, in order to have more control over old data.
An easy way to find an old, inactivated ORPHA code, is the dataviz tool https://dataviz.orphacode.org/
but the information about the inactivation date is not available.
We look forward to hearing your feedback, It's a very intersting issue that deserves further discussion and we thank you for sharing it.
Kind regards

The italian team

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-Italia ,

Thanks for your feedback.

We already explained to the expert how to identify the changes with the differential file of the nomenclature pack and with Dataviz, but your suggestion to indicate the date on which a code has been inactivated is interesting.
Perhaps the Orphanet coordination team can consider including this information in future editions of the nomenclature pack.

At the moment the Spanish expert has not contacted us again to discuss this issue, but if we have more information, we will let you know.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES @Orphanet-Italia, 

Thank you for your feedbacks, I take note of your idea to add the date of ORPHAcodes inactivation in the future Nomenclature Pack files and transmit to our technical IT staff for evaluation.
Kind regards, 
Marie-Cécile

**Comment by uunter98** [comment]
Dear Marie-Cecile, dear all, I was wondering if there are technical solutions known to you how to replace or remove inactivated codes in information systems? Do the currently available coding files support this? Austria is only in the process of implementing Orpha codes, and everyone keeps asking ME and complaining, so sorry I do not have any helpful input.. Ursula

**Comment by Orphabe** [comment]
Hi Ursula,

I am afraid I can't help you any further. I asked the manager of the Belgian Central Registry of Rare Diseases (CRRD) how she proceeds to tackle this issue. Here is her answer:

"This is indeed an ‘annoying’ issue that cannot be handled ‘automatically’.

What I always do: after release of the new data pack, I recheck all ORPHAcodes in the registry and manually replace, inactivate, … or whatever action is needed. And I do it each year. Until now, I never contacted the data provider (because of technicalities and privacy) it is difficult to communicate with a DP about a specific patient (although not impossible). The same is true for newly created ORPHAcodes (as we had one last year). 

My future plan is to share the list of patients with each DP for which the code was changed or created, and also to provide them with the new release of the nomenclature pack. Because I never did this before, I cannot yet share you my experience regarding this. One nice thing in the CRRD is that the original code is always kept (I cannot change a registration) but the list that is layed on top can be changed, in this case I add a ‘code’ explaining the history of the disease code assigned by me and not the DP because it became obsolete,... For me, adding the date would not have extra value because I check each year anyway…".

Not sure it helps, sorry :-(

Annabelle (Orphanet Belgium)

**Comment by uunter98** [comment]
Dear Annabelle, thank you, this helps a lot!! 
I wonder if the list of newly inactive ORPHAcodes that is included in the file "ORPHA nomenclature_diff" of the nomenclature pack can be used for some kind of automatization. I have way too little technical knowledge about this, maybe Mark can help? Also Marek knows about these things I guess..

**Comment by Orphanet** [comment]
Dear all,
2 ways to do it :
- yes, you have the "diff" and the status in the nomenclature pack files. Based on that you can compare the content of any orphacode within a dataset, check the current statuts of each code (and if needed the aggregation code etc.)


- API https://api.orphacode.org/ 
GET ​/{lang}​/ClinicalEntity​/orphacode​/{orphacode}​/Status
Search for a clinical entity's status by ORPHAcode
The result retrieves the clinical entity's ORPHAcode and its status (active/inactive).

Which means you can run a script/service/app using the API, get the status of each orphacodes you may have in your database.
Then, for the current inactives, depending on the process you can use :
GET ​/{lang}​/ClinicalEntity​/orphacode​/{orphacode}​/ORPHAcodeAggregation
(Search for a clinical entity's aggregation code by ORPHAcode)

and/or

GET ​/{lang}​/ClinicalEntity​/orphacode​/{orphacode}​/TargetEntity
(Search for the target of an inactive clinical entity by ORPHAcode)
this one should be useful in order to find out to  which "new" possible orphacode point.

(you can also use this one to test directly the inactive/active code. In case of an actual active code, the respons will be :
"Status": "Active",
"Relation": "No relation: the entity is active",
"Target ORPHAcode": "No target ORPHAcode: the entity is active"

The API (Application Programming  Interface) is definitely the most accurate to automation/script processing.
Best regards

**Comment by uunter98** [comment]
Thank you so much, Marc, for your superfast response and the explanation!! I will forward this to the people responsible at our MoH. If anyone else in this group is trying it out, I would be interested to hear about your experiences!
thxx again, Ursula
