### ISSUE TITLE
Who to code?

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#79]
Hello,

In the Swiss Coding Working Group, we discussed who should be assigned with an Orphacode in these two situations:

- Twin to twin transfusion syndrome (ORPHA:95431)
- Placental insufficiency (ORPHA:439167)

In the first case the majority voted for coding the twins and in the second case for coding the mother. 

Would you agree with these decisions? 

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Thank you for your message those 2 coding situations.
- Regarding Twin to twin transfusion syndrome (ORPHA:95431), the code should be used to code both twins if necessary since ORPHA:95431 described the causal clinical situation/diagnosis that can influence the follow up and care for each of them (differently depending who is the transfusor twin who's the transfused twin for instance)
- Regarding the placental insufficency, indeed An ORPHAcode is meant to represent a phenotype, not a patient. In this case we consider that the 'Placental insufficiency' is only a maternal condition/consequence (of various risk factors) and in that sense the corresponding ORPHAcode should be used to code only the mother. Please note that ICD-10/11 also apply same logic since 'Placental insufficiency' is categorized under "maternal care" in their classification. Hence, we do not recommend to use ORPHAcode:439167 to code the baby or child of the mother suffering from placental insufficiency.

This exact last coding question was raised in the RD-CODE GitHub and I answered it few months ago you can consult the detail here [RD CODE issue9](https://github.com/orphanet-rare-diseases-issues/RD-CODE/issues/9).
I will probably update the coding recommendations in the OD4RD Wiki page with these clinical situations as examples.

Kind Regards, 
Marie-Cécile

**Comment by OrphanetSwitzerland** [comment]
Thanks Marie-Cécile,
Martin

**Comment by Marlies99** [comment]
Dear Marie-Cécile

We have discussed the two Orphacodes at length in our working group. What confuses us (in particular, medical coders who work with icd 10 on a daily basis) are the ICD-10 codes. In ICD 10, there are codes for the mother = O-codes and codes for the children = P-codes.

The ICD-10-Code in Orphanet for «ORPHA:95431 Twin to twin transfusion syndrome»  is O43.0 ("Transplacental transfusion syndromes"). In ICD-10 there is also the P-Code "P02.3 Damage to the fetus and newborn due to transplacental transfusion syndromes". Both codes are listed in the chapter "Pathological conditions of the placenta".

The ICD-10-Code in Orphanet for «ORPHA:439167  Placental insufficiency» is O36.5 ("Care of the mother due to fetal growth retardation"). In ICD-10 there is also the P-Code "P02.2 Damage to the fetus and newborn due to other and unspecified morphological and functional placental abnormalities.
placental-:
- Dysfunction
- infarction
- insufficiency"

Based on the logic you put forward, shouldn't "ORPHA:95431 Twin to twin transfusion syndrome" list the P-code P02.3 in Orphanet instead of showing the O-code? For medical coders, an O-code corresponds to the mother and a P-code to a child.

Thank you for your feedback to this.

Kind regards
Marlies

**Comment by MCecile-US14** [comment]
Dear @JTorphanet, 

Can you please clarify and check the correspondance for these ORPHAcodes  regarding the O-code and P-code of ICD Nomenclature ?

Thank you,
Marie-Cécile

**Comment by JTorphanet** [comment]
Dear @Marlies99, 

Thank you for your message! I have reviewed your request and both codes you proposed are good for these entities. 

Coding is specific to each country, depending on its own legislation and the way in which the patient is coded (mother or child). The context should be taken into account, depending on the patient concerned. In conclusion, we have decided to keep both ICD-10 codes for each entity to leave the choice. 

I hope this answers your question.

Thank you for your contribution, 
Julie

**Comment by Marlies99** [comment]
Dear Julie

Thank you for your answer. Okay, somehow this answer does not fit one to one with your previous answer...?!


  *   Regarding Twin to twin transfusion syndrome (ORPHA:95431), the code should be used to code both twins if necessary since ORPHA:95431 described the causal clinical situation/diagnosis that can influence the follow up and care for each of them (differently depending who is the transfusor twin who's the transfused twin for instance)
  *   Regarding the placental insufficency, indeed An ORPHAcode is meant to represent a phenotype, not a patient. In this case we consider that the 'Placental insufficiency' is only a maternal condition/consequence (of various risk factors) and in that sense the corresponding ORPHAcode should be used to code only the mother. Please note that ICD-10/11 also apply same logic since 'Placental insufficiency' is categorized under "maternal care" in their classification. Hence, we do not recommend to use ORPHAcode:439167 to code the baby or child of the mother suffering from placental insufficiency.
Here you do not speak of different countries, but clearly indicate which code is for the mother, which for the child. So you changed your mind?
Kind regards
Marlies


Von: Julie T. - ORPHANET ***@***.***>
Gesendet: Mittwoch, 27. September 2023 19:02
An: OD4RD/Main-Help-Desk ***@***.***>
Cc: Morf, Marlies ***@***.***>; Mention ***@***.***>
Betreff: Re: [OD4RD/Main-Help-Desk] Who to code? (Issue #79)


Dear @Marlies99<https://github.com/Marlies99>,

Thank you for your message! I have reviewed your request and both codes you proposed are good for these entities.

Coding is specific to each country, depending on its own legislation and the way in which the patient is coded (mother or child). The context should be taken into account, depending on the patient concerned. In conclusion, we have decided to keep both ICD-10 codes for each entity to leave the choice.

I hope this answers your question.

Thank you for your contribution,
Julie

**Comment by JTorphanet** [comment]
Dear @Marlies99, 

Indeed, there is a potential misunderstanding. Just to clarify: 
- @MCecile-US14  based her reply on the ICD-10 code aligned at that moment (only "O" ICD-10 codes)
- Following your post, I have reviewed (as Alignment manager) the ICD-10 codes and we have concluded that both "P" and "O" codes are good depending on the country use (several countries do not code fetuses and they only code the mother if needed even if we propose a code for the affected fetus) and the patient we need to code in the medical practice. 

I think it is important to better delineate Orphanet coding recommendations related to the use of ORPHAcodes and the alignment activity. Orphanet provides the rules to use ORPHAcodes but for ICD-10 and other terminologies we propose codes that you could use but it is not mandatory. 

Please @OrphanetNL could you take note of this type of request for your dutch activity report in general and maybe keep in touch with @Marlies99 for future Orphanet nomenclature recommendations. 

I hope my answer clarifies your questions; we stay at your diposal if you need more information.

Best regards, 

Julie

**Comment by Marlies99** [comment]
Dear Julie

Thank you very much for your replay.

Yes I do also think that we have a misunderstanding. Our question has been about the use of the two Orphacodes (ORPHA:95431 Twin to twin transfusion syndrome and  ORPHA:439167Placental insufficiency) not about the ICD-10 Codes. We do not use ICD-10 Codes for coding rare diseases. We use Orphacodes. You explained the use of the Orphacodes with the ICD-10 codes, but unfortunately not entirely correct. Furthermore, the question was not to orphacode a fetus, but the child/children or the mother. I assumed so far that orphacoding is a patient-based coding, not a case based coding like ICD-10 is. Especially with placental insufficiency, the child often suffers later consequences. That’s why we were doubting if not the person affected by consequences should be coded. The placenta not only has maternal part but also a fetal part.

The question is now, should we stick to the guidelines you gave us?

-       ORPHA:95431 Twin to twin transfusion syndrome -> Only the children should be orphacoded

-       ORPHA:439167 Placental insufficiency -> Only the mother should be orphacoded

If we orphacode the mother and the child/ children, the disease may be over-reported in the registry. For demarcation: The ICD-10 coding is primarily about case billing. If the child does not have a case (e.g. because it has not yet been born) the logic consequence is that the mother’s case is coded with an O-Code. But in orphacoding we do not code cases, but a person’s rare disease. For me this is a significant difference in application of coding.

Sorry for my persistence, but we are trying to get the orphacoding right for consistent data in our national registry. Logical and consistent guidelines are therefore very important.

Kind regards
Marlies


Von: Julie T. - ORPHANET ***@***.***>
Gesendet: Montag, 2. Oktober 2023 11:37
An: OD4RD/Main-Help-Desk ***@***.***>
Cc: Morf, Marlies ***@***.***>; Mention ***@***.***>
Betreff: Re: [OD4RD/Main-Help-Desk] Who to code? (Issue #79)


Dear @Marlies99<https://github.com/Marlies99>,

Indeed, there is a potential misunderstanding. Just to clarify:

  *   @MCecile-US14<https://github.com/MCecile-US14> based her reply on the ICD-10 code aligned at that moment (only "O" ICD-10 codes)
  *   Following your post, I have reviewed (as Alignment manager) the ICD-10 codes and we have concluded that both "P" and "O" codes are good depending on the country use (several countries do not code fetuses and they only code the mother if needed even if we propose a code for the affected fetus) and the patient we need to code in the medical practice.

I think it is important to better delineate Orphanet coding recommendations related to the use of ORPHAcodes and the alignment activity. Orphanet provides the rules to use ORPHAcodes but for ICD-10 and other terminologies we propose codes that you could use but it is not mandatory.

Please @OrphanetNL<https://github.com/OrphanetNL> could you take note of this type of request for your dutch activity report in general and maybe keep in touch with @Marlies99<https://github.com/Marlies99> for future Orphanet nomenclature recommendations.

I hope my answer clarifies your questions; we stay at your diposal if you need more information.

Best regards,

Julie

**Comment by caterina-lucano-orphanet** [comment]
Dear @Marlies99 , 
Sorry for my late reply; Marie-Cécile and Julie have brought up this issue in our internal meeting and we have re-discussed the matter.

I think that there has simply been a misunderstanding between coding with ORPHAcodes and/or with ICD-10, and alignments of ORPHAcodes with ICD-10.

I want to stress that ORPHAcodes are aligned to other terminologies with several different relationships, and every alignment is not necessarily an exact match. Therefore, you can have several ICD-10 codes linked to the same ORPHA or a single ICD-10 linked to multiple ORPHAcodes.
When you asked for clarification about the "O/P" ICD-10 codes for ORPHA:95431 and OPRHA:439167, we started a review of the alignments, and we decided to keep both ICD codes aligned to increase the interoperability and to leave to each country the choice of the good ICD code to assign according to the recommendations and practices for ICD coding they are implementing. Therefore, when Julie replied to you that “coding is specific to each country” and that “the context should be taken into account, depending on the patient concerned” she was talking about ICD coding, for which we cannot issue any recommendation. Alignment of ORPHAcodes to other terminologies is done in order to help with data interoperability and ICD codes are given as suggestions for users and coders, but we are not in charge of establishing ICD coding rules or usage. 

This said, as for official ORPHAcoding recommendations, what Marie-Cécile stated at the beginning of this ticket still stands: we recommend using the code ORPHA:95431 Twin to twin transfusion syndrome for coding the twin babies; on the other hand, we recommend using ORPHA:439167 Placental insufficiency to code the mother. 

ORPHAcodes are indeed used to code the main clinical diagnosis of the patient. As you were correctly saying, ORPHAcodes do not code cases, but a person’s rare disease/diagnosis. Therefore, even if the placenta is a shared organ, the fetuses/neonates will need to be coded with the appropriate code for their condition resulting from the placental insufficiency (ex: growth restriction, distress, or death) with an appropriate code (ORPHA if the condition is rare, ICD/other codes if it is not). Placental insufficiency in fact will not be the child's main diagnosis, but the condition resulting from placental insufficiency will be their diagnosis. Moreover, as you mentioned, to avoid overrepresentation in the registry, it is not recommended to code both the mother and the child with the same code. 
  
We kindly encourage you to also get in touch with @OrphanetNL for national coding recommendations; the NL Orphanet team is here to provide Orphanet general and specific country-dependent coding recommendations. 

Do not hesitate to come back to us if you have further doubts on this or other issues.
Kind regards,

Caterina Lucano
Orphanet scientific team coordinator
