### ISSUE TITLE
Use of ORPHAcodes belonging to a group: National official requirements

### ISSUE THREAD

**Issue by Orphanet-ES** [OD4RD/Main-Help-Desk#86]
Dear all,

In the document [7_ADVANCED-How-to-choose-the-right-code_CHAPTER-5_V3_script.pptx](https://network.orphanet.org/7_advanced-how-to-choose-the-right-code_chapter-5_v3_script/), regarding the use of disorder group ORPHAcodes, they are allowed if it is an "national official requirement".
In the script on this slide it says that "in Italy some groups are listed in the offcial RD List and thus need to be used for reimbursement purposes".
Could you tell me what these groups of disorders are? 
Because an expert from a Spanish registry would be interested in knowing.

Kind regards, 

María Elena

**Comment by MCecile-US14** [comment]
Dear @Orphanet-ES, 

Thank you for your comment. Indeed we added this mention in the script (not in the slide) of the presentation we provided in order to clarify that despite Orphanet Nomenclature recommendations, some national adjustements are/have to be made depending of each healthcare political situation accross UE. The mention of Italy was an example we know but there is other countries. This is something we can discuss in WP4 open sessions with all Orphanet NH :)

@Orphanet-Italia could you please specify the list of official RD that are concerned for 'national official requirements' or the context of how the list is created/updated and enlight @Orphanet-ES ?
Thank you for your help, 
Kind Regards
Marie-Cécile

**Comment by Orphanet-Italia** [comment]
Dear @Orphanet-ES , we are sorry for the out of time reply, we hope that the following informations will be helpful in the future anyway.
We highly recommend to read the following document, coauthored by Orphanet Italia (prof. B. Dallapiccola) and issued in 2017, but still relevant to understand how the system works.
Here follow the link to the above mentioned document (in italian); please note that you can find the interesting contents at pages 5 (chapter 3: essentials level of care and list of rare diseases) and 6 (chapter 4: codes and groups, methodologic introduction) of the file:

file:///C:/Users/michele.nutini/Downloads/guida-esenzioni-mr-2019%20(3).pdf

To summarize, the italian Healthcare System attributes exemption codes (_codice esenzione_) either to single rare diseases or to groups of diseases. The interesting concept behind the groups, is that they have been created to be **open**: even if a specific rare disorder is not mentioned in the list, it can nonetheless fall within an officially recognized group and consequently have an exemption code (_codice esenzione_) that allows the patient to access the cost exemption for specific treatments at the Centre of Expertise. 
You can find useful to access the official website/search engine of the Ministry of Health-National Institute of Health dedicated to rare diseases (https://www.malattierare.gov.it/).
Here follow the link to the officially recognized group “OTHER LYSOSOMAL STORAGE DISEASES” :

https://www.malattierare.gov.it/malattie/dettaglio/7318

We are at disposal for further clarifications.
Warm regards

The italian team

**Comment by Orphanet-ES** [comment]
Dear @Orphanet-Italia ,

Thanks for your answer.
This information is very interesting, and I will forward it to the experts who asked about coding by disease groups.

Warm regards, 

María Elena
