### ISSUE TITLE
ORPHA:251880 – Ependymoblastoma

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#87]
Hello,

Doubt from a Swiss coder on whether to use or not the ORPHA:251880 – Ependymoblastoma for a patient. 

She argues that the term seems to be outdated (or at least the Orphanet definition needs to be revised).

Please see: 
-	https://www.cancer.gov/types/brain/hp/child-ependymoma-treatment-pdq: “Ependymoblastoma is no longer recognized in the WHO classification and is now classified as an embryonal tumor with multilayered rosettes”.
-	https://www.frontiersin.org/articles/10.3389/fneur.2022.964856/full: Ependymoblastoma is a PNET according to the 2007 CNS Tumor Classification Guidelines. In the 2016 update of CNS tumor classification guidelines, ependymoblastoma was redefined as an embryonic tumor with multilayer rosettes (ETMR), with amplification of the C19MC region on chromosome 19, rich in nerve cells and true rosettes.

Thank you

**Comment by MCecile-US14** [comment]
Dear @Orphanet-AysegulSenol, 

Could you please take a look at this request to update the definition ORPHA:251880 - Ependymoblastoma ?

@OrphanetSwitzerland, please note, this is not considered in our top priority list since the definition is probably already outdated but it was edited in 2014, FYI we are currently working on older definitions' revision and slowly revising newer entities :)

Kind Regards, 
Marie-Cécile

**Comment by Orphanet-AysegulSenol** [comment]
Dear @OrphanetSwitzerland,

I wanted to update you that, your request is now in the priority list and I will be keeping you updated in following weeks,

Best regards,

Aysegul
