### ISSUE TITLE
Pituitary carcinoma

### ISSUE THREAD

**Issue by galyea123** [OD4RD/Main-Help-Desk#89]
Notice that in the definition it is used "adenoma" instead of "carcinoma".

**Comment by MCecile-US14** [comment]
Dear @galyea123, 

Indeed the short definition of 'Pituitary carinoma' ORPHA:300385 described 'A rare pituitary tumor characterized by the presence of a pituitary adenoma that has metastasized ...' meaning into a cancerous/agressive tumor. This is a correct description since pituitary adenomas are not rare, so Orphanet represents only 'Pituitary carcinomas' whom is a small percentage of adenomas of the pituitary gland.

Thanks for your contribution, 
Kind regards, 
Marie-Cécile (Orphanet coord. team)
