### ISSUE TITLE
ORPHA:90076 - Partial deep dermal and full thickness burns

### ISSUE THREAD

**Issue by OrphanetSwitzerland** [OD4RD/Main-Help-Desk#92]
Hello,

A doubt discussed in the Swiss Coding Working Group: 

In which context would you recommend the use of the code ORPHA:90076 - Partial deep dermal and full thickness burns?

As there is no definition of the entity, how to assess if a patient can be assigned such a code? Is there a minimum percentage of the body surface that has to be burned at this degree (in the German name it is degree IIB and/or III)?

Thanks

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

ORPHA:90076 'Partial deep dermal and full thickness burns' is an entity that had an UE or US orphan designation this is why there is not definition available.
In Orphanet, his preferential parent is the wide 'Other dermis disorder' group ORPHA:79381 and as you can see on DataViz the ICD-10 code T30.3 'Burn of third degree, body region unspecified' has been attributed with NTBT relationship by Orphanet (meaning ICD code is broader than ORPHAcode). And it corresponds to degree IIB and/or III in the German clinical system based on their german knowledge policy, clinical activities etc... 
We cannot provide more detailed specifications regarding the use of the code as it is responsability of each country to clarify/specify their own recommendations based on existing patient/ context and national regulation of clinical trials/orphan designation context. If more details needed we advice to check the clinical trials (4) and research project (1) referenced in the Orphanet website for this entity.

Kind Regards, 
Marie-Cécile

**Comment by OrphanetSwitzerland** [comment]
As a follow-up of yesterday’s coding open session, I include here the question from the Swiss coding group:  Despite the previous answer, it is not clear yet the scope of this code, why it was created and how to use it. Thanks

**Comment by OrphanetSwitzerland** [comment]
Kind reminder.

With some added info: The coder asked the head physician for plastic surgery concerning the entity and here is the answer: “It's difficult for me to answer that because I'm not clear what the purpose or consequence is. In principle, if you take them all, 2b and 3 injuries are too common to be considered rare diseases, I think. If you want to make it meaningful, then perhaps all 3rd degree plus all second degree (2a to 3) from over 10% body surface area affected”.

**Comment by MCecile-US14** [comment]
Dear @OrphanetSwitzerland, 

Sorry for delayed answer, I reviewed the case based on your question and the comments from the coder and the physician, unfortunately I do not have much more information to provide than:

- This entity has been created as a particular clinical situation, as oftened in those case in Orphanet because 4 active Orphan Designations (OD) are currently associated to ORPHA:90076, in Europe, see the screenshot from the EC ref website. As you can see two of them are very recent (2021 and 2022) and Orphanet has the legal obligation to represent it then (as rare conditions). https://ec.europa.eu/health/documents/community-register/html/reg_od_act.htm?sort=a

<img width="539" alt="image" src="https://github.com/user-attachments/assets/c7edc8f9-4f19-42b9-9743-9b47ab7e381e">

- As I found an expired [OD EMA document](https://www.ema.europa.eu/en/medicines/human/orphan-designations/eu-3-02-107), you can read in the definition "_Second-degree burns are divided into two groups. These are called superficial and deep partial-thickness burns_"[...] "_Third-degree burns involve all skin layers (full thickness)_"[...] "_Deep partial or full-thickness burns can be life-threatening_." > **confirming the use of the code for 2nd (IIa and IIb in particular) for the deep but partial-thickness burns and 3rd (III) degree for the full thickness burns.** as specified before.

- Even if this OD was withdraw in 2022, you can read in the note of stage of development of this medicine "_Update: Purified bromelain (NexoBrid) was authorised in the EU on 18 December 2012 for removal of eschar in adults with deep partial- and full-thickness thermal burns_." 
As mentioned in the European Product Assessment Report of Nexobrid
[NexoBrid | European Medicines Agency (EMA) (europa.eu)](https://www.ema.europa.eu/en/medicines/human/EPAR/nexobrid), "_NexoBrid is a medicine used for removing eschar (dead tissue which is dried out, thick, leathery and black) due to skin burns caused by heat or fire. It can be used both for deep partial-thickness burns (sometimes called ‘second degree’ burns) which extend into a deep region of an inner layer of the skin called the dermis, and full-thickness burns (sometimes called ‘third degree’ burns) which extend even deeper, through the whole dermis_"

- In each EMA OD is also dispalyed the estimated number of patients affected by the condition (1:10,000), information provided by the COMP, which Orphanet refered as the rarity criteria based on Regulation (EC) No 141/2000 establishing the rarity threshold < 5:10,000 in UE population. Again this entity as it is "**Partial deep dermal and full-tickness burns" in all OD is considered rare in Europe**

To conclude, I am not sure to understand what is the point and difficulty of the physician and coder to use ORPHA:90076 ? is the problem it refers to ICD-10 code that is only 3rd degree burns (but NTBT alignment with the ORPHAcode)?

Hope this helps, 
Kind Regards, 
Marie-Cécile

**Comment by OrphanetSwitzerland** [comment]
Merci, Marie-Cécile. I will share your answer with the group of coders. And all the best for the future! It was a pleasure working with you.

**Comment by MCecile-US14** [comment]
> Merci, Marie-Cécile. I will share your answer with the group of coders. And all the best for the future! It was a pleasure working with you.

Merci Martin ! Pleasure shared, good luck to Orphanet Switzerland :)
