### ISSUE TITLE
Confusion related to Jacobs syndrome

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#97]
Hello,

We discovered that Jacobs syndrome is used as a synonym for ORPHA:2848 Camptodactyly-arthropathy-coxa-vara-pericarditis syndrome, but Jacobs syndrome is a well known name for 47 XYY (ORPHA:8)
See examples here:
https://pubmed.ncbi.nlm.nih.gov/32491631/
https://frambu.no/diagnose/47-xyy-syndrom/

This is confusing. It might even be wrong. Suggestions: Move Jacobs syndrome (as a synonyme) from ORPHA:2848 to ORPHA:8.

Kind regards,
Lene

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

I have checked your request and indeed there is a confusion. The synonym "Jacobs syndrome" for ORPHA:2848 Camptodactyly-arthropathy-coxa-vara-pericarditis syndrome is only based on OMIM due to the first publications related to this phenotype. When I check all the references in Pubmed related to this disease, no one use this name to identify the disease (PMIDs: 21924065, 36694203, 23290693, 23756439). I will remove it from this entity. 

And as you proposed, Jacobs syndrome is used as a synonym for the 47 XYY syndrome. 

I have just done the modification and it will be visible in the next 24H on our website! 

Thank you for your contribution, 
Best, 
Julie
