### ISSUE TITLE
ORPHA:262128 Partial deletion of the long arm of chromosome 16

### ISSUE THREAD

**Issue by LeneMartinsen** [OD4RD/Main-Help-Desk#99]
Hi,
We have a request from a professional who needs a code for a patient with 16q22 deletion syndrome. OMIM: 614541 https://www.omim.org/entry/614541?search=614541&highlight=614541

Could a code be made or do you recommend using the group code ORPHA:262128 together with OMIM?

Kind regards,
Lene

**Comment by JTorphanet** [comment]
Dear @LeneMartinsen, 

Thanks for your request. Usually, we don't recommend to use ORPHAcode of a group to code patient. Moreover, we already have 2 disorders under this group (ORPHA: 262128) but concern 16q24 microdeletion and the OMIM is related to 16q22 microdeletion. I need to review this potential creation. 

Just to inform you, we have a high number of requests for september; I will be able to present this creation to the Orphanet committee in October. 

Thank you, 
Best, 

Julie

**Comment by LeneMartinsen** [comment]
Thank you, @JTorphanet !
Yes, we are aware of the other two diagnosis under that group code.
We will await your review.

Best,
Lene

**Comment by MCecile-US14** [comment]
Dear @LeneMartinsen dear @OD4RD/helpdesknorway,  

Thank you for your suggestion. After revision, Orphanet' medical and scientific commitee decided to create the ID:31933 '16q22 deletion syndrome' ORPHA:658540 that is indeed missing in our Nomenclature.
It will be classified under 'Partial deletion of the long arm of chromosome 16' [Group of disorders - Category] ORPHA:262128.
In this type of situation (cytogenetics abnormalities) we do not recommend to code with the upstream Group of Disorders but as you did, first suggest a creation of a dedicated code (in this case, many literature references and case reports exist since 1983).

Changes will be visible within 24 hours on the website.
Kind Regards, 
Marie-Cécile
